import type { CAPICrossword } from '../../src/@types/CAPI';

export const everyman: CAPICrossword = {
	id: 'crosswords/everyman/4071',
	number: 4071,
	name: 'Everyman crossword No 4,071',
	date: 1729987200000,
	webPublicationDate: 1729983645000,
	entries: [
		{
			id: '1-across',
			number: 1,
			humanNumber: '1',
			clue: 'Old Testament prophet seen in tam-o’-shanter (4)',
			direction: 'across',
			length: 4,
			group: ['1-across'],
			position: {
				x: 3,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '4-across',
			number: 4,
			humanNumber: '4',
			clue: 'Intensity regularly dropped in avian protection (4)',
			direction: 'across',
			length: 4,
			group: ['4-across'],
			position: {
				x: 8,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '8-across',
			number: 8,
			humanNumber: '8',
			clue: '‘How eerie!’ ‘Why, sure!’ Uneasy sentiment when abroad (4,3,4,4)',
			direction: 'across',
			length: 15,
			group: ['8-across'],
			position: {
				x: 0,
				y: 2,
			},
			separatorLocations: {
				',': [4, 7, 11],
			},
		},
		{
			id: '11-across',
			number: 11,
			humanNumber: '11',
			clue: 'Chose, after imbibing drop of Laphroaig, to become drunk (7)',
			direction: 'across',
			length: 7,
			group: ['11-across'],
			position: {
				x: 0,
				y: 4,
			},
			separatorLocations: {},
		},
		{
			id: '12-across',
			number: 12,
			humanNumber: '12',
			clue: 'Moves heavily wanting sleep after cycling (7)',
			direction: 'across',
			length: 7,
			group: ['12-across'],
			position: {
				x: 8,
				y: 4,
			},
			separatorLocations: {},
		},
		{
			id: '13-across',
			number: 13,
			humanNumber: '13',
			clue: 'With buff back muscles, doing a flip, they’re resolute (9)',
			direction: 'across',
			length: 9,
			group: ['13-across'],
			position: {
				x: 0,
				y: 6,
			},
			separatorLocations: {},
		},
		{
			id: '14-across',
			number: 14,
			humanNumber: '14',
			clue: 'Tax channel (5)',
			direction: 'across',
			length: 5,
			group: ['14-across'],
			position: {
				x: 10,
				y: 6,
			},
			separatorLocations: {},
		},
		{
			id: '15-across',
			number: 15,
			humanNumber: '15',
			clue: 'Wristwatch, say: not so exciting but a becoming one (5)',
			direction: 'across',
			length: 5,
			group: ['15-across'],
			position: {
				x: 0,
				y: 8,
			},
			separatorLocations: {},
		},
		{
			id: '16-across',
			number: 16,
			humanNumber: '16',
			clue: 'Like a competition involving multiple setters? (3-3-3)',
			direction: 'across',
			length: 9,
			group: ['16-across'],
			position: {
				x: 6,
				y: 8,
			},
			separatorLocations: {
				'-': [3, 6],
			},
		},
		{
			id: '19-across',
			number: 19,
			humanNumber: '19',
			clue: 'Ghastly duck penetrating – we need camouflage! (7)',
			direction: 'across',
			length: 7,
			group: ['19-across'],
			position: {
				x: 0,
				y: 10,
			},
			separatorLocations: {},
		},
		{
			id: '21-across',
			number: 21,
			humanNumber: '21',
			clue: '<span>Erstwhile capital offence: </span><i>agent provocateur</i><span> finally taken, 7 beheaded</span> (7)',
			direction: 'across',
			length: 7,
			group: ['21-across'],
			position: {
				x: 8,
				y: 10,
			},
			separatorLocations: {},
		},
		{
			id: '22-across',
			number: 22,
			humanNumber: '22',
			clue: '<span>Liberally salt the roast, say? Who </span><i>does</i><span> that any more?</span> (5,2,4,4)',
			direction: 'across',
			length: 15,
			group: ['22-across'],
			position: {
				x: 0,
				y: 12,
			},
			separatorLocations: {
				',': [5, 7, 11],
			},
		},
		{
			id: '23-across',
			number: 23,
			humanNumber: '23',
			clue: 'Everyman gripped by American science fiction? Hardly (2,2)',
			direction: 'across',
			length: 4,
			group: ['23-across'],
			position: {
				x: 3,
				y: 14,
			},
			separatorLocations: {
				',': [2],
			},
		},
		{
			id: '24-across',
			number: 24,
			humanNumber: '24',
			clue: 'What pothead may get from – or do to – his habit (4)',
			direction: 'across',
			length: 4,
			group: ['24-across'],
			position: {
				x: 8,
				y: 14,
			},
			separatorLocations: {},
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2',
			clue: 'Historic ship showing might on river (9)',
			direction: 'down',
			length: 9,
			group: ['2-down'],
			position: {
				x: 4,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'Quiet location for milk … shake (7)',
			direction: 'down',
			length: 7,
			group: ['3-down'],
			position: {
				x: 6,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: 'Annoys the French (a primary requirement)? (7)',
			direction: 'down',
			length: 7,
			group: ['4-down'],
			position: {
				x: 8,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '5-down',
			number: 5,
			humanNumber: '5',
			clue: 'Energy shown by Second XI? (5)',
			direction: 'down',
			length: 5,
			group: ['5-down'],
			position: {
				x: 10,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '6-down',
			number: 6,
			humanNumber: '6',
			clue: 'Pinches small tissues (6)',
			direction: 'down',
			length: 6,
			group: ['6-down'],
			position: {
				x: 0,
				y: 1,
			},
			separatorLocations: {},
		},
		{
			id: '7-down',
			number: 7,
			humanNumber: '7',
			clue: 'Shaking tail end, watch a lad fall in Vermont, for example? (6)',
			direction: 'down',
			length: 6,
			group: ['7-down'],
			position: {
				x: 14,
				y: 1,
			},
			separatorLocations: {},
		},
		{
			id: '9-down',
			number: 9,
			humanNumber: '9',
			clue: 'TikTok etc, therefore claim idea is deranged (6,5)',
			direction: 'down',
			length: 11,
			group: ['9-down'],
			position: {
				x: 2,
				y: 2,
			},
			separatorLocations: {
				',': [6],
			},
		},
		{
			id: '10-down',
			number: 10,
			humanNumber: '10',
			clue: 'On the phone, Ms Raducanu will call Ireland (7,4)',
			direction: 'down',
			length: 11,
			group: ['10-down'],
			position: {
				x: 12,
				y: 2,
			},
			separatorLocations: {
				',': [7],
			},
		},
		{
			id: '14-down',
			number: 14,
			humanNumber: '14',
			clue: 'Using reason, conciliated freely? That’s not on! (9)',
			direction: 'down',
			length: 9,
			group: ['14-down'],
			position: {
				x: 10,
				y: 6,
			},
			separatorLocations: {},
		},
		{
			id: '15-down',
			number: 15,
			humanNumber: '15',
			clue: '<span>Turncoats abandoning </span><i>HMS</i><span> inhabited this island, primarily?</span> (6)',
			direction: 'down',
			length: 6,
			group: ['15-down'],
			position: {
				x: 0,
				y: 8,
			},
			separatorLocations: {},
		},
		{
			id: '16-down',
			number: 16,
			humanNumber: '16',
			clue: 'Scribble, leave hurriedly (4,3)',
			direction: 'down',
			length: 7,
			group: ['16-down'],
			position: {
				x: 6,
				y: 8,
			},
			separatorLocations: {
				',': [4],
			},
		},
		{
			id: '17-down',
			number: 17,
			humanNumber: '17',
			clue: 'Understand second Beatles hit (3,4)',
			direction: 'down',
			length: 7,
			group: ['17-down'],
			position: {
				x: 8,
				y: 8,
			},
			separatorLocations: {
				',': [3],
			},
		},
		{
			id: '18-down',
			number: 18,
			humanNumber: '18',
			clue: 'They’re beyond help? King George succeeded in the protection of one (6)',
			direction: 'down',
			length: 6,
			group: ['18-down'],
			position: {
				x: 14,
				y: 8,
			},
			separatorLocations: {},
		},
		{
			id: '20-down',
			number: 20,
			humanNumber: '20',
			clue: 'Where to get dates and a drink for ‘90s rockers (5)',
			direction: 'down',
			length: 5,
			group: ['20-down'],
			position: {
				x: 4,
				y: 10,
			},
			separatorLocations: {},
		},
	],
	solutionAvailable: false,
	dateSolutionAvailable: 1730592000000,
	dimensions: {
		cols: 15,
		rows: 15,
	},
	crosswordType: 'everyman',
	pdf: 'https://crosswords-static.guim.co.uk/obs.everyman.20241027.pdf',
};
