import type { CAPICrossword } from '../../src/@types/CAPI';

export const groupedClues: CAPICrossword = {
	id: 'crosswords/prize/25220',
	number: 25220,
	name: 'Prize crossword No 25,220',
	creator: {
		name: 'Araucaria',
		webUrl: 'https://www.theguardian.com/profile/araucaria',
	},
	date: 1295049600000,
	webPublicationDate: 1295049600000,
	entries: [
		{
			id: '7-across',
			number: 7,
			humanNumber: '7',
			clue: 'See 23',
			direction: 'across',
			length: 8,
			group: [
				'23-across',
				'25-across',
				'26-across',
				'22-down',
				'11-across',
				'7-across',
				'10-across',
			],
			position: {
				x: 0,
				y: 1,
			},
			separatorLocations: {
				',': [1, 3, 6],
			},
			solution: 'WITHOUTA',
		},
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: "The general view is it's a vice (6)",
			direction: 'across',
			length: 6,
			group: ['9-across'],
			position: {
				x: 9,
				y: 1,
			},
			separatorLocations: {},
			solution: 'AGREED',
		},
		{
			id: '10-across',
			number: 10,
			humanNumber: '10',
			clue: 'See 23',
			direction: 'across',
			length: 4,
			group: [
				'23-across',
				'25-across',
				'26-across',
				'22-down',
				'11-across',
				'7-across',
				'10-across',
			],
			position: {
				x: 0,
				y: 3,
			},
			separatorLocations: {
				',': [],
			},
			solution: 'NAME',
		},
		{
			id: '11-across',
			number: 11,
			humanNumber: '11',
			clue: 'See 23',
			direction: 'across',
			length: 10,
			group: [
				'23-across',
				'25-across',
				'26-across',
				'22-down',
				'11-across',
				'7-across',
				'10-across',
			],
			position: {
				x: 5,
				y: 3,
			},
			separatorLocations: {
				',': [4, 6],
			},
			solution: 'WORTHANAGE',
		},
		{
			id: '12-across',
			number: 12,
			humanNumber: '12',
			clue: 'Weird agent holds love authorised (6)',
			direction: 'across',
			length: 6,
			group: ['12-across'],
			position: {
				x: 0,
				y: 5,
			},
			separatorLocations: {},
			solution: 'SPOOKY',
		},
		{
			id: '14-across',
			number: 14,
			humanNumber: '14',
			clue: 'See 22',
			direction: 'across',
			length: 8,
			group: ['22-across', '14-across'],
			position: {
				x: 7,
				y: 5,
			},
			separatorLocations: {
				',': [3],
			},
			solution: 'TOOSHORT',
		},
		{
			id: '15-across',
			number: 15,
			humanNumber: '15',
			clue: 'See 22 down',
			direction: 'across',
			length: 7,
			group: ['22-down', '15-across'],
			position: {
				x: 0,
				y: 7,
			},
			separatorLocations: {
				',': [],
			},
			solution: 'LEISURE',
		},
		{
			id: '17-across',
			number: 17,
			humanNumber: '17',
			clue: "Witch's home's point in support (7)",
			direction: 'across',
			length: 7,
			group: ['17-across'],
			position: {
				x: 8,
				y: 7,
			},
			separatorLocations: {},
			solution: 'ENDORSE',
		},
		{
			id: '20-across',
			number: 20,
			humanNumber: '20',
			clue: 'Playing tapes about small flower (5,3)',
			direction: 'across',
			length: 8,
			group: ['20-across'],
			position: {
				x: 0,
				y: 9,
			},
			separatorLocations: {
				',': [5],
			},
			solution: 'SWEETPEA',
		},
		{
			id: '22-across',
			number: 22,
			humanNumber: '22, 14',
			clue: " We haven't time to waste on trivia: how about art? (4,2,3,5)",
			direction: 'across',
			length: 6,
			group: ['22-across', '14-across'],
			position: {
				x: 9,
				y: 9,
			},
			separatorLocations: {
				',': [4, 6],
			},
			solution: 'LIFEIS',
		},
		{
			id: '23-across',
			number: 23,
			humanNumber: '23, 25, 26, 22, 11, 7, 10',
			clue: 'O Swindon Town! outed from highest league — a fair cow — or a Houlier needed: would this clarion call be any compensation? (3,7,4,2,8,4,2,5,2,3,7,1,4)',
			direction: 'across',
			length: 10,
			group: [
				'23-across',
				'25-across',
				'26-across',
				'22-down',
				'11-across',
				'7-across',
				'10-across',
			],
			position: {
				x: 0,
				y: 11,
			},
			separatorLocations: {
				',': [3, 10],
			},
			solution: 'ONECROWDED',
		},
		{
			id: '24-across',
			number: 24,
			humanNumber: '24',
			clue: 'NHS advisers are respectable and fastid­ious (4)',
			direction: 'across',
			length: 4,
			group: ['24-across'],
			position: {
				x: 11,
				y: 11,
			},
			separatorLocations: {},
			solution: 'NICE',
		},
		{
			id: '25-across',
			number: 25,
			humanNumber: '25',
			clue: 'See 23',
			direction: 'across',
			length: 6,
			group: [
				'23-across',
				'25-across',
				'26-across',
				'22-down',
				'11-across',
				'7-across',
				'10-across',
			],
			position: {
				x: 0,
				y: 13,
			},
			separatorLocations: {
				',': [4, 6],
			},
			solution: 'HOUROF',
		},
		{
			id: '26-across',
			number: 26,
			humanNumber: '26',
			clue: 'See 23',
			direction: 'across',
			length: 8,
			group: [
				'23-across',
				'25-across',
				'26-across',
				'22-down',
				'11-across',
				'7-across',
				'10-across',
			],
			position: {
				x: 7,
				y: 13,
			},
			separatorLocations: {
				',': [8],
			},
			solution: 'GLORIOUS',
		},
		{
			id: '1-down',
			number: 1,
			humanNumber: '1',
			clue: 'Bramley over the pond? (3,5)',
			direction: 'down',
			length: 8,
			group: ['1-down'],
			position: {
				x: 1,
				y: 0,
			},
			separatorLocations: {
				',': [3],
			},
			solution: 'BIGAPPLE',
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2, 24',
			clue: " He's a lion, maybe, but I go on a horse (4,4)",
			direction: 'down',
			length: 4,
			group: ['2-down', '24-down'],
			position: {
				x: 3,
				y: 0,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'SHOE',
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'Heartless fugitive on airfield (6)',
			direction: 'down',
			length: 6,
			group: ['3-down'],
			position: {
				x: 5,
				y: 0,
			},
			separatorLocations: {},
			solution: 'RUNWAY',
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: 'Carbon forest settled then and there (4,4)',
			direction: 'down',
			length: 8,
			group: ['4-down'],
			position: {
				x: 9,
				y: 0,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'CASHDOWN',
		},
		{
			id: '5-down',
			number: 5,
			humanNumber: '5',
			clue: 'Être fainéant — and maybe stick (6,4)',
			direction: 'down',
			length: 10,
			group: ['5-down'],
			position: {
				x: 11,
				y: 0,
			},
			separatorLocations: {
				',': [6],
			},
			solution: 'FRENCHLOAF',
		},
		{
			id: '6-down',
			number: 6,
			humanNumber: '6',
			clue: 'One wanting food in pub? (6)',
			direction: 'down',
			length: 6,
			group: ['6-down'],
			position: {
				x: 13,
				y: 0,
			},
			separatorLocations: {},
			solution: 'BEGGAR',
		},
		{
			id: '8-down',
			number: 8,
			humanNumber: '8',
			clue: 'Put bubbles in fresh tea — about time! (6)',
			direction: 'down',
			length: 6,
			group: ['8-down'],
			position: {
				x: 7,
				y: 1,
			},
			separatorLocations: {},
			solution: 'AERATE',
		},
		{
			id: '13-down',
			number: 13,
			humanNumber: '13',
			clue: 'With which comic character pursues shellfish round London? (6,4)',
			direction: 'down',
			length: 10,
			group: ['13-down'],
			position: {
				x: 3,
				y: 5,
			},
			separatorLocations: {
				',': [6],
			},
			solution: 'OYSTERCARD',
		},
		{
			id: '16-down',
			number: 16,
			humanNumber: '16',
			clue: 'Tickings off for agent and so for organiser (8)',
			direction: 'down',
			length: 8,
			group: ['16-down'],
			position: {
				x: 5,
				y: 7,
			},
			separatorLocations: {},
			solution: 'REPROOFS',
		},
		{
			id: '18-down',
			number: 18,
			humanNumber: '18',
			clue: 'Covert plan to get little guy in drink (6-2)',
			direction: 'down',
			length: 8,
			group: ['18-down'],
			position: {
				x: 13,
				y: 7,
			},
			separatorLocations: {
				'-': [6],
			},
			solution: 'STITCHUP',
		},
		{
			id: '19-down',
			number: 19,
			humanNumber: '19',
			clue: 'Petted pet in quiet party held by convict (6)',
			direction: 'down',
			length: 6,
			group: ['19-down'],
			position: {
				x: 7,
				y: 8,
			},
			separatorLocations: {},
			solution: 'LAPDOG',
		},
		{
			id: '21-down',
			number: 21,
			humanNumber: '21',
			clue: "Microsoft's idea to get prize of vintage port (6)",
			direction: 'down',
			length: 6,
			group: ['21-down'],
			position: {
				x: 1,
				y: 9,
			},
			separatorLocations: {},
			solution: 'WINDOW',
		},
		{
			id: '22-down',
			number: 22,
			humanNumber: '22, 15',
			clue: " She needn't do anything for boy to call faulty file reliable (4,2,7)",
			direction: 'down',
			length: 6,
			group: ['22-down', '15-across'],
			position: {
				x: 9,
				y: 9,
			},
			separatorLocations: {
				',': [4, 6],
			},
			solution: 'LADYOF',
		},
		{
			id: '24-down',
			number: 24,
			humanNumber: '24',
			clue: 'See 2',
			direction: 'down',
			length: 4,
			group: ['2-down', '24-down'],
			position: {
				x: 11,
				y: 11,
			},
			separatorLocations: {
				',': [],
			},
			solution: 'NAIL',
		},
	],
	solutionAvailable: true,
	dateSolutionAvailable: 1295654400000,
	dimensions: {
		cols: 15,
		rows: 15,
	},
	crosswordType: 'prize',
	pdf: 'http://static.guim.co.uk/crosswords/pdfs/gdn.cryptic.20110115.pdf',
};
