import type { CAPICrossword } from '../../src/@types/CAPI';

export const miniCryptic: CAPICrossword = {
    name: 'Mini crossword No 47',
    id: 'crosswords/mini/47',
    crosswordType: 'mini',
    number: 47,
    dimensions: {
        cols: 5,
        rows: 5,
    },
    entries: [
        {
            id: '1-across',
            number: 1,
            humanNumber: '1',
            position: {
                x: 0,
                y: 0,
            },
            length: 5,
            clue: 'Sylvester Stallone’s boxing role (5)',
            solution: 'ROCKY',
            direction: 'across',
            group: ['1-across'],
            separatorLocations: {},
        },
        {
            id: '6-across',
            number: 6,
            humanNumber: '6',
            position: {
                x: 0,
                y: 1,
            },
            length: 5,
            clue: 'Ladybug’s lunch (5)',
            solution: 'APHID',
            direction: 'across',
            group: ['6-across'],
            separatorLocations: {},
        },
        {
            id: '7-across',
            number: 7,
            humanNumber: '7',
            position: {
                x: 0,
                y: 2,
            },
            length: 5,
            clue: 'Shopping hangouts before Amazon (5)',
            solution: 'MALLS',
            direction: 'across',
            group: ['7-across'],
            separatorLocations: {},
        },
        {
            id: '8-across',
            number: 8,
            humanNumber: '8',
            position: {
                x: 0,
                y: 3,
            },
            length: 4,
            clue: 'Secret scheme (4)',
            solution: 'PLOT',
            direction: 'across',
            group: ['8-across'],
            separatorLocations: {},
        },
        {
            id: '9-across',
            number: 9,
            humanNumber: '9',
            position: {
                x: 0,
                y: 4,
            },
            length: 3,
            clue: 'Opposite of NNW (3)',
            solution: 'SSE',
            direction: 'across',
            group: ['9-across'],
            separatorLocations: {},
        },
        {
            id: '1-down',
            number: 1,
            humanNumber: '1',
            position: {
                x: 0,
                y: 0,
            },
            length: 5,
            clue: 'Highway exits (5)',
            solution: 'RAMPS',
            direction: 'down',
            group: ['1-down'],
            separatorLocations: {},
        },
        {
            id: '2-down',
            number: 2,
            humanNumber: '2',
            position: {
                x: 1,
                y: 0,
            },
            length: 5,
            clue: 'October birthstones (5)',
            solution: 'OPALS',
            direction: 'down',
            group: ['2-down'],
            separatorLocations: {},
        },
        {
            id: '3-down',
            number: 3,
            humanNumber: '3',
            position: {
                x: 2,
                y: 0,
            },
            length: 5,
            clue: 'Actress Sevigny (5)',
            solution: 'CHLOE',
            direction: 'down',
            group: ['3-down'],
            separatorLocations: {},
        },
        {
            id: '4-down',
            number: 4,
            humanNumber: '4',
            position: {
                x: 3,
                y: 0,
            },
            length: 4,
            clue: 'Bagpiper’s skirt (4)',

            solution: 'KILT',
            direction: 'down',
            group: ['4-down'],
            separatorLocations: {},
        },
        {
            id: '5-down',
            number: 5,
            humanNumber: '5',
            position: {
                x: 4,
                y: 0,
            },
            length: 3,
            clue: 'Football gains, abbr. (3)',
            solution: 'YDS',
            direction: 'down',
            group: ['5-down'],
            separatorLocations: {},
        },
    ],
    creator: {
        name: 'awks',
        webUrl: 'https://www.theguardian.com/profile/awks',
    },
    date: 1730332800000,
    webPublicationDate: 1730332802000,
    solutionAvailable: true,
};