import type { CAPICrossword } from '../../src/@types/CAPI';

export const quickCryptic: CAPICrossword = {
	id: 'crosswords/quick-cryptic/30',
	number: 30,
	name: 'Quick cryptic crossword No 30',
	creator: {
		name: 'Maskarade',
		webUrl: 'https://www.theguardian.com/profile/maskarade',
	},
	date: 1729900800000,
	webPublicationDate: 1729897217000,
	entries: [
		{
			id: '1-across',
			number: 1,
			humanNumber: '1',
			clue: 'Multi-talented relatives worked out (9)',
			direction: 'across',
			length: 9,
			group: ['1-across'],
			position: {
				x: 0,
				y: 0,
			},
			separatorLocations: {},
			solution: 'VERSATILE',
		},
		{
			id: '7-across',
			number: 7,
			humanNumber: '7',
			clue: 'Yields to Wimbledon favourites, we’re told (5)',
			direction: 'across',
			length: 5,
			group: ['7-across'],
			position: {
				x: 0,
				y: 2,
			},
			separatorLocations: {},
			solution: 'CEDES',
		},
		{
			id: '8-across',
			number: 8,
			humanNumber: '8',
			clue: 'Awfully eager to acquiesce (5)',
			direction: 'across',
			length: 5,
			group: ['8-across'],
			position: {
				x: 6,
				y: 2,
			},
			separatorLocations: {},
			solution: 'AGREE',
		},
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: 'Deafening noise of item of sports equipment heard (6)',
			direction: 'across',
			length: 6,
			group: ['9-across'],
			position: {
				x: 0,
				y: 4,
			},
			separatorLocations: {},
			solution: 'RACKET',
		},
		{
			id: '10-across',
			number: 10,
			humanNumber: '10',
			clue: 'Drop leaves on outhouse (4)',
			direction: 'across',
			length: 4,
			group: ['10-across'],
			position: {
				x: 7,
				y: 4,
			},
			separatorLocations: {},
			solution: 'SHED',
		},
		{
			id: '13-across',
			number: 13,
			humanNumber: '13',
			clue: 'Whitish bucket is suggested (4)',
			direction: 'across',
			length: 4,
			group: ['13-across'],
			position: {
				x: 0,
				y: 6,
			},
			separatorLocations: {},
			solution: 'PALE',
		},
		{
			id: '14-across',
			number: 14,
			humanNumber: '14',
			clue: 'Mum’s got small bed charm (6)',
			direction: 'across',
			length: 6,
			group: ['14-across'],
			position: {
				x: 5,
				y: 6,
			},
			separatorLocations: {},
			solution: 'MASCOT',
		},
		{
			id: '17-across',
			number: 17,
			humanNumber: '17',
			clue: 'Bird with the French name (5)',
			direction: 'across',
			length: 5,
			group: ['17-across'],
			position: {
				x: 0,
				y: 8,
			},
			separatorLocations: {},
			solution: 'TITLE',
		},
		{
			id: '19-across',
			number: 19,
			humanNumber: '19',
			clue: 'Precedes to Yorkshire city, according to reports (5)',
			direction: 'across',
			length: 5,
			group: ['19-across'],
			position: {
				x: 6,
				y: 8,
			},
			separatorLocations: {},
			solution: 'LEADS',
		},
		{
			id: '20-across',
			number: 20,
			humanNumber: '20',
			clue: 'Fatigue attacked dissenter (9)',
			direction: 'across',
			length: 9,
			group: ['20-across'],
			position: {
				x: 2,
				y: 10,
			},
			separatorLocations: {},
			solution: 'TIREDNESS',
		},
		{
			id: '1-down',
			number: 1,
			humanNumber: '1',
			clue: 'Parish priest and little girl by vehicle (5)',
			direction: 'down',
			length: 5,
			group: ['1-down'],
			position: {
				x: 0,
				y: 0,
			},
			separatorLocations: {},
			solution: 'VICAR',
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2',
			clue: 'Extremist’s excellent in slang (7)',
			direction: 'down',
			length: 7,
			group: ['2-down'],
			position: {
				x: 2,
				y: 0,
			},
			separatorLocations: {},
			solution: 'RADICAL',
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'The reply is “Warne’s out!” (6)',
			direction: 'down',
			length: 6,
			group: ['3-down'],
			position: {
				x: 4,
				y: 0,
			},
			separatorLocations: {},
			solution: 'ANSWER',
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: 'One hastened to Persia nowadays (4)',
			direction: 'down',
			length: 4,
			group: ['4-down'],
			position: {
				x: 6,
				y: 0,
			},
			separatorLocations: {},
			solution: 'IRAN',
		},
		{
			id: '5-down',
			number: 5,
			humanNumber: '5',
			clue: 'Attention – the Cockney’s present (3)',
			direction: 'down',
			length: 3,
			group: ['5-down'],
			position: {
				x: 8,
				y: 0,
			},
			separatorLocations: {},
			solution: 'EAR',
		},
		{
			id: '6-down',
			number: 6,
			humanNumber: '6',
			clue: 'It’s said that work with dough is a must-have (4)',
			direction: 'down',
			length: 4,
			group: ['6-down'],
			position: {
				x: 10,
				y: 1,
			},
			separatorLocations: {},
			solution: 'NEED',
		},
		{
			id: '11-down',
			number: 11,
			humanNumber: '11',
			clue: 'It has replaced the acre! (7)',
			direction: 'down',
			length: 7,
			group: ['11-down'],
			position: {
				x: 8,
				y: 4,
			},
			separatorLocations: {},
			solution: 'HECTARE',
		},
		{
			id: '12-down',
			number: 12,
			humanNumber: '12',
			clue: 'Young boy came first and served out the soup (6)',
			direction: 'down',
			length: 6,
			group: ['12-down'],
			position: {
				x: 6,
				y: 5,
			},
			separatorLocations: {},
			solution: 'LADLED',
		},
		{
			id: '13-down',
			number: 13,
			humanNumber: '13',
			clue: 'Darlings step out (4)',
			direction: 'down',
			length: 4,
			group: ['13-down'],
			position: {
				x: 0,
				y: 6,
			},
			separatorLocations: {},
			solution: 'PETS',
		},
		{
			id: '15-down',
			number: 15,
			humanNumber: '15',
			clue: 'Lab work for international games (5)',
			direction: 'down',
			length: 5,
			group: ['15-down'],
			position: {
				x: 10,
				y: 6,
			},
			separatorLocations: {},
			solution: 'TESTS',
		},
		{
			id: '16-down',
			number: 16,
			humanNumber: '16',
			clue: 'Squint at member of the House of Lords (4)',
			direction: 'down',
			length: 4,
			group: ['16-down'],
			position: {
				x: 4,
				y: 7,
			},
			separatorLocations: {},
			solution: 'PEER',
		},
		{
			id: '18-down',
			number: 18,
			humanNumber: '18',
			clue: 'Rubbish work on a shuttle (3)',
			direction: 'down',
			length: 3,
			group: ['18-down'],
			position: {
				x: 2,
				y: 8,
			},
			separatorLocations: {},
			solution: 'TAT',
		},
	],
	solutionAvailable: true,
	dateSolutionAvailable: 1729897200000,
	dimensions: {
		cols: 11,
		rows: 11,
	},
	crosswordType: 'quick-cryptic',
	pdf: 'https://crosswords-static.guim.co.uk/gdn.quick-cryptic.20241026.pdf',
	instructions:
		'<b>TODAY’S TRICKS</b> Clues begin or end with a definition of the answer. The rest is one of these:\n<b>Anagram</b>\nAn anagram of the answer and a hint that there’s an anagram\n‘Senator arranged crime (7)’ gives TREASON\n<b>Charade</b>\nA combination of synonyms\n‘Qualify to get drink for ID (8)’ gives PASSPORT (pass + port)\n<b>Double definition</b>\nBoth halves are definitions!\n‘Search scrub (5)’ gives SCOUR\n<b>Soundalike</b>\nSomething that sounds like the answer\n‘Excited as Oscar’s announced (4)’ gives WILD',
};
