import type { CAPICrossword } from '../../src/@types/CAPI';

export const speedy: CAPICrossword = {
	id: 'crosswords/speedy/1516',
	number: 1516,
	name: 'Speedy crossword No 1,516',
	date: 1729987200000,
	webPublicationDate: 1729983644000,
	entries: [
		{
			id: '1-across',
			number: 1,
			humanNumber: '1',
			clue: 'Tangible (8)',
			direction: 'across',
			length: 8,
			group: ['1-across'],
			position: {
				x: 0,
				y: 0,
			},
			separatorLocations: {},
			solution: 'PALPABLE',
		},
		{
			id: '5-across',
			number: 5,
			humanNumber: '5',
			clue: 'Shortage (4)',
			direction: 'across',
			length: 4,
			group: ['5-across'],
			position: {
				x: 9,
				y: 0,
			},
			separatorLocations: {},
			solution: 'LACK',
		},
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: 'Stand-offish (5)',
			direction: 'across',
			length: 5,
			group: ['9-across'],
			position: {
				x: 0,
				y: 2,
			},
			separatorLocations: {},
			solution: 'ALOOF',
		},
		{
			id: '10-across',
			number: 10,
			humanNumber: '10',
			clue: 'Precarious (7)',
			direction: 'across',
			length: 7,
			group: ['10-across'],
			position: {
				x: 6,
				y: 2,
			},
			separatorLocations: {},
			solution: 'PARLOUS',
		},
		{
			id: '11-across',
			number: 11,
			humanNumber: '11',
			clue: 'Causing cancer (12)',
			direction: 'across',
			length: 12,
			group: ['11-across'],
			position: {
				x: 1,
				y: 4,
			},
			separatorLocations: {},
			solution: 'CARCINOGENIC',
		},
		{
			id: '13-across',
			number: 13,
			humanNumber: '13',
			clue: 'Confer holy orders (6)',
			direction: 'across',
			length: 6,
			group: ['13-across'],
			position: {
				x: 0,
				y: 6,
			},
			separatorLocations: {},
			solution: 'ORDAIN',
		},
		{
			id: '14-across',
			number: 14,
			humanNumber: '14',
			clue: 'Wild ass (6)',
			direction: 'across',
			length: 6,
			group: ['14-across'],
			position: {
				x: 7,
				y: 6,
			},
			separatorLocations: {},
			solution: 'ONAGER',
		},
		{
			id: '17-across',
			number: 17,
			humanNumber: '17',
			clue: 'Place in brackets (12)',
			direction: 'across',
			length: 12,
			group: ['17-across'],
			position: {
				x: 0,
				y: 8,
			},
			separatorLocations: {},
			solution: 'PARENTHESIZE',
		},
		{
			id: '20-across',
			number: 20,
			humanNumber: '20',
			clue: 'Driving force (7)',
			direction: 'across',
			length: 7,
			group: ['20-across'],
			position: {
				x: 0,
				y: 10,
			},
			separatorLocations: {},
			solution: 'IMPETUS',
		},
		{
			id: '21-across',
			number: 21,
			humanNumber: '21',
			clue: 'Legally bar or preclude (5)',
			direction: 'across',
			length: 5,
			group: ['21-across'],
			position: {
				x: 8,
				y: 10,
			},
			separatorLocations: {},
			solution: 'ESTOP',
		},
		{
			id: '22-across',
			number: 22,
			humanNumber: '22',
			clue: 'Small whirlpool (4)',
			direction: 'across',
			length: 4,
			group: ['22-across'],
			position: {
				x: 0,
				y: 12,
			},
			separatorLocations: {},
			solution: 'EDDY',
		},
		{
			id: '23-across',
			number: 23,
			humanNumber: '23',
			clue: 'Insincere praise (8)',
			direction: 'across',
			length: 8,
			group: ['23-across'],
			position: {
				x: 5,
				y: 12,
			},
			separatorLocations: {},
			solution: 'FLATTERY',
		},
		{
			id: '1-down',
			number: 1,
			humanNumber: '1',
			clue: 'Summit (4)',
			direction: 'down',
			length: 4,
			group: ['1-down'],
			position: {
				x: 0,
				y: 0,
			},
			separatorLocations: {},
			solution: 'PEAK',
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2',
			clue: 'Garment for working out (7)',
			direction: 'down',
			length: 7,
			group: ['2-down'],
			position: {
				x: 2,
				y: 0,
			},
			separatorLocations: {},
			solution: 'LEOTARD',
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'Loving (12)',
			direction: 'down',
			length: 12,
			group: ['3-down'],
			position: {
				x: 4,
				y: 0,
			},
			separatorLocations: {},
			solution: 'AFFECTIONATE',
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: 'Relating to a wolf (6)',
			direction: 'down',
			length: 6,
			group: ['4-down'],
			position: {
				x: 6,
				y: 0,
			},
			separatorLocations: {},
			solution: 'LUPINE',
		},
		{
			id: '6-down',
			number: 6,
			humanNumber: '6',
			clue: 'Fruit of the oak (5)',
			direction: 'down',
			length: 5,
			group: ['6-down'],
			position: {
				x: 10,
				y: 0,
			},
			separatorLocations: {},
			solution: 'ACORN',
		},
		{
			id: '7-down',
			number: 7,
			humanNumber: '7',
			clue: 'Lock of hair curving onto the face (4,4)',
			direction: 'down',
			length: 8,
			group: ['7-down'],
			position: {
				x: 12,
				y: 0,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'KISSCURL',
		},
		{
			id: '8-down',
			number: 8,
			humanNumber: '8',
			clue: 'Be deliberately slow to act (4,4,4)',
			direction: 'down',
			length: 12,
			group: ['8-down'],
			position: {
				x: 8,
				y: 1,
			},
			separatorLocations: {
				',': [4, 8],
			},
			solution: 'DRAGONESFEET',
		},
		{
			id: '12-down',
			number: 12,
			humanNumber: '12',
			clue: 'Medical drug derived from opium (8)',
			direction: 'down',
			length: 8,
			group: ['12-down'],
			position: {
				x: 0,
				y: 5,
			},
			separatorLocations: {},
			solution: 'MORPHINE',
		},
		{
			id: '15-down',
			number: 15,
			humanNumber: '15',
			clue: 'Journal, newspaper (7)',
			direction: 'down',
			length: 7,
			group: ['15-down'],
			position: {
				x: 10,
				y: 6,
			},
			separatorLocations: {},
			solution: 'GAZETTE',
		},
		{
			id: '16-down',
			number: 16,
			humanNumber: '16',
			clue: 'Cheat or swindle (6)',
			direction: 'down',
			length: 6,
			group: ['16-down'],
			position: {
				x: 6,
				y: 7,
			},
			separatorLocations: {},
			solution: 'CHISEL',
		},
		{
			id: '18-down',
			number: 18,
			humanNumber: '18',
			clue: 'Speedy (5)',
			direction: 'down',
			length: 5,
			group: ['18-down'],
			position: {
				x: 2,
				y: 8,
			},
			separatorLocations: {},
			solution: 'RAPID',
		},
		{
			id: '19-down',
			number: 19,
			humanNumber: '19',
			clue: 'Sterilize a female animal (4)',
			direction: 'down',
			length: 4,
			group: ['19-down'],
			position: {
				x: 12,
				y: 9,
			},
			separatorLocations: {},
			solution: 'SPAY',
		},
	],
	solutionAvailable: true,
	dateSolutionAvailable: 1729983600000,
	dimensions: {
		cols: 13,
		rows: 13,
	},
	crosswordType: 'speedy',
	pdf: 'https://crosswords-static.guim.co.uk/obs.speedy.20241027.pdf',
};
