/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
	'palette.brand.100': {
		'.': {
			colorSpace: 'srgb',
			components: [0, 0.08235294117647059, 0.21176470588235294],
			alpha: 1,
			hex: '#001536',
		},
	},
	'palette.brand.300': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.01568627450980392, 0.12156862745098039, 0.2901960784313726,
			],
			alpha: 1,
			hex: '#041f4a',
		},
	},
	'palette.brand.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0.0196078431372549, 0.1607843137254902, 0.3843137254901961],
			alpha: 1,
			hex: '#052962',
		},
	},
	'palette.brand.500': {
		'.': {
			colorSpace: 'srgb',
			components: [0, 0.4666666666666667, 0.7137254901960784],
			alpha: 1,
			hex: '#0077b6',
		},
	},
	'palette.brand.600': {
		'.': {
			colorSpace: 'srgb',
			components: [0.3137254901960784, 0.4117647058823529, 0.5686274509803921],
			alpha: 1,
			hex: '#506991',
		},
	},
	'palette.brand.800': {
		'.': {
			colorSpace: 'srgb',
			components: [0.7568627450980392, 0.8470588235294118, 0.9882352941176471],
			alpha: 1,
			hex: '#c1d8fc',
		},
	},
	'palette.brandAlt.200': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9529411764705882, 0.7568627450980392, 0],
			alpha: 1,
			hex: '#f3c100',
		},
	},
	'palette.brandAlt.300': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.8509803921568627, 0],
			alpha: 1,
			hex: '#ffd900',
		},
	},
	'palette.brandAlt.400': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.8980392156862745, 0],
			alpha: 1,
			hex: '#ffe500',
		},
	},
	'palette.neutral.0': {
		'.': {
			colorSpace: 'srgb',
			components: [0, 0, 0],
			alpha: 1,
			hex: '#000000',
		},
	},
	'palette.neutral.7': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.07058823529411765, 0.07058823529411765, 0.07058823529411765,
			],
			alpha: 1,
			hex: '#121212',
		},
	},
	'palette.neutral.10': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.10196078431372549, 0.10196078431372549, 0.10196078431372549,
			],
			alpha: 1,
			hex: '#1a1a1a',
		},
	},
	'palette.neutral.20': {
		'.': {
			colorSpace: 'srgb',
			components: [0.2, 0.2, 0.2],
			alpha: 1,
			hex: '#333333',
		},
	},
	'palette.neutral.38': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.32941176470588235, 0.32941176470588235, 0.32941176470588235,
			],
			alpha: 1,
			hex: '#545454',
		},
	},
	'palette.neutral.46': {
		'.': {
			colorSpace: 'srgb',
			components: [0.4392156862745098, 0.4392156862745098, 0.4392156862745098],
			alpha: 1,
			hex: '#707070',
		},
	},
	'palette.neutral.60': {
		'.': {
			colorSpace: 'srgb',
			components: [0.6, 0.6, 0.6],
			alpha: 1,
			hex: '#999999',
		},
	},
	'palette.neutral.73': {
		'.': {
			colorSpace: 'srgb',
			components: [0.7294117647058823, 0.7294117647058823, 0.7294117647058823],
			alpha: 1,
			hex: '#bababa',
		},
	},
	'palette.neutral.86': {
		'.': {
			colorSpace: 'srgb',
			components: [0.8627450980392157, 0.8627450980392157, 0.8627450980392157],
			alpha: 1,
			hex: '#dcdcdc',
		},
	},
	'palette.neutral.93': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9294117647058824, 0.9294117647058824, 0.9294117647058824],
			alpha: 1,
			hex: '#ededed',
		},
	},
	'palette.neutral.97': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9647058823529412, 0.9647058823529412, 0.9647058823529412],
			alpha: 1,
			hex: '#f6f6f6',
		},
	},
	'palette.neutral.100': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 1, 1],
			alpha: 1,
			hex: '#ffffff',
		},
	},
	'palette.error.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0.7803921568627451, 0, 0],
			alpha: 1,
			hex: '#c70000',
		},
	},
	'palette.error.500': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.5647058823529412, 0.5058823529411764],
			alpha: 1,
			hex: '#ff9081',
		},
	},
	'palette.success.300': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.09411764705882353, 0.3686274509803922, 0.21176470588235294,
			],
			alpha: 1,
			hex: '#185e36',
		},
	},
	'palette.success.400': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.13333333333333333, 0.5294117647058824, 0.30196078431372547,
			],
			alpha: 1,
			hex: '#22874d',
		},
	},
	'palette.success.500': {
		'.': {
			colorSpace: 'srgb',
			components: [0.34509803921568627, 0.8156862745098039, 0.5450980392156862],
			alpha: 1,
			hex: '#58d08b',
		},
	},
	'palette.news.100': {
		'.': {
			colorSpace: 'srgb',
			components: [0.4, 0.0196078431372549, 0.0196078431372549],
			alpha: 1,
			hex: '#660505',
		},
	},
	'palette.news.200': {
		'.': {
			colorSpace: 'srgb',
			components: [0.5450980392156862, 0, 0],
			alpha: 1,
			hex: '#8b0000',
		},
	},
	'palette.news.300': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.6705882352941176, 0.023529411764705882, 0.07450980392156863,
			],
			alpha: 1,
			hex: '#ab0613',
		},
	},
	'palette.news.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0.7803921568627451, 0, 0],
			alpha: 1,
			hex: '#c70000',
		},
	},
	'palette.news.500': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.34901960784313724, 0.2627450980392157],
			alpha: 1,
			hex: '#ff5943',
		},
	},
	'palette.news.550': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.5647058823529412, 0.5058823529411764],
			alpha: 1,
			hex: '#ff9081',
		},
	},
	'palette.news.600': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.7294117647058823, 0.7843137254901961],
			alpha: 1,
			hex: '#ffbac8',
		},
	},
	'palette.news.700': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.8470588235294118, 0.8196078431372549],
			alpha: 1,
			hex: '#ffd8d1',
		},
	},
	'palette.news.800': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.9568627450980393, 0.9490196078431372],
			alpha: 1,
			hex: '#fff4f2',
		},
	},
	'palette.opinion.100': {
		'.': {
			colorSpace: 'srgb',
			components: [0.403921568627451, 0.12549019607843137, 0.0196078431372549],
			alpha: 1,
			hex: '#672005',
		},
	},
	'palette.opinion.200': {
		'.': {
			colorSpace: 'srgb',
			components: [0.5529411764705883, 0.15294117647058825, 0],
			alpha: 1,
			hex: '#8d2700',
		},
	},
	'palette.opinion.300': {
		'.': {
			colorSpace: 'srgb',
			components: [0.7803921568627451, 0.27450980392156865, 0],
			alpha: 1,
			hex: '#c74600',
		},
	},
	'palette.opinion.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0.7803921568627451, 0.27450980392156865, 0],
			alpha: 1,
			hex: '#c74600',
		},
	},
	'palette.opinion.450': {
		'.': {
			colorSpace: 'srgb',
			components: [0.8784313725490196, 0.3686274509803922, 0],
			alpha: 1,
			hex: '#e05e00',
		},
	},
	'palette.opinion.500': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.4980392156862745, 0.058823529411764705],
			alpha: 1,
			hex: '#ff7f0f',
		},
	},
	'palette.opinion.550': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.6, 0.2549019607843137],
			alpha: 1,
			hex: '#ff9941',
		},
	},
	'palette.opinion.600': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9764705882352941, 0.7019607843137254, 0.4627450980392157],
			alpha: 1,
			hex: '#f9b376',
		},
	},
	'palette.opinion.700': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.9058823529411765, 0.8313725490196079],
			alpha: 1,
			hex: '#ffe7d4',
		},
	},
	'palette.opinion.800': {
		'.': {
			colorSpace: 'srgb',
			components: [0.996078431372549, 0.9764705882352941, 0.9607843137254902],
			alpha: 1,
			hex: '#fef9f5',
		},
	},
	'palette.sport.100': {
		'.': {
			colorSpace: 'srgb',
			components: [0, 0.23529411764705882, 0.3764705882352941],
			alpha: 1,
			hex: '#003c60',
		},
	},
	'palette.sport.200': {
		'.': {
			colorSpace: 'srgb',
			components: [0, 0.3058823529411765, 0.48627450980392156],
			alpha: 1,
			hex: '#004e7c',
		},
	},
	'palette.sport.300': {
		'.': {
			colorSpace: 'srgb',
			components: [0, 0.33725490196078434, 0.5372549019607843],
			alpha: 1,
			hex: '#005689',
		},
	},
	'palette.sport.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0, 0.4666666666666667, 0.7137254901960784],
			alpha: 1,
			hex: '#0077b6',
		},
	},
	'palette.sport.500': {
		'.': {
			colorSpace: 'srgb',
			components: [0, 0.6980392156862745, 1],
			alpha: 1,
			hex: '#00b2ff',
		},
	},
	'palette.sport.600': {
		'.': {
			colorSpace: 'srgb',
			components: [0.5647058823529412, 0.8627450980392157, 1],
			alpha: 1,
			hex: '#90dcff',
		},
	},
	'palette.sport.700': {
		'.': {
			colorSpace: 'srgb',
			components: [0.8470588235294118, 0.9450980392156862, 1],
			alpha: 1,
			hex: '#d8f1ff',
		},
	},
	'palette.sport.800': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9450980392156862, 0.9725490196078431, 0.9882352941176471],
			alpha: 1,
			hex: '#f1f8fc',
		},
	},
	'palette.culture.50': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.16862745098039217, 0.14901960784313725, 0.1450980392156863,
			],
			alpha: 1,
			hex: '#2b2625',
		},
	},
	'palette.culture.100': {
		'.': {
			colorSpace: 'srgb',
			components: [0.24313725490196078, 0.2, 0.13725490196078433],
			alpha: 1,
			hex: '#3e3323',
		},
	},
	'palette.culture.200': {
		'.': {
			colorSpace: 'srgb',
			components: [0.3411764705882353, 0.2823529411764706, 0.20784313725490197],
			alpha: 1,
			hex: '#574835',
		},
	},
	'palette.culture.300': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.4196078431372549, 0.34509803921568627, 0.25098039215686274,
			],
			alpha: 1,
			hex: '#6b5840',
		},
	},
	'palette.culture.350': {
		'.': {
			colorSpace: 'srgb',
			components: [0.5254901960784314, 0.42745098039215684, 0.3137254901960784],
			alpha: 1,
			hex: '#866d50',
		},
	},
	'palette.culture.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0.5254901960784314, 0.42745098039215684, 0.3137254901960784],
			alpha: 1,
			hex: '#866d50',
		},
	},
	'palette.culture.450': {
		'.': {
			colorSpace: 'srgb',
			components: [0.6313725490196078, 0.5176470588235295, 0.3607843137254902],
			alpha: 1,
			hex: '#a1845c',
		},
	},
	'palette.culture.500': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9176470588235294, 0.8, 0.6274509803921569],
			alpha: 1,
			hex: '#eacca0',
		},
	},
	'palette.culture.600': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9058823529411765, 0.8313725490196079, 0.7254901960784313],
			alpha: 1,
			hex: '#e7d4b9',
		},
	},
	'palette.culture.700': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9372549019607843, 0.9098039215686274, 0.8666666666666667],
			alpha: 1,
			hex: '#efe8dd',
		},
	},
	'palette.culture.800': {
		'.': {
			colorSpace: 'srgb',
			components: [0.984313725490196, 0.9647058823529412, 0.9372549019607843],
			alpha: 1,
			hex: '#fbf6ef',
		},
	},
	'palette.lifestyle.100': {
		'.': {
			colorSpace: 'srgb',
			components: [0.3176470588235294, 0, 0.2627450980392157],
			alpha: 1,
			hex: '#510043',
		},
	},
	'palette.lifestyle.200': {
		'.': {
			colorSpace: 'srgb',
			components: [0.396078431372549, 0, 0.32941176470588235],
			alpha: 1,
			hex: '#650054',
		},
	},
	'palette.lifestyle.300': {
		'.': {
			colorSpace: 'srgb',
			components: [0.49019607843137253, 0, 0.40784313725490196],
			alpha: 1,
			hex: '#7d0068',
		},
	},
	'palette.lifestyle.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0.7333333333333333, 0.23137254901960785, 0.5019607843137255],
			alpha: 1,
			hex: '#bb3b80',
		},
	},
	'palette.lifestyle.450': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9529411764705882, 0.47843137254901963, 0.7372549019607844],
			alpha: 1,
			hex: '#f37abc',
		},
	},
	'palette.lifestyle.500': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.6705882352941176, 0.8588235294117647],
			alpha: 1,
			hex: '#ffabdb',
		},
	},
	'palette.lifestyle.600': {
		'.': {
			colorSpace: 'srgb',
			components: [0.996078431372549, 0.7843137254901961, 0.8274509803921568],
			alpha: 1,
			hex: '#fec8d3',
		},
	},
	'palette.lifestyle.800': {
		'.': {
			colorSpace: 'srgb',
			components: [0.996078431372549, 0.9450980392156862, 0.9725490196078431],
			alpha: 1,
			hex: '#fef1f8',
		},
	},
	'palette.labs.100': {
		'.': {
			colorSpace: 'srgb',
			components: [0.03529411764705882, 0.3803921568627451, 0.3568627450980392],
			alpha: 1,
			hex: '#09615b',
		},
	},
	'palette.labs.200': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.047058823529411764, 0.47843137254901963, 0.45098039215686275,
			],
			alpha: 1,
			hex: '#0c7a73',
		},
	},
	'palette.labs.300': {
		'.': {
			colorSpace: 'srgb',
			components: [0.396078431372549, 0.6588235294117647, 0.592156862745098],
			alpha: 1,
			hex: '#65a897',
		},
	},
	'palette.labs.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0.4117647058823529, 0.8196078431372549, 0.792156862745098],
			alpha: 1,
			hex: '#69d1ca',
		},
	},
	'palette.labs.500': {
		'.': {
			colorSpace: 'srgb',
			components: [0.6588235294117647, 0.8901960784313725, 0.8745098039215686],
			alpha: 1,
			hex: '#a8e3df',
		},
	},
	'palette.labs.600': {
		'.': {
			colorSpace: 'srgb',
			components: [0.8627450980392157, 0.9568627450980393, 0.9529411764705882],
			alpha: 1,
			hex: '#dcf4f3',
		},
	},
	'palette.labs.700': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9529411764705882, 0.984313725490196, 0.984313725490196],
			alpha: 1,
			hex: '#f3fbfb',
		},
	},
	'palette.specialReport.100': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.13333333333333333, 0.1450980392156863, 0.15294117647058825,
			],
			alpha: 1,
			hex: '#222527',
		},
	},
	'palette.specialReport.200': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.18823529411764706, 0.20784313725490197, 0.2196078431372549,
			],
			alpha: 1,
			hex: '#303538',
		},
	},
	'palette.specialReport.300': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.24705882352941178, 0.27450980392156865, 0.2901960784313726,
			],
			alpha: 1,
			hex: '#3f464a',
		},
	},
	'palette.specialReport.400': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.34901960784313724, 0.3607843137254902, 0.37254901960784315,
			],
			alpha: 1,
			hex: '#595c5f',
		},
	},
	'palette.specialReport.450': {
		'.': {
			colorSpace: 'srgb',
			components: [0.615686274509804, 0.6274509803921569, 0.6352941176470588],
			alpha: 1,
			hex: '#9da0a2',
		},
	},
	'palette.specialReport.500': {
		'.': {
			colorSpace: 'srgb',
			components: [0.6705882352941176, 0.7607843137254902, 0.788235294117647],
			alpha: 1,
			hex: '#abc2c9',
		},
	},
	'palette.specialReport.700': {
		'.': {
			colorSpace: 'srgb',
			components: [0.8941176470588236, 0.8980392156862745, 0.9098039215686274],
			alpha: 1,
			hex: '#e4e5e8',
		},
	},
	'palette.specialReport.800': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9372549019607843, 0.9450980392156862, 0.9490196078431372],
			alpha: 1,
			hex: '#eff1f2',
		},
	},
	'palette.specialReportAlt.100': {
		'.': {
			colorSpace: 'srgb',
			components: [
				0.16862745098039217, 0.16862745098039217, 0.16470588235294117,
			],
			alpha: 1,
			hex: '#2b2b2a',
		},
	},
	'palette.specialReportAlt.200': {
		'.': {
			colorSpace: 'srgb',
			components: [0.7254901960784313, 0.18823529411764706, 0.0392156862745098],
			alpha: 1,
			hex: '#b9300a',
		},
	},
	'palette.specialReportAlt.300': {
		'.': {
			colorSpace: 'srgb',
			components: [1, 0.4, 0.23921568627450981],
			alpha: 1,
			hex: '#ff663d',
		},
	},
	'palette.specialReportAlt.700': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9215686274509803, 0.9019607843137255, 0.8823529411764706],
			alpha: 1,
			hex: '#ebe6e1',
		},
	},
	'palette.specialReportAlt.800': {
		'.': {
			colorSpace: 'srgb',
			components: [0.9607843137254902, 0.9411764705882353, 0.9215686274509803],
			alpha: 1,
			hex: '#f5f0eb',
		},
	},
	'palette.focus.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0, 0.4666666666666667, 0.7137254901960784],
			alpha: 1,
			hex: '#0077b6',
		},
	},
	'palette.notificationBlue.400': {
		'.': {
			colorSpace: 'srgb',
			components: [0.00392156862745098, 0.5647058823529412, 0.9686274509803922],
			alpha: 1,
			hex: '#0190f7',
		},
	},
	'size.xsmall': {
		'.': {
			value: 24,
			unit: 'px',
		},
	},
	'size.small': {
		'.': {
			value: 36,
			unit: 'px',
		},
	},
	'size.medium': {
		'.': {
			value: 44,
			unit: 'px',
		},
	},
	'iconSize.xsmall': {
		'.': {
			value: 20,
			unit: 'px',
		},
	},
	'iconSize.small': {
		'.': {
			value: 26,
			unit: 'px',
		},
	},
	'iconSize.medium': {
		'.': {
			value: 30,
			unit: 'px',
		},
	},
	'height.ctaMedium': {
		'.': {
			value: 44,
			unit: 'px',
		},
	},
	'height.ctaSmall': {
		'.': {
			value: 36,
			unit: 'px',
		},
	},
	'height.ctaXsmall': {
		'.': {
			value: 24,
			unit: 'px',
		},
	},
	'height.inputMedium': {
		'.': {
			value: 44,
			unit: 'px',
		},
	},
	'height.inputXsmall': {
		'.': {
			value: 24,
			unit: 'px',
		},
	},
	'height.iconMedium': {
		'.': {
			value: 30,
			unit: 'px',
		},
	},
	'height.iconSmall': {
		'.': {
			value: 26,
			unit: 'px',
		},
	},
	'height.iconXsmall': {
		'.': {
			value: 20,
			unit: 'px',
		},
	},
	'width.ctaMedium': {
		'.': {
			value: 44,
			unit: 'px',
		},
	},
	'width.ctaSmall': {
		'.': {
			value: 36,
			unit: 'px',
		},
	},
	'width.ctaXsmall': {
		'.': {
			value: 24,
			unit: 'px',
		},
	},
	'width.inputXsmall': {
		'.': {
			value: 24,
			unit: 'px',
		},
	},
	'width.iconMedium': {
		'.': {
			value: 30,
			unit: 'px',
		},
	},
	'width.iconSmall': {
		'.': {
			value: 26,
			unit: 'px',
		},
	},
	'width.iconXsmall': {
		'.': {
			value: 20,
			unit: 'px',
		},
	},
	'space.0': {
		'.': {
			value: 2,
			unit: 'px',
		},
	},
	'space.1': {
		'.': {
			value: 4,
			unit: 'px',
		},
	},
	'space.2': {
		'.': {
			value: 8,
			unit: 'px',
		},
	},
	'space.3': {
		'.': {
			value: 12,
			unit: 'px',
		},
	},
	'space.4': {
		'.': {
			value: 16,
			unit: 'px',
		},
	},
	'space.5': {
		'.': {
			value: 20,
			unit: 'px',
		},
	},
	'space.6': {
		'.': {
			value: 24,
			unit: 'px',
		},
	},
	'space.8': {
		'.': {
			value: 32,
			unit: 'px',
		},
	},
	'space.9': {
		'.': {
			value: 36,
			unit: 'px',
		},
	},
	'space.10': {
		'.': {
			value: 40,
			unit: 'px',
		},
	},
	'space.12': {
		'.': {
			value: 48,
			unit: 'px',
		},
	},
	'space.14': {
		'.': {
			value: 56,
			unit: 'px',
		},
	},
	'space.16': {
		'.': {
			value: 64,
			unit: 'px',
		},
	},
	'space.18': {
		'.': {
			value: 72,
			unit: 'px',
		},
	},
	'space.24': {
		'.': {
			value: 96,
			unit: 'px',
		},
	},
	'breakpoint.mobile': {
		'.': {
			value: 320,
			unit: 'px',
		},
	},
	'breakpoint.mobileMedium': {
		'.': {
			value: 375,
			unit: 'px',
		},
	},
	'breakpoint.mobileLandscape': {
		'.': {
			value: 480,
			unit: 'px',
		},
	},
	'breakpoint.phablet': {
		'.': {
			value: 660,
			unit: 'px',
		},
	},
	'breakpoint.tablet': {
		'.': {
			value: 740,
			unit: 'px',
		},
	},
	'breakpoint.desktop': {
		'.': {
			value: 980,
			unit: 'px',
		},
	},
	'breakpoint.leftCol': {
		'.': {
			value: 1140,
			unit: 'px',
		},
	},
	'breakpoint.wide': {
		'.': {
			value: 1300,
			unit: 'px',
		},
	},
	'typography.fontFamily.titlepiece': {
		'.': ['GT Guardian Titlepiece', 'Georgia', 'serif'],
	},
	'typography.fontFamily.headline': {
		'.': ['GH Guardian Headline', 'Guardian Egyptian Web', 'Georgia', 'serif'],
	},
	'typography.fontFamily.body': {
		'.': [
			'GuardianTextEgyptian',
			'Guardian Text Egyptian Web',
			'Georgia',
			'serif',
		],
	},
	'typography.fontFamily.textSans': {
		'.': [
			'GuardianTextSans',
			'Guardian Text Sans Web',
			'Helvetica Neue',
			'Helvetica',
			'Arial',
			'Lucida Grande',
			'sans-serif',
		],
	},
	'typography.fontSize.12': {
		'.': {
			value: 12,
			unit: 'px',
		},
	},
	'typography.fontSize.14': {
		'.': {
			value: 14,
			unit: 'px',
		},
	},
	'typography.fontSize.15': {
		'.': {
			value: 15,
			unit: 'px',
		},
	},
	'typography.fontSize.17': {
		'.': {
			value: 17,
			unit: 'px',
		},
	},
	'typography.fontSize.20': {
		'.': {
			value: 20,
			unit: 'px',
		},
	},
	'typography.fontSize.24': {
		'.': {
			value: 24,
			unit: 'px',
		},
	},
	'typography.fontSize.28': {
		'.': {
			value: 28,
			unit: 'px',
		},
	},
	'typography.fontSize.34': {
		'.': {
			value: 34,
			unit: 'px',
		},
	},
	'typography.fontSize.42': {
		'.': {
			value: 42,
			unit: 'px',
		},
	},
	'typography.fontSize.50': {
		'.': {
			value: 50,
			unit: 'px',
		},
	},
	'typography.fontSize.64': {
		'.': {
			value: 64,
			unit: 'px',
		},
	},
	'typography.fontSize.70': {
		'.': {
			value: 70,
			unit: 'px',
		},
	},
	'typography.lineHeight.tight': {
		'.': 1.15,
	},
	'typography.lineHeight.regular': {
		'.': 1.3,
	},
	'typography.lineHeight.loose': {
		'.': 1.4,
	},
	'typography.fontWeight.light': {
		'.': 300,
	},
	'typography.fontWeight.regular': {
		'.': 400,
	},
	'typography.fontWeight.medium': {
		'.': 500,
	},
	'typography.fontWeight.bold': {
		'.': 700,
	},
	'typography.textDecorationThicknessForFontSize.12': {
		'.': {
			value: 2,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.14': {
		'.': {
			value: 2,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.15': {
		'.': {
			value: 2,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.17': {
		'.': {
			value: 2,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.20': {
		'.': {
			value: 3,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.24': {
		'.': {
			value: 3,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.28': {
		'.': {
			value: 3,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.34': {
		'.': {
			value: 4,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.42': {
		'.': {
			value: 5,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.50': {
		'.': {
			value: 6,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.64': {
		'.': {
			value: 6,
			unit: 'px',
		},
	},
	'typography.textDecorationThicknessForFontSize.70': {
		'.': {
			value: 6,
			unit: 'px',
		},
	},
};

/** Get individual token */
export function token(tokenID, modeName = '.') {
	return tokens[tokenID]?.[modeName];
}
