/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

import type {
	ColorTokenNormalized,
	DimensionTokenNormalized,
	FontFamilyTokenNormalized,
	NumberTokenNormalized,
} from '@terrazzo/parser';

export declare const tokens: {
	'palette.brand.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.brand.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.brand.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.brand.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.brand.600': Record<'.', ColorTokenNormalized['$value']>;
	'palette.brand.800': Record<'.', ColorTokenNormalized['$value']>;
	'palette.brandAlt.200': Record<'.', ColorTokenNormalized['$value']>;
	'palette.brandAlt.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.brandAlt.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.0': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.7': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.10': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.20': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.38': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.46': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.60': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.73': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.86': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.93': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.97': Record<'.', ColorTokenNormalized['$value']>;
	'palette.neutral.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.error.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.error.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.success.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.success.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.success.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.news.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.news.200': Record<'.', ColorTokenNormalized['$value']>;
	'palette.news.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.news.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.news.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.news.550': Record<'.', ColorTokenNormalized['$value']>;
	'palette.news.600': Record<'.', ColorTokenNormalized['$value']>;
	'palette.news.700': Record<'.', ColorTokenNormalized['$value']>;
	'palette.news.800': Record<'.', ColorTokenNormalized['$value']>;
	'palette.opinion.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.opinion.200': Record<'.', ColorTokenNormalized['$value']>;
	/** @deprecated Use palette.opinion.400 */
	'palette.opinion.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.opinion.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.opinion.450': Record<'.', ColorTokenNormalized['$value']>;
	'palette.opinion.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.opinion.550': Record<'.', ColorTokenNormalized['$value']>;
	'palette.opinion.600': Record<'.', ColorTokenNormalized['$value']>;
	'palette.opinion.700': Record<'.', ColorTokenNormalized['$value']>;
	'palette.opinion.800': Record<'.', ColorTokenNormalized['$value']>;
	'palette.sport.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.sport.200': Record<'.', ColorTokenNormalized['$value']>;
	'palette.sport.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.sport.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.sport.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.sport.600': Record<'.', ColorTokenNormalized['$value']>;
	'palette.sport.700': Record<'.', ColorTokenNormalized['$value']>;
	'palette.sport.800': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.50': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.200': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.300': Record<'.', ColorTokenNormalized['$value']>;
	/** @deprecated Use palette.culture.400 */
	'palette.culture.350': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.450': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.600': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.700': Record<'.', ColorTokenNormalized['$value']>;
	'palette.culture.800': Record<'.', ColorTokenNormalized['$value']>;
	'palette.lifestyle.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.lifestyle.200': Record<'.', ColorTokenNormalized['$value']>;
	'palette.lifestyle.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.lifestyle.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.lifestyle.450': Record<'.', ColorTokenNormalized['$value']>;
	'palette.lifestyle.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.lifestyle.600': Record<'.', ColorTokenNormalized['$value']>;
	'palette.lifestyle.800': Record<'.', ColorTokenNormalized['$value']>;
	'palette.labs.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.labs.200': Record<'.', ColorTokenNormalized['$value']>;
	'palette.labs.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.labs.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.labs.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.labs.600': Record<'.', ColorTokenNormalized['$value']>;
	'palette.labs.700': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReport.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReport.200': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReport.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReport.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReport.450': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReport.500': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReport.700': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReport.800': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReportAlt.100': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReportAlt.200': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReportAlt.300': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReportAlt.700': Record<'.', ColorTokenNormalized['$value']>;
	'palette.specialReportAlt.800': Record<'.', ColorTokenNormalized['$value']>;
	'palette.focus.400': Record<'.', ColorTokenNormalized['$value']>;
	'palette.notificationBlue.400': Record<'.', ColorTokenNormalized['$value']>;
	'size.xsmall': Record<'.', DimensionTokenNormalized['$value']>;
	'size.small': Record<'.', DimensionTokenNormalized['$value']>;
	/** Meets WCAG 2.1 AAA compliance for touch targets. */
	'size.medium': Record<'.', DimensionTokenNormalized['$value']>;
	'iconSize.xsmall': Record<'.', DimensionTokenNormalized['$value']>;
	'iconSize.small': Record<'.', DimensionTokenNormalized['$value']>;
	'iconSize.medium': Record<'.', DimensionTokenNormalized['$value']>;
	/** Call to action buttons and links */
	'height.ctaMedium': Record<'.', DimensionTokenNormalized['$value']>;
	/** Secondary calls to action */
	'height.ctaSmall': Record<'.', DimensionTokenNormalized['$value']>;
	/** Calls to action where there is very limited space */
	'height.ctaXsmall': Record<'.', DimensionTokenNormalized['$value']>;
	/** Text input fields, radio and checkbox labels */
	'height.inputMedium': Record<'.', DimensionTokenNormalized['$value']>;
	/** Checkables such as checkboxes or radio buttons */
	'height.inputXsmall': Record<'.', DimensionTokenNormalized['$value']>;
	'height.iconMedium': Record<'.', DimensionTokenNormalized['$value']>;
	'height.iconSmall': Record<'.', DimensionTokenNormalized['$value']>;
	'height.iconXsmall': Record<'.', DimensionTokenNormalized['$value']>;
	/** Medium height call to action buttons and links */
	'width.ctaMedium': Record<'.', DimensionTokenNormalized['$value']>;
	/** Small height call to action buttons and links */
	'width.ctaSmall': Record<'.', DimensionTokenNormalized['$value']>;
	/** Extra small height call to action buttons and links */
	'width.ctaXsmall': Record<'.', DimensionTokenNormalized['$value']>;
	'width.inputXsmall': Record<'.', DimensionTokenNormalized['$value']>;
	'width.iconMedium': Record<'.', DimensionTokenNormalized['$value']>;
	'width.iconSmall': Record<'.', DimensionTokenNormalized['$value']>;
	/** Checkables such as checkboxes or radio buttons */
	'width.iconXsmall': Record<'.', DimensionTokenNormalized['$value']>;
	'space.0': Record<'.', DimensionTokenNormalized['$value']>;
	'space.1': Record<'.', DimensionTokenNormalized['$value']>;
	'space.2': Record<'.', DimensionTokenNormalized['$value']>;
	'space.3': Record<'.', DimensionTokenNormalized['$value']>;
	'space.4': Record<'.', DimensionTokenNormalized['$value']>;
	'space.5': Record<'.', DimensionTokenNormalized['$value']>;
	'space.6': Record<'.', DimensionTokenNormalized['$value']>;
	'space.8': Record<'.', DimensionTokenNormalized['$value']>;
	'space.9': Record<'.', DimensionTokenNormalized['$value']>;
	'space.10': Record<'.', DimensionTokenNormalized['$value']>;
	'space.12': Record<'.', DimensionTokenNormalized['$value']>;
	'space.14': Record<'.', DimensionTokenNormalized['$value']>;
	'space.16': Record<'.', DimensionTokenNormalized['$value']>;
	'space.18': Record<'.', DimensionTokenNormalized['$value']>;
	'space.24': Record<'.', DimensionTokenNormalized['$value']>;
	'breakpoint.mobile': Record<'.', DimensionTokenNormalized['$value']>;
	'breakpoint.mobileMedium': Record<'.', DimensionTokenNormalized['$value']>;
	'breakpoint.mobileLandscape': Record<'.', DimensionTokenNormalized['$value']>;
	'breakpoint.phablet': Record<'.', DimensionTokenNormalized['$value']>;
	'breakpoint.tablet': Record<'.', DimensionTokenNormalized['$value']>;
	'breakpoint.desktop': Record<'.', DimensionTokenNormalized['$value']>;
	'breakpoint.leftCol': Record<'.', DimensionTokenNormalized['$value']>;
	'breakpoint.wide': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontFamily.titlepiece': Record<
		'.',
		FontFamilyTokenNormalized['$value']
	>;
	'typography.fontFamily.headline': Record<
		'.',
		FontFamilyTokenNormalized['$value']
	>;
	'typography.fontFamily.body': Record<
		'.',
		FontFamilyTokenNormalized['$value']
	>;
	'typography.fontFamily.textSans': Record<
		'.',
		FontFamilyTokenNormalized['$value']
	>;
	'typography.fontSize.12': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.14': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.15': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.17': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.20': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.24': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.28': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.34': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.42': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.50': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.64': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.fontSize.70': Record<'.', DimensionTokenNormalized['$value']>;
	'typography.lineHeight.tight': Record<'.', NumberTokenNormalized['$value']>;
	'typography.lineHeight.regular': Record<'.', NumberTokenNormalized['$value']>;
	'typography.lineHeight.loose': Record<'.', NumberTokenNormalized['$value']>;
	'typography.fontWeight.light': Record<'.', NumberTokenNormalized['$value']>;
	'typography.fontWeight.regular': Record<'.', NumberTokenNormalized['$value']>;
	'typography.fontWeight.medium': Record<'.', NumberTokenNormalized['$value']>;
	'typography.fontWeight.bold': Record<'.', NumberTokenNormalized['$value']>;
	'typography.textDecorationThicknessForFontSize.12': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.14': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.15': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.17': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.20': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.24': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.28': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.34': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.42': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.50': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.64': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
	'typography.textDecorationThicknessForFontSize.70': Record<
		'.',
		DimensionTokenNormalized['$value']
	>;
};

export declare function token<K extends keyof typeof tokens>(
	tokenID: K,
	modeName?: never,
): (typeof tokens)[K]['.'];
export declare function token<
	K extends keyof typeof tokens,
	M extends keyof (typeof tokens)[K],
>(tokenID: K, modeName: M): (typeof tokens)[K][M];
