/* eslint-disable import/no-default-export -- cobalt plugins do this */

// @ts-check

import { defaultTransformer, serializeJS } from '@cobalt-ui/plugin-js';
import { set } from '@cobalt-ui/utils';

/**
 * @param {{ filename: string; }} options
 * @returns {import('@cobalt-ui/core').Plugin}
 */
export default function pluginBreakpoints(options) {
	return {
		name: 'plugin-breakpoints',

		config(/* config */) {},
		async build({ tokens /* metadata, rawSchema */ }) {
			const header = `/**
* Autogenerated from design-tokens/tokens.json.
* DO NOT EDIT!
*/

`;
			// this is where we'll store the transformed tokens
			/** @type {Object.<string, string>} */
			const transformedTokens = {};

			/** @type {Object.<string, string>} */
			const jsDoc = {};

			// we can re-use the default transformer from `@cobalt-ui/plugin-js`
			for (const token of tokens) {
				set(transformedTokens, token.id, defaultTransformer(token));
				if (token.$description) {
					jsDoc[token.id] = token.$description;
				}
			}

			let typescriptSource = '';

			Object.keys(transformedTokens).forEach((tokenGroup) => {
				const serialisedJS = serializeJS(transformedTokens[tokenGroup], {
					comments: jsDoc,
				}).trim();

				// create a typescript source string containing the transformed tokens
				typescriptSource += `export const ${tokenGroup} = ${serialisedJS.replace(/;$/, '')} as const;`;
			});

			return [
				{
					filename: options.filename,
					contents: header,
				},
			];
		},
	};
}
