---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template for the deploy-storybook.yml workflow action.

Resources:
  AllStorybooks:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com-gu-all-storybooks
      WebsiteConfiguration:
        IndexDocument: index.html
  AllStorybookCloudfront: # sadly required for HTTPs :(
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        - CustomOriginConfig:
          OriginProtocolPolicy: http-only
          DomainName: !GetAtt AllStorybooks.DomainName
  StorybookSourceFoundations:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com-gu-storybook-source-foundations
      WebsiteConfiguration:
        IndexDocument: index.html
  StorybookSourceReactComponents:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com-gu-storybook-source-react-components
      WebsiteConfiguration:
        IndexDocument: index.html
  StorybookSourceReactComponentsDevelopmentKitchen:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com-gu-storybook-source-react-components-development-kitchen
      WebsiteConfiguration:
        IndexDocument: index.html
