import { basename, extname, join } from 'node:path';

/**
 * @param {string} plugin
 * @param {string} contents
 */
export const template = (plugin, contents) =>
	`/**
* DO NOT EDIT THIS FILE DIRECTLY!
*
* It was auto-generated by ${join('design-tokens', 'plugins', basename(plugin))}.
*
* Update design-tokens/tokens.json and (re)build @guardian/source instead.
*/

${contents}
`;
