/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * It was auto-generated by design-tokens/plugins/breakpoints.js.
 *
 * Update design-tokens/tokens.json and (re)build @guardian/source instead.
 */

export const breakpoint = {
	desktop: 980,
	leftCol: 1140,
	mobile: 320,
	mobileLandscape: 480,
	mobileMedium: 375,
	phablet: 660,
	tablet: 740,
	wide: 1300,
} as const;

export type Breakpoint = keyof typeof breakpoint;
