/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * It was auto-generated by design-tokens/plugins/size.js.
 *
 * Update design-tokens/tokens.json and (re)build @guardian/source instead.
 */

export const height = {
	ctaMedium: 44,
	ctaSmall: 36,
	ctaXsmall: 24,
	iconMedium: 30,
	iconSmall: 26,
	iconXsmall: 20,
	inputMedium: 44,
	inputXsmall: 24,
} as const;
export const iconSize = {
	/** Meets WCAG 2.1 AAA compliance for touch targets. */
	medium: 30,
	small: 26,
	xsmall: 20,
} as const;
export const size = {
	/** Meets WCAG 2.1 AAA compliance for touch targets. */
	medium: 44,
	small: 36,
	xsmall: 24,
} as const;
export const width = {
	ctaMedium: 44,
	ctaSmall: 36,
	ctaXsmall: 24,
	iconMedium: 30,
	iconSmall: 26,
	iconXsmall: 20,
	inputXsmall: 24,
} as const;
export const remHeight = {
	ctaMedium: '2.75rem',
	ctaSmall: '2.25rem',
	ctaXsmall: '1.5rem',
	iconMedium: '1.875rem',
	iconSmall: '1.625rem',
	iconXsmall: '1.25rem',
	inputMedium: '2.75rem',
	inputXsmall: '1.5rem',
} as const;
export const remIconSize = {
	/** Meets WCAG 2.1 AAA compliance for touch targets. */
	medium: '1.875rem',
	small: '1.625rem',
	xsmall: '1.25rem',
} as const;
export const remSize = {
	/** Meets WCAG 2.1 AAA compliance for touch targets. */
	medium: '2.75rem',
	small: '2.25rem',
	xsmall: '1.5rem',
} as const;
export const remWidth = {
	ctaMedium: '2.75rem',
	ctaSmall: '2.25rem',
	ctaXsmall: '1.5rem',
	iconMedium: '1.875rem',
	iconSmall: '1.625rem',
	iconXsmall: '1.25rem',
	inputXsmall: '1.5rem',
} as const;
