name: 'Setup Environment'
description: 'Sets up Node.js environment and installs dependencies'

runs:
  using: 'composite'
  steps:
    # Temporary fix to version with updated npm registry keys. Remove once fixed.
    # See -> https://github.com/actions/setup-node/issues/1222
    - run: npm install --global corepack@0.31.0
      shell: bash
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    # Trusted publishing requires npm CLI v11.5.1 or later:
    - run: npm install -g npm@11.6.1
      shell: bash

    # Set up GitHub Actions caching for Wireit.
    - uses: google/wireit@setup-github-actions-caching/v2

    - run: pnpm install --frozen-lockfile
      shell: bash
