name: 'Setup Environment'
description: 'Sets up Node.js environment and installs dependencies'

runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    # Set up GitHub Actions caching for Wireit.
    # disable cross-run caching for now
    # - uses: google/wireit@setup-github-actions-caching/v1

    - run: pnpm install --frozen-lockfile
      shell: bash
