name: 'Setup Environment'
description: 'Sets up Node.js environment and installs dependencies'

runs:
  using: 'composite'
  steps:
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    # Set up GitHub Actions caching for Wireit.
    - uses: google/wireit@setup-github-actions-caching/v1

    - run: pnpm install --frozen-lockfile
      shell: bash

    # if cypress tests fail _and_ you have an update to the lockfile, you may
    # need to do a single run with this uncommented...
    # don't forget to check the version.
    # i hate cypress.
    - run: pnpm dlx cypress@13.7.1 install --force
      shell: bash

    # Restores cypress binary cache. If the binary is missing, it will be
    # downloaded and cached for next time.
    # https://docs.cypress.io/guides/continuous-integration/introduction#Caching
    - name: Cache Cypress binary
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}
