// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12.506 2Q14.248 9.752 22 11.493v1.013Q14.248 14.248 12.506 22h-1.012Q9.752 14.248 2 12.506v-1.013Q9.752 9.751 11.494 2z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgAiIndicator = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				AI indicator
			</span>
		) : (
			''
		)}
	</>
);
