// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M17 4.502V19.5l-.875.875H4.375L3.5 19.5V4.502l.875-.875h11.75zM5.125 18.75h10.25v-7.625H5.125zm14.25-12.623V17.74l-.748.75-.877.01v-13h1.012zm1.637 1.365.613.627v7.7l-.748.75-.877.01V7.491zM12.25 16.5H6.125v-1.625h6.125zm1.625-2.625h-7.75V12.25h7.75zM5.125 9.5h10.25V5.252H5.125z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgAllRecipes = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				All recipes
			</span>
		) : (
			''
		)}
	</>
);
