// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="m6.549 7.245-.002-.002 2.471-1.878a1.557 1.557 0 0 0-2.174-.295 1.55 1.55 0 0 0-.297 2.173l-.003.002z"
			fill={theme?.fill}
		/>
		<path d="m17.441 7.245.002-.002.003.002z" fill={theme?.fill} />
		<path
			d="m17.443 7.243-2.471-1.878a1.557 1.557 0 0 1 2.174-.295c.68.514.815 1.488.297 2.173"
			fill={theme?.fill}
		/>
		<path
			d="M21.186 16.985a7.8 7.8 0 0 0 1.654-4.815c0-1.815-.62-3.485-1.654-4.815l.364-.365A6.69 6.69 0 0 1 24 12.17c0 2.09-.955 3.95-2.45 5.18z"
			fill={theme?.fill}
		/>
		<path
			d="M20.466 12.18c0 1.18-.36 2.28-.97 3.19l.49.49a5.2 5.2 0 0 0 1.524-3.68c0-1.44-.58-2.735-1.524-3.68l-.49.49c.615.91.97 2.01.97 3.19"
			fill={theme?.fill}
		/>
		<path
			d="M2.764 16.905a7.68 7.68 0 0 1-1.63-4.73 7.7 7.7 0 0 1 1.63-4.73l-.36-.36A6.57 6.57 0 0 0 0 12.175c0 2.05.935 3.88 2.405 5.09z"
			fill={theme?.fill}
		/>
		<path
			d="M3.53 12.18c0 1.18.36 2.28.97 3.19l-.49.49a5.2 5.2 0 0 1-1.526-3.68c0-1.435.58-2.735 1.525-3.68l.49.49a5.7 5.7 0 0 0-.97 3.19"
			fill={theme?.fill}
		/>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M12.008 5.525a6.483 6.483 0 0 0-5.01 10.602L5.755 17.8l.455.455 1.668-1.247a6.46 6.46 0 0 0 4.13 1.487 6.46 6.46 0 0 0 4.064-1.432l1.595 1.192.455-.455-1.181-1.582a6.486 6.486 0 0 0-4.932-10.693m4.269 7.33-4.39.44-.86-.87.51-5.325h.675l.47 4.845 3.595.235z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgAlarmClockSounded = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Alarm sounded
			</span>
		) : (
			''
		)}
	</>
);
