// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path d="M6.125 12.25h7.75v1.625h-7.75z" fill={theme?.fill} />
		<path d="M12.25 14.875H6.125V16.5h6.125z" fill={theme?.fill} />
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="m4.375 3.627-.875.875V19.5l.875.875h11.75L17 19.5V4.502l-.875-.875zm.75 5.873V5.252h10.25V9.5zm0 1.625v7.625h10.25v-7.625z"
			fill={theme?.fill}
		/>
		<path d="M18.762 5.5H17.75v13l.877-.01.748-.75V6.127z" fill={theme?.fill} />
		<path
			d="M21.012 7.492H20v9.086l.877-.01.748-.75V8.12z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgAllRecipes = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				All recipes
			</span>
		) : (
			''
		)}
	</>
);
