// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M7.818 2A3.31 3.31 0 0 0 4.51 5.309v13.254l.002-.002-.002.115a3.31 3.31 0 0 0 3.308 3.308h11.807l.875-.861v-.764h-.625a1.684 1.684 0 0 1 0-3.367h.625V2.873L19.625 2zm8.749 16.676c0 .615.167 1.19.46 1.683H7.817a1.684 1.684 0 0 1 0-3.367h9.208a3.3 3.3 0 0 0-.46 1.684m2.302-15.051h-11c-.812 0-1.625.75-1.625 1.75v10.438s.625-.438 1.5-.438H18.87z"
			fill={theme?.fill}
		/>
		<path d="M7.87 5.25h1.624v8.5H7.87z" fill={theme?.fill} />
	</svg>
);

export const SvgBookOutlined = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Book credit
			</span>
		) : (
			''
		)}
	</>
);
