// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M11.522 3.007a6 6 0 0 0-.022.48c0 3.03 2.457 5.213 5.487 5.213h.01v12.63l-.468.299-4.529-2.6-4.533 2.6L7 21.333V4.375l1.375-1.362zM20 1.437 17.926 3.51 20 5.586l-.936.914-2.075-2.052L14.937 6.5 14 5.541l2.052-2.052-2.03-2.03.915-.937 2.03 2.052L19.04.5z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgBookmarkCross = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Remove bookmark
			</span>
		) : (
			''
		)}
	</>
);
