// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M4.364 6.5v-1L5 4.717 9.818 3.63V2.543L10.364 2h3.272l.546.543V3.63L19 4.717l.636.783v1zM6 21 4.364 7.5h15.272L18 21l-1 1-10-.09zm8.182-3.348v-6.109l.545-.543.546.543v6.11l-.546.543zm-5.455-6.108v6.108l.546.544.545-.544v-6.108L9.273 11zm2.727 6.108v-6.109L12 11l.545.543v6.11l-.545.543z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgBin = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Delete
			</span>
		) : (
			''
		)}
	</>
);
