// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="m18 21-1 1-10-.09L6 21 4.364 7.5h15.272zm-9.273-9.456v6.108l.546.543.545-.543v-6.108L9.273 11zm2.727 0v6.108l.546.543.545-.543v-6.108L12 11zm2.728 0v6.108l.545.543.546-.543v-6.108L14.727 11zM13.636 2l.546.544v1.087L19 4.718l.636.782v1H4.364v-1L5 4.718 9.818 3.63V2.544L10.364 2z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgBin = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Delete
			</span>
		) : (
			''
		)}
	</>
);
