// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="m16.6 14.995-4.6 3.51-4.575-3.51-.885.885 5.13 5.125h.685l5.13-5.13z"
			fill={theme?.fill}
		/>
		<path
			d="m7.425 9.005 4.6-3.51 4.575 3.51.885-.885-5.13-5.125h-.685l-5.13 5.13z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgChevronUpAndDownSmall = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Sort
			</span>
		) : (
			''
		)}
	</>
);
