// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M19.67 4.305 2.57 21.429l-1.295-1.317 2.618-2.618A4.01 4.01 0 0 1 1 13.65c0-1.57 1.072-3.093 2.55-3.75 0-2.894 2.376-5.25 5.3-5.25 2.077 0 3.873 1.307 4.693 3.195L18.387 3zm-2.985 4.959c.278.197.536.427.765.686.49-.203 1.02-.3 1.55-.3a4 4 0 0 1 0 8h-2.75l-.001-.002h-3.7l-.032.002c-.544.027-2.47.024-4.235.017L9.8 16.15h.367v-.002H17.5v.002H19a2.5 2.5 0 0 0 0-5 2.56 2.56 0 0 0-2 1 3.07 3.07 0 0 0-1.407-1.794zM8.85 6.15c-2.101 0-3.8 1.679-3.8 3.75 0 .7.231 1.323.469 1.964l.03.086-.599.2-.45-1c-1.072.293-2 1.352-2 2.5 0 1.383 1.101 2.5 2.5 2.5h.237l7.113-7.113c-.437-1.6-1.786-2.887-3.5-2.887"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgCrossedOutCloud = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				No WiFi
			</span>
		) : (
			''
		)}
	</>
);
