// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="m17.72 13.296.165 6.046h1.13V21H5v-1.658h1.132l.226-6.04A4.552 4.552 0 1 1 7.99 4.436c1.136-1.113 2.642-1.811 4.394-1.811 1.683 0 3.224.61 4.413 1.62q.301-.042.617-.042a4.552 4.552 0 0 1 .306 9.093M7.57 7.55c.748-1.869 2.682-3.175 4.814-3.175.905 0 1.754.237 2.49.653-1.121.827-1.822 2.193-1.822 3.725h1.314c0-1.518 1.563-2.939 3.049-2.939 1.546 0 2.8 1.393 2.8 2.94a2.8 2.8 0 0 1-2.543 2.788l-.034-1.224h-1.25l-.166 6.052H7.756l-.12-3.196a4.54 4.54 0 0 0 1.778-.884l-.78-1.05c-.56.392-1.418.564-2.086.564-1.547 0-2.8-1.504-2.8-3.05a2.8 2.8 0 0 1 3.058-2.789 8 8 0 0 0-.51 1.046zm.237 10.196.06 1.595h8.273l.044-1.595z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgChef = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Chef
			</span>
		) : (
			''
		)}
	</>
);
