// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M11.16 13.85v8.88h1.75v-8.88l3.68 2.89.88-.88-5.12-5.13h-.69l-5.13 5.13.88.88z"
			fill={theme?.fill}
		/>
		<path
			d="M19.06 15c2.21 0 3.94-1.79 3.94-4s-1.79-4-4-4c-.53 0-1.06.1-1.55.3a4.66 4.66 0 0 0-3.53-1.61h-.17C13.08 3.55 11.1 2 8.77 2 5.9 2 3.57 4.35 3.54 7.25 2.07 7.91 1 9.43 1 11c0 2.22 1.71 4.02 3.92 4.02l1.52-1.52H5c-1.4 0-2.5-1.12-2.5-2.5 0-1.15.93-2.21 2-2.5l.45 1 .6-.2-.03-.09c-.24-.64-.47-1.32-.47-2.02 0-2.04 1.65-3.69 3.69-3.69s3.69 1.65 3.69 3.69c0 .1 0 .21-.01.31a3.213 3.213 0 0 1 4.59 1.97c.46-.6 1.23-.98 1.99-.98a2.5 2.5 0 0 1 0 5h-1.45l1.5 1.5"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgCloudUpload = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Cloud upload
			</span>
		) : (
			''
		)}
	</>
);
