// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M16.944 9.242a1.25 1.25 0 1 0 0-2.5 1.25 1.25 0 0 0 0 2.5"
			fill={theme?.fill}
		/>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M6.206 18.96a8.7 8.7 0 0 1 4.11-2.079l1.218-4.57-.144-.545-6.748 1.701-.76-.453L2.6 7.928l.454-.76 6.672-1.681-.142-.537 1.208-.32 1.39 5.248 1.734-6.503 1.208.322-.117.44 6.41 1.603.454.758-1.272 5.089-.758.455-6.507-1.628-.506 1.898 1.228 4.636a8.7 8.7 0 0 1 3.806 2.013h2.422v.875l-.75.75h-15l-.75-.75v-.875zm5.828-2.25a9 9 0 0 0-.38.009l.525-1.974.528 1.991a9 9 0 0 0-.673-.025m1.621-7.504 1.03-3.86L20.507 6.8l-.97 3.876zm-9.69-.978 1.24-.312 1.007 3.866-1.27.32zm3.612-.91-1.16.292 1.007 3.867 1.16-.293zm2.22 3.56L8.79 7.013l1.256-.317 1.024 3.863z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgCuisines = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Cuisines
			</span>
		) : (
			''
		)}
	</>
);
