// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M12.243 2.819c.67.06 1.99.19 3.46.99a8.2 8.2 0 0 1 2.63 2.3l-3.32.37-.07 1.13 5.82.32.45-.41.33-6.01-1.12-.06-.76 3.38h.01a10.02 10.02 0 0 0-7.34-3.82 9.98 9.98 0 0 0-8.43 3.91c.12.2.24.41.37.61.8-.63 4.06-3.05 7.97-2.71"
			fill={theme?.fill}
		/>
		<path
			d="M22.183 13.619c-.08-.38-.23-1.1-.82-1.79-.74-.86-1.69-1.09-1.97-1.15-1.08-.24-1.95.06-2.27.19-.16-.23-.43-.55-.87-.8-1-.58-2.05-.3-2.28-.23-.67-2.14-2.65-3.69-4.98-3.69-2.87 0-5.2 2.35-5.23 5.25-1.47.66-2.04 1.61-2.04 3.18 0 .26.04.47.09.66.23-.12.46-.23.7-.33 0-.25.03-.53.15-.83.33-.8 1.12-1.35 2.05-1.43l.45 1 .6-.2-.03-.09c-.24-.64-.47-1.32-.47-2.02 0-2.04 1.65-3.69 3.69-3.69s3.69 1.65 3.69 3.69c0 .1 0 .21-.01.31.16-.12.82-.58 1.72-.49.71.07 1.17.44 1.27.52.71.59.8 1.41.82 1.59.07-.08 1.16-1.21 2.43-.9.65.16 1.05.62 1.22.86.78 1.13.27 3.16-1.21 5.09a8.14 8.14 0 0 1-6.67 2.88 8.16 8.16 0 0 1-6.09-3.29l3.33-.37.06-1.14-5.82-.32-.45.41-.33 6.01 1.12.06.74-3.39c1.72 2.19 4.34 3.65 7.34 3.82 3.4.19 6.52-1.38 8.45-3.89.34-.44 2.14-2.98 1.62-5.48"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgCloudSync = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Cloud sync
			</span>
		) : (
			''
		)}
	</>
);
