// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2m0 .8a9.2 9.2 0 1 0 0 18.4 9.2 9.2 0 0 0 0-18.4m5.138 4.842L13.165 12l3.973 4.357-.782.78-4.35-3.98-4.362 3.966-.783-.781L10.85 12 6.86 7.657l.783-.78 4.363 3.967 4.35-3.983z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgCrossRoundOutlined = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Close
			</span>
		) : (
			''
		)}
	</>
);
