// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M21.35 2 23 3.703v15.112l-1.65 1.446H16l-2.9 3.495h-2.347V20.26H2.65L1 18.814V3.704L2.65 2zM3.75 4.21l-.55.553V17.5l.528.5h8.822v3.5L15.5 18h4.75l.55-.5V4.763l-.55-.552z"
			fill={theme?.fill}
		/>
		<path d="M5 10h9v2H5z" fill={theme?.fill} />
		<path d="M19 16h-9v-2h9z" fill={theme?.fill} />
		<path d="M15 10h4v2h-4z" fill={theme?.fill} />
		<path d="M9 16H5v-2h4z" fill={theme?.fill} />
	</svg>
);

export const SvgClosedCaptionsOff = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Closed captions off
			</span>
		) : (
			''
		)}
	</>
);
