// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M4.728 6.546h3.635V3h7.274v3.546h3.636V3h1.325L22 4.422v16.166l-1.402 1.39L3.402 22 2 20.588V4.422L3.402 3h1.326zm-.91 13.636h16.364V9.272H3.818zm9.19-2.273h-1.48v-4.772l-1.346.173v-.937l2-.827h.827zM7.456 5.637H5.637V2h1.818zm10.908 0h-1.817V2h1.817z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgCalendar = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Calendar
			</span>
		) : (
			''
		)}
	</>
);
