// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M17 8.5h-2.5L12.995 7h-2L9.5 8.5H7l-.5.5v6l.5.5h10l.5-.5V9zm-5 5.625a2.247 2.247 0 0 1-2.25-2.25A2.247 2.247 0 0 1 12 9.625a2.25 2.25 0 0 1 0 4.5"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgCameraSmall = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Camera
			</span>
		) : (
			''
		)}
	</>
);
