// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="m12.025 5.495-4.6 3.51-.885-.88 5.13-5.13h.685l5.13 5.125-.885.885zM12 18.505l4.6-3.51.885.88-5.13 5.13h-.685L6.54 15.88l.885-.885z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgChevronUpAndDownSmall = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Sort
			</span>
		) : (
			''
		)}
	</>
);
