// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M21.401 3.893 3.957 21.337l-1.342-1.342 3.56-3.56-.007-.006 2.041-2.041.005.009 1.674-1.674-.004-.01 2.12-2.12v.013l2.388-2.387-.008-.006 1.7-1.7.009.004L20.06 2.55zm-2.08 4.764a32 32 0 0 1 3.116 2.786v1.115c-.023.025-5.82 6.143-10.437 6.143-.744 0-1.519-.16-2.295-.427l1.827-1.828q.231.025.468.026c2.467 0 4.483-1.993 4.483-4.46q0-.248-.027-.49zM12 5.3c.719 0 1.466.148 2.216.399l-1.848 1.847a4.48 4.48 0 0 0-4.835 4.835L4.62 15.294a32 32 0 0 1-3.056-2.736v-1.115C1.603 11.4 7.39 5.299 12 5.299"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgEyeStrike = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Not visible
			</span>
		) : (
			''
		)}
	</>
);
