// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12 2c5.515 0 10 4.151 10 9.273 0 5.09-4.485 9.243-10 9.243-1.09 0-2.151-.152-3.151-.455L5.06 22v-4.09C3.18 16.241 2 13.878 2 11.272 2 6.15 6.485 2 12 2m1.546 9.424L10.97 8.758l-5.455 5.726 4.97-2.726 2.576 2.666 5.454-5.727z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgFacebookMessenger = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Facebook Messenger logo
			</span>
		) : (
			''
		)}
	</>
);
