// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12 2.057c5.523 0 10 4.477 10 10s-4.477 10-10 10-10-4.477-10-10 4.477-10 10-10m0 .833a9.167 9.167 0 1 0 0 18.335A9.167 9.167 0 0 0 12 2.89m1.975 13.116v1.5l-.485.5h-3l-.49-.5v-1.5zm2.015-3.996v1.495l-.5.505h-7l-.5-.505V12.01zm1.995-2.505-.495.5h-11l-.495-.5v-1.5h11.99z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgFilterOutlinedWeb = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Filter
			</span>
		) : (
			''
		)}
	</>
);
