// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path d="M2 3.285 3.283 2h17.434L22 3.285v.62H2z" fill={theme?.fill} />
		<path d="M22 20.715 20.717 22H3.283L2 20.715v-.62h20z" fill={theme?.fill} />
		<path d="M4 3.905H2v16.19h2z" fill={theme?.fill} />
		<path d="M22 3.905h-2v16.19h2z" fill={theme?.fill} />
		<path
			d="M11.35 7.339q-.147 0-.295.015t-.25.032l-.532 2.054H9.062V6.716a8 8 0 0 1 1.21-.296q.724-.14 1.477-.14.798 0 1.463.156.68.156 1.152.482.487.327.753.872.28.53.28 1.292 0 1.059-.546 1.713-.531.654-1.55 1.26-.754.437-1.079.732a.92.92 0 0 0-.325.701q0 .109.015.218.03.093.06.249h-1.168a3 3 0 0 1-.221-.498 2.6 2.6 0 0 1-.089-.7q0-.546.236-.935.251-.405.71-.794.546-.482.797-.95.266-.466.266-1.245 0-.81-.28-1.152-.281-.342-.872-.342m.193 10.524a1.34 1.34 0 0 1-1.049-.468 1.6 1.6 0 0 1-.413-1.09q0-.621.413-1.073a1.34 1.34 0 0 1 1.049-.467q.65 0 1.063.467.414.45.414 1.074 0 .622-.414 1.09-.413.465-1.063.466"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgGuessPuzzles = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Guess
			</span>
		) : (
			''
		)}
	</>
);
