// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12 2a10 10 0 0 1 9.136 5.936h.013v.029A10 10 0 0 1 22 12c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2M9.937 16.068c.189.83.43 1.567.707 2.183.337.75.687 1.235.975 1.506.139.13.243.192.303.22.053.024.075.023.078.023s.026 0 .078-.023c.06-.028.164-.09.303-.22.288-.271.638-.756.975-1.506.277-.616.518-1.352.707-2.183zm-4.825 0a8.03 8.03 0 0 0 3.866 3.34c-.46-.928-.83-2.063-1.086-3.34zm10.996 0c-.256 1.277-.627 2.412-1.087 3.34a8.03 8.03 0 0 0 3.867-3.34zm.294-6.132a22 22 0 0 1 0 4.132h3.326a8 8 0 0 0 .002-4.132zm-6.793 0a20 20 0 0 0 0 4.132h4.782a20 20 0 0 0 0-4.132zm-5.34 0a8 8 0 0 0 .002 4.132H7.6a22 22 0 0 1-.001-4.132zM15.022 4.59c.46.928.832 2.066 1.088 3.345h2.78a8.03 8.03 0 0 0-3.868-3.345m-3.1-.568c-.06.028-.163.09-.302.22-.288.271-.638.756-.975 1.506a11.7 11.7 0 0 0-.708 2.187h4.129c-.19-.832-.431-1.57-.709-2.187-.337-.75-.687-1.235-.975-1.506a1.2 1.2 0 0 0-.303-.22C12.026 4 12.003 4 12 4zm-2.942.568a8.03 8.03 0 0 0-3.87 3.345h2.782c.256-1.28.627-2.417 1.088-3.345"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgGlobe = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Globe
			</span>
		) : (
			''
		)}
	</>
);
