// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M17.75 6.75V10h1.5V6.75h3.25v-1.5h-3.25V2h-1.5v3.25H14.5v1.5zM18.5 12q.096 0 .19-.003v9.071l-.904.932H12.8v-6.786H8.277V22H3.309l-.904-.896v-9.056H1.5v-.453l.905-.905 7.6-7.69h.904l1.721 1.701q-.129.598-.13 1.299c0 3.038 2.5 6 6 6"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgHousePlus = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Add to home
			</span>
		) : (
			''
		)}
	</>
);
