// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12.63 4.702c-.084.398-.13.83-.13 1.298 0 3.038 2.5 6 6 6q.096-.001.19-.005v9.073l-.904.932h-4.985v-6.786H8.276V22H3.31l-.906-.895v-9.057H1.5v-.452l.904-.905L10.004 3h.905zm6.62.548h3.25v1.5h-3.25V10h-1.5V6.75H14.5v-1.5h3.25V2h1.5z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgHousePlus = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Add to home
			</span>
		) : (
			''
		)}
	</>
);
