// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2m0 .833a9.167 9.167 0 1 0 0 18.334 9.167 9.167 0 0 0 0-18.334m.027 3.168a5.53 5.53 0 0 1 5.53 5.528h-.001a5.5 5.5 0 0 1-.338 1.906c.209.38.327.815.327 1.278v.184c0 1.474-1.2 2.674-2.675 2.674h-.38l-.92-.92v-3.692l.92-.92h.38c.617 0 1.181.21 1.634.56.083-.342.13-.7.13-1.07a4.614 4.614 0 0 0-4.607-4.606 4.614 4.614 0 0 0-4.607 4.606c0 .373.05.735.134 1.082A2.66 2.66 0 0 1 9.2 12.04h.38l.921.92v3.692l-.921.921h-.38a2.68 2.68 0 0 1-2.675-2.675v-.183c0-.456.117-.886.318-1.26a5.528 5.528 0 0 1 5.184-7.453m-2.826 6.96a1.753 1.753 0 0 0-1.749 1.674q-.004.04-.005.08v.183c0 .97.786 1.754 1.754 1.754h.38v-3.691zm5.292-.002v3.691h.38c.969 0 1.754-.785 1.754-1.753v-.184l-.003-.003c0-.035-.005-.068-.005-.103a1.73 1.73 0 0 0-.45-1.072 1.74 1.74 0 0 0-1.296-.576z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgHeadphonesRoundOutlined = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Listen
			</span>
		) : (
			''
		)}
	</>
);
