// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12.63 4.202c-.084.398-.13.83-.13 1.298 0 3.037 2.5 6 6 6q.096-.001.19-.005v9.073l-.904.932h-4.985v-6.786H8.276V21.5H3.31l-.906-.896v-9.056H1.5v-.453l.904-.904 7.6-7.691h.905zm9.228-1L19.561 5.5l2.297 2.298-1.06 1.061L18.5 6.56 16.202 8.86l-1.06-1.06 2.297-2.3-2.297-2.297 1.06-1.06L18.5 4.438l2.298-2.298z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgHouseCross = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Remove from home
			</span>
		) : (
			''
		)}
	</>
);
