// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="m19.686 9.742.002-.004 1.358 1.358v.452h-.906v9.02l-.904.932H4.76l-.906-.895v-9.057H2.95v-.452l.904-.905 7.6-7.691h.905zM11.976 8c-.276 0-.6.025-.95.075L10.8 9.3c-.475.075-.9.25-1.3.475l-1-.65c-.575.375-.975.825-1.375 1.325l.65 1.05c-.25.425-.4.85-.475 1.25l-1.225.275c-.025.375-.075.625-.075 1 0 .3.05.575.075.95l1.225.2c.075.5.25.85.475 1.325l-.65.975c.375.525.85 1 1.375 1.4l1-.65c.375.225.825.375 1.3.475l.225 1.225c.375.025.65.075.95.075.375 0 .626-.05 1-.075L13.2 18.7c.475-.1.925-.25 1.3-.475l1.025.65c.525-.4.95-.825 1.35-1.4l-.65-.975c.225-.4.4-.825.475-1.325l1.225-.2c.025-.375.075-.65.075-.95 0-.375-.05-.625-.075-1L16.7 12.75c-.075-.475-.25-.85-.475-1.25l.65-1.05c-.4-.5-.825-.95-1.35-1.325l-1.025.65c-.4-.225-.825-.4-1.3-.475l-.225-1.225a7 7 0 0 0-1-.075m0 3.13c1.674 0 2.899 1.225 2.899 2.9 0 1.5-1.25 2.85-2.9 2.85-1.6 0-2.85-1.35-2.85-2.85 0-1.65 1.25-2.9 2.85-2.9"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgHouseSetting = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Settings
			</span>
		) : (
			''
		)}
	</>
);
