// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="m19.686 9.742.002-.004 1.358 1.358v.452h-.906v9.02l-.904.932h-4.985v-6.786H9.726V21.5H4.76l-.906-.895v-9.057H2.95v-.452l.904-.905 7.6-7.691h.905z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgHomeHouseFilled = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Home
			</span>
		) : (
			''
		)}
	</>
);
