// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="m18.5 6.56 2.298 2.299 1.06-1.06L19.562 5.5l2.298-2.298-1.06-1.06L18.5 4.438l-2.298-2.298-1.06 1.06L17.438 5.5l-2.298 2.298 1.06 1.06zm0 4.94q.096 0 .19-.003v9.071l-.904.932H12.8v-6.786H8.277V21.5H3.309l-.904-.896v-9.056H1.5v-.453l.905-.905 7.6-7.69h.904l1.721 1.701q-.129.598-.13 1.299c0 3.038 2.5 6 6 6"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgHouseCross = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Remove from home
			</span>
		) : (
			''
		)}
	</>
);
