// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2m5.55 9.53c0 .67-.12 1.31-.34 1.9.21.38.33.82.33 1.28v.18c0 1.47-1.2 2.67-2.67 2.67h-.38l-.78-.78-.14-.14v-3.69l.92-.92h.38c.62 0 1.18.21 1.63.56.08-.34.13-.7.13-1.07 0-2.54-2.07-4.61-4.61-4.61s-4.61 2.07-4.61 4.61c0 .37.05.73.13 1.08.46-.36 1.03-.57 1.65-.57h.38l.92.92v3.69l-.15.15-.77.77h-.38c-1.47 0-2.67-1.2-2.67-2.67v-.18c0-.46.12-.89.32-1.26a5.6 5.6 0 0 1-.34-1.92C6.5 8.48 8.97 6 12.03 6s5.53 2.48 5.53 5.53z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgHeadphonesRoundFilled = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Listening
			</span>
		) : (
			''
		)}
	</>
);
