// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M17.05 4.13c.622-1.078 2.05-1.46 3.155-.83.54.305.925.803 1.087 1.397a2.27 2.27 0 0 1-.222 1.748l-2.828 4.55h2.85l.908.917c0 4.51-2.473 8.387-6.004 10.083H8.003C4.468 20.3 2 16.422 2 11.912l.908-.917h3.25l-.002-.04a1.078 1.078 0 1 1 2.157 0l-.002.04h4.502zM3.648 12.62c.23 3.472 2.145 6.358 4.742 7.75h7.218c2.594-1.393 4.511-4.279 4.743-7.75zm15.75-7.908c-.344-.196-.774-.059-.942.23l-.012.022-3.736 6.031h1.573l3.39-5.379a.65.65 0 0 0 .053-.49.66.66 0 0 0-.319-.41zm-8.133 3.227a1.078 1.078 0 1 1 0 2.157 1.078 1.078 0 0 1 0-2.157M5.17 3.441l3.314 4.655-.594.781-5.504-1.479-.454-1.04.007-.013.017-.037.067-.134c.055-.112.132-.268.22-.438.17-.326.402-.757.598-1.035.199-.282.517-.626.756-.876a20 20 0 0 1 .321-.328l.1-.098.027-.027.008-.007.003-.003zm9.355-1.857A3.463 3.463 0 0 1 9.09 5.875l.124-1.054 4.258-3.361zM4.513 5.041c-.18.195-.347.387-.444.524a7 7 0 0 0-.39.664l2.31.716zm6.335.401a1.964 1.964 0 0 0 2.848-2.248zM7.703 1.995a1.078 1.078 0 1 1 0 2.157 1.078 1.078 0 0 1 0-2.157"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgIngredient3 = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Ingredient
			</span>
		) : (
			''
		)}
	</>
);
