// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="m13.696 3.194-2.848 2.248a1.963 1.963 0 0 0 2.848-2.248m.83-1.61a3.463 3.463 0 0 1-5.436 4.29l.124-1.053 4.258-3.361zM7.702 4.152a1.078 1.078 0 1 0 0-2.157 1.078 1.078 0 0 0 0 2.157m4.64 4.865a1.078 1.078 0 1 1-2.155 0 1.078 1.078 0 0 1 2.156 0m-4.031 1.978v-.04a1.078 1.078 0 1 0-2.155.04H2.909l-.91.917c0 4.51 2.469 8.387 6.004 10.083h7.994C19.527 20.3 22 16.422 22 11.912l-.909-.917h-2.849l2.827-4.55c.307-.53.386-1.153.223-1.747A2.29 2.29 0 0 0 20.205 3.3c-1.106-.632-2.533-.25-3.155.83l-4.237 6.864zm-5.47-6.294c-.196.278-.428.709-.598 1.035a25 25 0 0 0-.286.572l-.018.037-.007.014.454 1.04 5.504 1.478.593-.781-3.313-4.654-1.114-.08-.003.003-.008.007-.028.028a17 17 0 0 0-.42.425c-.24.25-.557.594-.756.876M5.99 6.945l-2.31-.716c.142-.265.285-.516.39-.663.096-.138.263-.33.444-.525zm8.72 4.05h1.572l3.39-5.38a.65.65 0 0 0 .054-.489.66.66 0 0 0-.319-.41l-.003-.002-.004-.002c-.344-.197-.775-.059-.942.23l-.012.022zM8.391 20.37c-2.597-1.392-4.512-4.278-4.743-7.75h16.703c-.231 3.471-2.148 6.358-4.743 7.75z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgIngredient3 = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Ingredient
			</span>
		) : (
			''
		)}
	</>
);
