// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="m9.164 4.285 3.005-1.626-.35-.869-3.493 1.011zM2 11.915l.909-.917h9.279l4.236-6.864c.623-1.08 2.05-1.462 3.156-.83.539.304.925.802 1.087 1.397a2.27 2.27 0 0 1-.223 1.747l-2.821 4.55h3.468l.909.917c0 4.51-2.472 8.388-6.003 10.083H8.003C4.468 20.302 2 16.425 2 11.915m1.648.708c.231 3.473 2.146 6.358 4.743 7.75h7.217c2.595-1.392 4.512-4.279 4.744-7.75zm8.18-5.218a1.078 1.078 0 1 0 0-2.157 1.078 1.078 0 0 0 0 2.157m-3.566 1.28a6.5 6.5 0 0 1-.406-.754c-.055-.12-.111-.25-.164-.373l-.003-.007c-.171-.396-.325-.745-.493-1.012-.228-.362-.488-.597-.876-.698-.271-.07-.638-.083-1.146.015l1.183 1.17-.277.372-1.453-.855c.093.542.3.932.555 1.218.386.432.932.684 1.531.817.546.12 1.104.134 1.55.108m1.232 1.113c-.17.032-.738.105-1.01.126a7.1 7.1 0 0 1-2.04-.126c-.754-.166-1.576-.512-2.194-1.205-.633-.709-.977-1.695-.918-2.986l.023-.508.48-.167c1.129-.39 2.042-.496 2.797-.3.792.204 1.284.705 1.622 1.24.229.364.42.807.582 1.183q.083.193.156.355c.219.477.502.924.79 1.183zm9.552-4.18a.65.65 0 0 0 .054-.489.66.66 0 0 0-.319-.41l-.003-.002-.004-.002c-.344-.197-.775-.059-.942.23l-.012.022-3.722 6.031h1.613z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgIngredient2 = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Ingredient
			</span>
		) : (
			''
		)}
	</>
);
