// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M16.425 4.134c.622-1.079 2.05-1.462 3.155-.83.539.304.924.802 1.087 1.396a2.27 2.27 0 0 1-.223 1.748l-2.821 4.55h3.468l.909.917c0 4.51-2.472 8.387-6.003 10.083H8.003C4.468 20.302 2 16.425 2 11.915l.91-.917h9.278zM3.648 12.623c.231 3.472 2.146 6.358 4.743 7.75h7.217c2.595-1.393 4.512-4.279 4.744-7.75zm15.126-7.908c-.344-.197-.775-.058-.942.231l-.012.02-3.722 6.032h1.613l3.335-5.379a.65.65 0 0 0 .054-.49.66.66 0 0 0-.319-.41l-.004-.002zm-14.938.218c1.128-.39 2.04-.497 2.796-.302.792.204 1.284.706 1.622 1.242.23.364.42.806.582 1.183q.082.192.156.354c.219.477.501.923.79 1.183l-.289 1.205c-.17.032-.737.105-1.01.126-.54.042-1.284.04-2.04-.126C5.69 9.63 4.87 9.286 4.25 8.593c-.633-.709-.976-1.695-.918-2.986l.022-.508zm2.483.909c-.27-.07-.637-.084-1.145.014l1.182 1.17-.276.372-1.452-.855c.092.542.3.932.555 1.218.385.431.932.684 1.53.816.546.12 1.104.134 1.55.109a6.5 6.5 0 0 1-.408-.755c-.054-.12-.11-.251-.163-.373l-.004-.007c-.17-.396-.324-.745-.492-1.012-.228-.362-.488-.597-.877-.697m5.51-.594a1.078 1.078 0 1 1-.001 2.157 1.078 1.078 0 0 1 0-2.157m.34-2.589L9.164 4.285l-.839-1.483L11.82 1.79z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgIngredient2 = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Ingredient
			</span>
		) : (
			''
		)}
	</>
);
