// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M5.81 17.38v2.8h-2.8v-2.8zm15.24 1.83-.39.5H8.05v-2h13zm-15.25-5H3v-2.8h2.8zm15.25-1.2-.39.5H8.05v-2h13zM5.8 7.8H3V5h2.8zm15.25-.99-.39.5H8.05v-2h13z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgList = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				list
			</span>
		) : (
			''
		)}
	</>
);
