// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M3 5h2.8v2.8H3zm18.05.31h-13v2h12.61l.39-.5zm0 6.2h-13v2h12.61l.39-.5zm-13 6.2h13v1.5l-.39.5H8.05zm-2.25-6.3H3v2.8h2.8zm-2.79 5.97h2.8v2.8h-2.8z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgList = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				list
			</span>
		) : (
			''
		)}
	</>
);
