// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<g clipPath="url(#media-controls-play__a)">
			<path
				fillRule="evenodd"
				clipRule="evenodd"
				d="M19.2 12.39v-.72L8.59 5 8 5.36v13.23l.59.41z"
				fill={theme?.fill}
			/>
		</g>
		<defs>
			<clipPath id="media-controls-play__a">
				<rect
					width={11.2}
					height={14}
					fill="white"
					transform="translate(8 5)"
				/>
			</clipPath>
		</defs>
	</svg>
);

export const SvgMediaControlsPlay = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Stop
			</span>
		) : (
			''
		)}
	</>
);
