// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M9.273 2c1 0 1.954.182 2.84.568.887.387 1.637.91 2.296 1.568.66.66 1.16 1.432 1.545 2.319a6.9 6.9 0 0 1 .569 2.818c0 1-.182 1.931-.569 2.818-.386.886-.886 1.659-1.545 2.318-.659.66-1.409 1.16-2.295 1.545-.887.387-1.841.569-2.841.569s-1.932-.182-2.818-.569-1.66-.886-2.319-1.545a7.5 7.5 0 0 1-1.568-2.318A6.9 6.9 0 0 1 2 9.273c0-1 .182-1.932.568-2.818q.58-1.33 1.568-2.319a7.5 7.5 0 0 1 2.319-1.568A6.9 6.9 0 0 1 9.273 2m0 1.84q-1.125 0-2.114.41c-.659.295-1.25.682-1.727 1.16-.5.5-.887 1.067-1.16 1.726a5.2 5.2 0 0 0-.431 2.137 5.1 5.1 0 0 0 .432 2.113c.272.66.659 1.228 1.159 1.728S6.5 14 7.159 14.295a5.1 5.1 0 0 0 2.114.432 5.1 5.1 0 0 0 2.113-.431 5.8 5.8 0 0 0 1.75-1.182 5.8 5.8 0 0 0 1.16-1.728c.295-.659.431-1.363.431-2.113s-.136-1.478-.432-2.137C14 6.477 13.636 5.91 13.136 5.41s-1.09-.864-1.75-1.159a5.5 5.5 0 0 0-2.113-.41m-.546 3.796c0 .5-.409.91-.909.91s-.909-.41-.909-.91c0-.522.41-.909.91-.909s.908.387.908.91m2.91 0c0 .5-.41.91-.91.91s-.909-.41-.909-.91c0-.522.41-.909.91-.909s.908.387.908.91M9.272 11.25c-1 0-1.91.273-2.682.818l-.41-.432a5 5 0 0 1 1.387-.954c.523-.228 1.091-.318 1.705-.318.613 0 1.181.09 1.704.318.523.25 1 .568 1.387.954l-.41.432c-.772-.545-1.659-.818-2.681-.818m5.454 5.318v-.932l.91-.909h.931L22 20.16 20.16 22z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgMagnifyingGlassSadFace = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				No results
			</span>
		) : (
			''
		)}
	</>
);
