// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="m17.49 2 .71.71v4.97h2.37l1.44 1.6-.01.01v3.14l-.02 7.48v.66l-.46.47-.48.49-.47.47h-.66l-15.79.02h-.66l-.47-.46-.52-.51-.47-.47V9.28l.006.002L3.42 7.68h2.36V2.71l.7-.71zm-4.73 16.04h-1.59L3.6 12.45v7.47l.52.51 15.79-.02.5-.49-.01-7.48zM7.08 3.3V13.49l4.61 2.929h.54l4.67-2.95V3.3zM4.14 9.28l-.54.609v1.391l2.18 1.385V9.28zm14.06 3.37 2.2-1.39V9.875l-.54-.595H18.2zm-2.77-1.33H8.56v-1h6.87zm0-2.64H8.56v-1h6.87zm0-2.64H8.56v-1h6.87z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgNewsletterOutlined = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Newsletter
			</span>
		) : (
			''
		)}
	</>
);
