// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2M7.795 8.21A4.87 4.87 0 0 0 6 11.997c0 1.537.7 2.89 1.795 3.787l.259-.259c-.75-.983-1.218-2.2-1.218-3.528s.468-2.546 1.218-3.53zm8.127.258a5.6 5.6 0 0 1 1.218 3.53c0 1.327-.431 2.544-1.218 3.527l.283.26A4.87 4.87 0 0 0 18 11.996c0-1.537-.7-2.89-1.795-3.787zM8.902 9.61c-.628.59-.984 1.452-.984 2.386s.357 1.758.983 2.385l.332-.32a3.55 3.55 0 0 1-.638-2.065c0-.787.233-1.488.638-2.078zm5.876.308c.394.59.628 1.291.628 2.078s-.234 1.488-.628 2.066l.308.319c.627-.627.996-1.45.996-2.385s-.369-1.796-.996-2.386zm-2.778.11a1.96 1.96 0 0 0-1.968 1.968c0 1.094.874 1.967 1.968 1.967a1.957 1.957 0 0 0 1.967-1.967A1.96 1.96 0 0 0 12 10.03"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgNotificationsOnRound = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Notification on
			</span>
		) : (
			''
		)}
	</>
);
