// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M19.625 9.683V6.25L16.25 2.838l-9 .037-.875.875v16.5l.875.875h11.5l.875-.875v-8.208l-3.562 3.562-1.18-1.179zM16.321 9.5h-7.5v1.25h7.5zm-2.084 2.917H8.822v1.25h5.417zm-1.666 2.916H8.82v1.25h3.75zm1.496 1.417-.296-.292.712-1.595 1.18 1.175z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgNoteFilled = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Note
			</span>
		) : (
			''
		)}
	</>
);
