// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M7.753 9.085h8.51V6.957a4.255 4.255 0 0 0-8.51 0zm4.256 3.404a1.276 1.276 0 0 0-.426 2.48v1.776h.851V14.97a1.277 1.277 0 0 0-.425-2.48m5.957-3.404.851.852v10.212l-.851.851H6.05l-.851-.85V9.936l.85-.852V6.957h.002a5.957 5.957 0 0 1 11.914 0z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgPadlock = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Lock
			</span>
		) : (
			''
		)}
	</>
);
