// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M8.063 10.438V7.59c0-2.164 1.77-3.903 3.937-3.903s3.938 1.739 3.938 3.903v2.847H17l.813.812v8.25l-.813.813H7l-.812-.813v-8.25L7 10.438zM9.687 7.59c0-1.25 1.027-2.278 2.313-2.278s2.313 1.028 2.313 2.278v2.847H9.686zM7.813 18.687v-6.625h8.375v6.626z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgPadlockLocked = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Padlock locked
			</span>
		) : (
			''
		)}
	</>
);
