// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M18.323 13.99a7.1 7.1 0 0 0-3.603-3.456l-.59-6.87A7 7 0 0 0 16.89 2H7.113a6.85 6.85 0 0 0 2.76 1.665l-.569 6.87A7.07 7.07 0 0 0 5.68 13.99h5.331v6.006l.99 4.004.99-4.004V13.99h5.333"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgPinned = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Pinned
			</span>
		) : (
			''
		)}
	</>
);
