// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2m0 .833a9.167 9.167 0 1 0 0 18.334 9.167 9.167 0 0 0 0-18.334m-4.263 8.693v3.79h8.526v-3.79l.473-.473h.475v4.724l-.486.486H7.25l-.462-.486v-4.724h.474zm6.857-2.31-.427.416-1.693-1.291v4.133h-.948V8.34L9.833 9.63l-.415-.414 2.416-2.428h.332z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgShareRoundOutline = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Share
			</span>
		) : (
			''
		)}
	</>
);
