// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<g clipPath="url(#sort__a)">
			<path
				fillRule="evenodd"
				clipRule="evenodd"
				d="M3 6h18v1.5l-.49.5H3V6m12.007 5.01H3v2h11.506l.5-.51zM8.983 16H3v2h5.503l.48-.5z"
				fill={theme?.fill}
			/>
		</g>
		<defs>
			<clipPath id="sort__a">
				<rect width={18} height={12} fill="white" transform="translate(3 6)" />
			</clipPath>
		</defs>
	</svg>
);

export const SvgSort = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Sort
			</span>
		) : (
			''
		)}
	</>
);
