// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M19.25 4.5V22H17.5V5.375H6.375V22h-1.75V4.5l.875-.875h12.875zM14.5 18.75H8v-1.625h6.5zm1.125-3H8v-1.625h7.625zm-.5-3H8v-1.625h7.125zm1-3H8V8.125h8.125z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgShoppingList = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Shopping list
			</span>
		) : (
			''
		)}
	</>
);
