// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="m4.625 4.5.875-.875h12.875l.875.875V22H17.5V5.375H6.375V22h-1.75zM8 8.125h8.125V9.75H8zm7.125 3H8v1.625h7.125zm-7.125 3h7.625v1.625H8zm6.5 3H8v1.625h6.5z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgShoppingList = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Shopping list
			</span>
		) : (
			''
		)}
	</>
);
