// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M12 2c5.52 0 10 4.48 10 10s-4.48 10-10 10S2 17.52 2 12 6.48 2 12 2M6.54 15.13l-.91.22v.57H8.5v-.55l-1.05-.24.74-2.26h3.02l.74 2.26-1.04.24v.55h3.35v-.57l-.89-.22-2.84-8.33H9.46zm7.2-2.15.33.88v-.03h2.16l.51 1.52-.75.18v.39h2.37v-.38l-.62-.18-2.02-5.87h-.76zm2.34.39h-1.83l.92-2.73h.03zM9.79 8.44l1.27 3.9H8.4l1.33-3.9z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgTextSizeRoundFilled = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Text size active
			</span>
		) : (
			''
		)}
	</>
);
