// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import type { IconProps } from '../..';
import { iconSize, visuallyHidden } from '../../../foundations';

const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="0 0 25 25"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			d="M4.563 22.079v1.82h7.994l-.042-1.58-5.571-.053c.478-.312 1.05-.998 1.621-1.611a8.8 8.8 0 0 0 1.674-2.568H8.586c-.322.582-.8 1.3-1.486 2.017a9.8 9.8 0 0 1-2.537 1.975"
			fill={theme?.fill}
		/>
		<path
			d="M20.447 22.079v1.82h-7.994l.042-1.58 5.571-.053c-.478-.312-1.05-.998-1.621-1.611a8.8 8.8 0 0 1-1.674-2.568h1.653c.322.582.8 1.3 1.486 2.017.905.977 1.85 1.6 2.537 1.975"
			fill={theme?.fill}
		/>
		<path
			d="m6.632 1.04-1.518.769v1.05h14.73V1.767L18.17 1.04z"
			fill={theme?.fill}
		/>
		<path
			d="m9.605 18.098-.728.759v1.05h7.069v-1.092l-.8-.717z"
			fill={theme?.fill}
		/>
		<path
			d="m13.44 15.01-.457-.135h-1.362v3.379h1.362l.458-.146z"
			fill={theme?.fill}
		/>
		<path
			d="M1.843 5.499s0 4.99 4.99 7.92l1.06-.748-.956-1.195s-2.703-1.279-3.66-5.239l2.87-.676-.063-1.174H2.716z"
			fill={theme?.fill}
		/>
		<path
			d="m22.308 4.394.873 1.112s0 4.99-4.99 7.921l-1.06-.748.956-1.196s2.703-1.278 3.66-5.239l-2.87-.675.063-1.175z"
			fill={theme?.fill}
		/>
		<path
			d="M12.484 14.002c5.8-.239 5.624-11.403 5.624-11.403h1.736s.239 12.723-7.245 13.108C4.875 15.55 5.125 2.599 5.125 2.599H6.86s-.188 11.174 5.634 11.403z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgTrophy = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Trophy
			</span>
		) : (
			''
		)}
	</>
);
