// DO NOT EDIT
// this file is auto-generated by libs/@guardian/source/scripts/create-icons/index.ts
import { css } from '@emotion/react';
import { iconSize, visuallyHidden } from '../../../foundations';
import type { IconProps } from '../..';
const Svg = ({ size, theme }: IconProps) => (
	<svg
		width={size ? iconSize[size] : undefined}
		height={undefined}
		viewBox="-3 -3 30 30"
		xmlns="http://www.w3.org/2000/svg"
		focusable={false}
		aria-hidden={true}
	>
		<path
			fillRule="evenodd"
			clipRule="evenodd"
			d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2m2.26 13.92h-3.35v-.55l1.04-.24-.74-2.26H8.19l-.74 2.26 1.05.24v.55H5.63v-.57l.91-.22L9.46 6.8h1.07l2.84 8.33.89.22zm4.1 0h-2.37v-.39l.75-.18-.51-1.52h-2.16v.03l-.33-.88 1.22-3.49h.76l2.02 5.87.62.18zm-3.19-5.28-.92 2.73h1.83l-.88-2.73zm-6.77 1.7 1.33-3.9h.06l1.27 3.9z"
			fill={theme?.fill}
		/>
	</svg>
);

export const SvgTextSizeRoundFilled = ({
	size,
	theme,
	isAnnouncedByScreenReader = false,
}: IconProps) => (
	<>
		<Svg size={size} theme={theme} />
		{isAnnouncedByScreenReader ? (
			<span
				css={css`
					${visuallyHidden}
				`}
			>
				Text size active
			</span>
		) : (
			''
		)}
	</>
);
