// Typography presets
// Auto-generated by scripts/build-type-presets.ts
// DO NOT EDIT
import type { TypographyPreset } from './types';

export const article15: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.4;
	font-weight: 400;
	font-style: normal;
`;

export const article17: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.4;
	font-weight: 400;
	font-style: normal;
`;

export const articleBold15: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.4;
	font-weight: 700;
	font-style: normal;
`;

export const articleBold17: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.4;
	font-weight: 700;
	font-style: normal;
`;

export const articleBoldItalic15: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.4;
	font-weight: 700;
	font-style: italic;
`;

export const articleBoldItalic17: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.4;
	font-weight: 700;
	font-style: italic;
`;

export const articleItalic15: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.4;
	font-weight: 400;
	font-style: italic;
`;

export const articleItalic17: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.4;
	font-weight: 400;
	font-style: italic;
`;

export const headlineBold14: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold17: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold20: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold24: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold28: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold34: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold42: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold50: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold70: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineLight14: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight17: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight20: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight24: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight28: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight34: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight42: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight50: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight70: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLightItalic14: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic17: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic20: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic24: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic28: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic34: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic42: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic50: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic70: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineMedium14: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium17: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium20: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium24: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium28: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium34: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium42: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium50: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium70: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMediumItalic14: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic17: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic20: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic24: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic28: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic34: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic42: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic50: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic70: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: italic;
`;

export const kicker14: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const kicker17: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const kicker20: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const kicker24: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const kicker34: TypographyPreset = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const textEgyptian14: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textEgyptian15: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textEgyptian17: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textEgyptianBold14: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textEgyptianBold15: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textEgyptianBold17: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textEgyptianBoldItalic14: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: italic;
`;

export const textEgyptianBoldItalic15: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: italic;
`;

export const textEgyptianBoldItalic17: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: italic;
`;

export const textEgyptianItalic14: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textEgyptianItalic15: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textEgyptianItalic17: TypographyPreset = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSans12: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.75rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans14: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans15: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans17: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans20: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.25rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans24: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.5rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans28: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.75rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans34: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 2.125rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSansBold12: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.75rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold14: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold15: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold17: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold20: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.25rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold24: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.5rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold28: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.75rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold34: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 2.125rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansItalic12: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.75rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic14: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic15: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic17: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic20: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.25rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic24: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.5rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic28: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.75rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic34: TypographyPreset = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 2.125rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const titlepiece42: TypographyPreset = `
	font-family: "GT Guardian Titlepiece", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const titlepiece50: TypographyPreset = `
	font-family: "GT Guardian Titlepiece", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const titlepiece70: TypographyPreset = `
	font-family: "GT Guardian Titlepiece", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;
