// Typography presets
// Auto-generated by scripts/build-type-presets.ts
// DO NOT EDIT

export const article15Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.9375rem',
	lineHeight: 1.4,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const article17Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.4,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const articleBold15Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.9375rem',
	lineHeight: 1.4,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const articleBold17Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.4,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const articleBoldItalic15Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.9375rem',
	lineHeight: 1.4,
	fontWeight: 700,
	fontStyle: 'italic',
};

export const articleBoldItalic17Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.4,
	fontWeight: 700,
	fontStyle: 'italic',
};

export const articleItalic15Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.9375rem',
	lineHeight: 1.4,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const articleItalic17Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.4,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const headlineBold14Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const headlineBold17Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const headlineBold20Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.25rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const headlineBold24Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.5rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const headlineBold28Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.75rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const headlineBold34Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.125rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const headlineBold42Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.625rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const headlineBold50Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '3.125rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const headlineBold70Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '4.375rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const headlineLight14Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'normal',
};

export const headlineLight17Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'normal',
};

export const headlineLight20Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.25rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'normal',
};

export const headlineLight24Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.5rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'normal',
};

export const headlineLight28Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.75rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'normal',
};

export const headlineLight34Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.125rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'normal',
};

export const headlineLight42Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.625rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'normal',
};

export const headlineLight50Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '3.125rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'normal',
};

export const headlineLight70Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '4.375rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'normal',
};

export const headlineLightItalic14Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'italic',
};

export const headlineLightItalic17Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'italic',
};

export const headlineLightItalic20Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.25rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'italic',
};

export const headlineLightItalic24Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.5rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'italic',
};

export const headlineLightItalic28Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.75rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'italic',
};

export const headlineLightItalic34Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.125rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'italic',
};

export const headlineLightItalic42Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.625rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'italic',
};

export const headlineLightItalic50Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '3.125rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'italic',
};

export const headlineLightItalic70Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '4.375rem',
	lineHeight: 1.15,
	fontWeight: 300,
	fontStyle: 'italic',
};

export const headlineMedium14Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'normal',
};

export const headlineMedium17Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'normal',
};

export const headlineMedium20Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.25rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'normal',
};

export const headlineMedium24Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.5rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'normal',
};

export const headlineMedium28Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.75rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'normal',
};

export const headlineMedium34Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.125rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'normal',
};

export const headlineMedium42Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.625rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'normal',
};

export const headlineMedium50Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '3.125rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'normal',
};

export const headlineMedium70Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '4.375rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'normal',
};

export const headlineMediumItalic14Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'italic',
};

export const headlineMediumItalic17Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'italic',
};

export const headlineMediumItalic20Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.25rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'italic',
};

export const headlineMediumItalic24Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.5rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'italic',
};

export const headlineMediumItalic28Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.75rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'italic',
};

export const headlineMediumItalic34Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.125rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'italic',
};

export const headlineMediumItalic42Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.625rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'italic',
};

export const headlineMediumItalic50Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '3.125rem',
	lineHeight: 1.15,
	fontWeight: 500,
	fontStyle: 'italic',
};

export const headlineMediumItalic70Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '4.375rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'italic',
};

export const kicker14Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const kicker17Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const kicker20Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.25rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const kicker24Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '1.5rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const kicker34Object = {
	fontFamily: '"GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif',
	fontSize: '2.125rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textEgyptian14Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textEgyptian15Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.9375rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textEgyptian17Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textEgyptianBold14Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textEgyptianBold15Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.9375rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textEgyptianBold17Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textEgyptianBoldItalic14Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'italic',
};

export const textEgyptianBoldItalic15Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.9375rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'italic',
};

export const textEgyptianBoldItalic17Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'italic',
};

export const textEgyptianItalic14Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.875rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textEgyptianItalic15Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '0.9375rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textEgyptianItalic17Object = {
	fontFamily:
		'GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif',
	fontSize: '1.0625rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textSans12Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '0.75rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textSans14Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '0.875rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textSans15Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '0.9375rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textSans17Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.0625rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textSans20Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.25rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textSans24Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.5rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textSans28Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.75rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textSans34Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '2.125rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'normal',
};

export const textSansBold12Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '0.75rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textSansBold14Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '0.875rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textSansBold15Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '0.9375rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textSansBold17Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.0625rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textSansBold20Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.25rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textSansBold24Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.5rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textSansBold28Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.75rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textSansBold34Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '2.125rem',
	lineHeight: 1.3,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const textSansItalic12Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '0.75rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textSansItalic14Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '0.875rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textSansItalic15Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '0.9375rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textSansItalic17Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.0625rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textSansItalic20Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.25rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textSansItalic24Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.5rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textSansItalic28Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '1.75rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const textSansItalic34Object = {
	fontFamily:
		'GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
	fontSize: '2.125rem',
	lineHeight: 1.3,
	fontWeight: 400,
	fontStyle: 'italic',
};

export const titlepiece42Object = {
	fontFamily: '"GT Guardian Titlepiece", Georgia, serif',
	fontSize: '2.625rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const titlepiece50Object = {
	fontFamily: '"GT Guardian Titlepiece", Georgia, serif',
	fontSize: '3.125rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};

export const titlepiece70Object = {
	fontFamily: '"GT Guardian Titlepiece", Georgia, serif',
	fontSize: '4.375rem',
	lineHeight: 1.15,
	fontWeight: 700,
	fontStyle: 'normal',
};
