// Typography presets
// Auto-generated by scripts/build-type-presets.ts
// DO NOT EDIT

export const article15 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.4;
	font-weight: 400;
	font-style: normal;
`;

export const article17 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.4;
	font-weight: 400;
	font-style: normal;
`;

export const articleBold15 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.4;
	font-weight: 700;
	font-style: normal;
`;

export const articleBold17 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.4;
	font-weight: 700;
	font-style: normal;
`;

export const articleBoldItalic15 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.4;
	font-weight: 700;
	font-style: italic;
`;

export const articleBoldItalic17 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.4;
	font-weight: 700;
	font-style: italic;
`;

export const articleItalic15 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.4;
	font-weight: 400;
	font-style: italic;
`;

export const articleItalic17 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.4;
	font-weight: 400;
	font-style: italic;
`;

export const headlineBold14 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold17 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold20 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold24 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold28 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold34 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold42 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold50 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineBold70 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const headlineLight14 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight17 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight20 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight24 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight28 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight34 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight42 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight50 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLight70 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: normal;
`;

export const headlineLightItalic14 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic17 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic20 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic24 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic28 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic34 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic42 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic50 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineLightItalic70 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 300;
	font-style: italic;
`;

export const headlineMedium14 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium17 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium20 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium24 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium28 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium34 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium42 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium50 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMedium70 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: normal;
`;

export const headlineMediumItalic14 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic17 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic20 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic24 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic28 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.75rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic34 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic42 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic50 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 500;
	font-style: italic;
`;

export const headlineMediumItalic70 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: italic;
`;

export const kicker14 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const kicker17 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const kicker20 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.25rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const kicker24 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 1.5rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const kicker34 = `
	font-family: "GH Guardian Headline", "Guardian Egyptian Web", Georgia, serif;
	font-size: 2.125rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const textEgyptian14 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textEgyptian15 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textEgyptian17 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textEgyptianBold14 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textEgyptianBold15 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textEgyptianBold17 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textEgyptianBoldItalic14 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: italic;
`;

export const textEgyptianBoldItalic15 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: italic;
`;

export const textEgyptianBoldItalic17 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: italic;
`;

export const textEgyptianItalic14 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textEgyptianItalic15 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textEgyptianItalic17 = `
	font-family: GuardianTextEgyptian, "Guardian Text Egyptian Web", Georgia, serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSans12 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.75rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans14 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans15 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans17 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans20 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.25rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans24 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.5rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans28 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.75rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSans34 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 2.125rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: normal;
`;

export const textSansBold12 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.75rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold14 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold15 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold17 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold20 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.25rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold24 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.5rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold28 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.75rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansBold34 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 2.125rem;
	line-height: 1.3;
	font-weight: 700;
	font-style: normal;
`;

export const textSansItalic12 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.75rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic14 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.875rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: Italic;
`;

export const textSansItalic15 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 0.9375rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic17 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.0625rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic20 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.25rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic24 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.5rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic28 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 1.75rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const textSansItalic34 = `
	font-family: GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	font-size: 2.125rem;
	line-height: 1.3;
	font-weight: 400;
	font-style: italic;
`;

export const titlepiece42 = `
	font-family: "GT Guardian Titlepiece", Georgia, serif;
	font-size: 2.625rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const titlepiece50 = `
	font-family: "GT Guardian Titlepiece", Georgia, serif;
	font-size: 3.125rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;

export const titlepiece70 = `
	font-family: "GT Guardian Titlepiece", Georgia, serif;
	font-size: 4.375rem;
	line-height: 1.15;
	font-weight: 700;
	font-style: normal;
`;
