export const labels: Record<string, string> = {
	'alarm-clock-filled': 'Alarm',
	'alarm-clock-outlined': 'Alarm',
	'alarm-clock-sounded': 'Alarm sounded',
	'alert-phone': 'Mobile phone with exclamation mark',
	'alert-round': 'Warning',
	'alert-triangle': 'Warning',
	'apple-brand': 'Apple logo',
	'arrow-contract': 'Collapse',
	'arrow-down-straight': 'Arrow down',
	'arrow-expand': 'Expand',
	'arrow-left-straight': 'Arrow left',
	'arrow-outdent': 'Up left arrow',
	'arrow-pop-out': 'Pop out',
	'arrow-right-straight': 'Arrow right',
	'arrow-scroll': 'Scroll content',
	'arrow-up-and-down-small': 'Up and down arrow',
	'arrow-up-straight': 'Arrow up',
	'arrow-up-straight-small': 'Arrow up',
	asterisk: 'Asterisk',
	audio: 'Audio',
	'audio-mute': 'Sound off',
	bin: 'Delete',
	'book-outlined': 'Book credit',
	'bookmark-cross': 'Remove bookmark',
	'bookmark-filled': 'Bookmarked',
	'bookmark-outlined': 'Bookmark',
	'bookmark-round-filled': 'Bookmarked',
	'bookmark-round-outlined': 'Bookmark',
	calendar: 'Calendar',
	camera: 'Camera',
	'camera-round-outlined': 'Camera',
	'camera-small': 'Camera',
	checkmark: 'Checkmark',
	'chevron-down-double': 'Double chevron down',
	'chevron-down-single': 'Expand to show more',
	'chevron-down-single-small': 'Expand',
	'chevron-down-single-xsmall': 'Expand to show more',
	'chevron-left-double': 'Double chevron left',
	'chevron-left-single': 'Chevron left',
	'chevron-left-small': 'Chevron left',
	'chevron-right-double': 'Double chevron right',
	'chevron-right-single': 'Chevron right',
	'chevron-right-small': 'Chevron right',
	'chevron-up-and-down-small': 'Sort',
	'chevron-up-double': 'Double chevron up',
	'chevron-up-single': 'Collapse to show less',
	'chevron-up-single-small': 'Collapse',
	clock: 'Clock',
	'clock-baseline-small': 'Clock',
	'credit-card': 'Credit card',
	cross: 'Close',
	'cross-round-filled': 'Close',
	'cross-round-outlined': 'Close',
	'cross-small': 'Close',
	'crossed-out-cloud': 'No WiFi',
	crosswords: 'Crosswords',
	'direct-debit': 'Direct Debit logo',
	'direct-debit-wide': 'Direct Debit logo',
	document: 'Document',
	download: 'Download',
	'drag-handle': 'Drag',
	edit: 'Edit',
	ellipsis: 'More',
	envelope: 'Email',
	exclamation: 'Exclamation mark',
	external: 'External link',
	eye: 'View',
	'eye-strike': 'Not visible',
	facebook: 'Facebook logo',
	'facebook-brand': 'Facebook logo',
	'facebook-messenger': 'Facebook Messenger logo',
	filter: 'Filter',
	'filter-android-app': 'Filter',
	'filter-android-app-small': 'Filter',
	'filter-ios-app': 'Filter',
	'filter-ios-app-small': 'Filter',
	'filter-outlined-web': 'Filter',
	gift: 'Gift',
	globe: 'Globe',
	'google-brand': 'Google logo',
	gps: 'Location',
	'hand-pointed': 'Interactive',
	'headphones-filled': 'Listening',
	'headphones-outlined': 'Listen',
	'headphones-round-filled': 'Listening',
	'headphones-round-outlined': 'Listen',
	'home-house-filled': 'Home',
	'home-house-outlined': 'Home',
	'home-square-filled': 'Home',
	'home-square-outlined': 'Home',
	'house-cross': 'Remove from home',
	'house-plus': 'Add to home',
	'house-setting': 'Settings',
	indent: 'Indent',
	'info-round': 'Information',
	'ingredient-1': 'Ingredient',
	'ingredient-2': 'Ingredient',
	'ingredient-3': 'Ingredient',
	'knife-and-fork': 'Serving',
	'linked-in': 'LinkedIn logo',
	list: 'List',
	'location-marker': 'Location',
	'magnifying-glass': 'Search',
	'magnifying-glass-minus': 'Zoom out',
	'magnifying-glass-plus': 'Zoom in',
	'magnifying-glass-sad-face': 'No results',
	'media-controls-back': 'Rewind',
	'media-controls-forward': 'Fast forward',
	'media-controls-pause': 'Pause',
	'media-controls-play': 'Stop',
	'media-controls-stop': 'Play',
	menu: 'Menu',
	message: 'Message',
	'message-round': 'Message',
	minus: 'Minus sign',
	moon: 'Dark mode',
	newsletter: 'Newsletter',
	'newspaper-archive': 'Newspaper archive',
	'note-filled': 'Note',
	'note-outlined': 'Note',
	'notifications-off': 'Notification off',
	'notifications-off-round': 'Notification off',
	'notifications-on': 'Notification on',
	'notifications-on-round': 'Notification on',
	padlock: 'Lock',
	'party-of-three': 'Share',
	'party-popper-filled': 'Celebration',
	'party-popper-outlined': 'Celebration',
	'pay-pal-brand': 'PayPal logo',
	person: 'Account',
	'person-cross': 'Remove user',
	'person-plus': 'Add user',
	'person-round-filled': 'Account, profile',
	'person-round-outlined': 'Account, profile',
	'person-tick': 'Verified user',
	phone: 'Mobile phone',
	pinned: 'Pinned',
	pinterest: 'Pinterest logo',
	plus: 'Plus sign',
	'plus-on-round': 'Add',
	quote: 'Quote',
	reload: 'Reload',
	settings: 'Settings',
	'share-app': 'Share',
	'share-app-small': 'Share',
	'share-callout': 'Share callout',
	'share-round-filled': 'Share active',
	'share-round-outline': 'Share',
	'share-web': 'Share',
	'signal-brand': 'Signal logo',
	sort: 'Sort',
	'speech-bubble': 'Comments',
	'speech-bubble-cross': 'Remove comment',
	'speech-bubble-plus': 'Add comment',
	star: 'Star',
	'star-outline': 'Star outline',
	'telegram-brand': 'Telegram logo',
	'text-large': 'Large text',
	'text-size': 'Text size',
	'text-size-round-filled': 'Text size active',
	'text-size-round-outline': 'Text size',
	'text-small': 'Small text',
	'tick-round': 'Ticked',
	timer: 'Timer',
	'transparent-arrow-left-straight-round': 'Go back',
	twitter: 'Twitter logo',
	upload: 'Upload',
	video: 'Video',
	'whats-app': 'WhatsApp logo',
	'whats-app-brand': 'WhatsApp logo',
};
