import { tokens } from '@guardian/design-tokens';
import { fontArrayToString } from '../src/utils/convert-value';

const { presets } = tokens.typography;

console.log('Building typography presets.\n');

let output = `
	// Typography presets
	// Auto-generated by scripts/build-type-presets.ts
	// DO NOT EDIT'
`;

for (const [preset, properties] of Object.entries(presets)) {
	output += `
		export const ${preset} = \`
		  font-family: ${fontArrayToString(properties.fontFamily)};
		  font-size: ${properties.fontSize};
		  line-height: ${properties.lineHeight};
		  font-weight: ${properties.fontWeight};
		  font-style: ${properties.fontStyle};
		\`;
	`;
}

console.log(output);
