import fs from 'node:fs';
import prettierConfig from '@guardian/prettier';
import { format } from 'prettier';
import { tokens } from '@guardian/design-tokens';
import { fontArrayToString } from '../src/utils/convert-value';

const { presets } = tokens.typography;

const presetOutputPath = `${process.cwd()}/src/typography/presets.ts`;

let output = `
	// Typography presets
	// Auto-generated by scripts/build-type-presets.ts
	// DO NOT EDIT
`;

for (const [preset, properties] of Object.entries(presets)) {
	output += `
		export const ${preset} = \`
			font-family: ${fontArrayToString(properties.fontFamily)};
			font-size: ${properties.fontSize};
			line-height: ${properties.lineHeight};
			font-weight: ${properties.fontWeight};
			font-style: ${properties.fontStyle};
		\`;
	`;
}

console.log('Writing typography presets.');

(async () => {
	const formattedOutput = await format(output, {
		parser: 'typescript',
		...prettierConfig,
	});
	fs.writeFileSync(presetOutputPath, formattedOutput);
})();
