import fs from 'node:fs';
import { typography, typographyPresets } from '@guardian/design-tokens';
import prettierConfig from '@guardian/prettier';
import { format } from 'prettier';
import { fontArrayToString, pxStringToRem } from '../src/utils/convert-value';

const STRIP_WHITESPACE = /^\s+/gm;
const STRIP_TABS = /^\t{3}|\t{2}/gm;

const { fontSize, textDecorationThicknessForFontSize } = typography;

type FontSize = keyof typeof fontSize;

const textDecorationThickness = (size: string) =>
	textDecorationThicknessForFontSize[size.slice(0, -2) as FontSize];

console.log('Building typography presets…');

const presetTotal = Object.keys(typographyPresets).length;

const outputPath = `${process.cwd()}/src/__generated__/typography`;
fs.mkdirSync(outputPath, { recursive: true });

const cssOutputPath = `${outputPath}/css.ts`;
const objectOutputPath = `${outputPath}/objects.ts`;

const banner = `
	// Typography presets
	// Auto-generated by scripts/build-type-presets.ts
	// DO NOT EDIT
`.replace(STRIP_WHITESPACE, '');

// Generate CSS representation of presets as a string
const css = Object.entries(typographyPresets)
	.map(
		([preset, properties]) => `
			export const ${preset} = \`
				font-family: ${fontArrayToString(properties.fontFamily)};
				font-size: ${pxStringToRem(properties.fontSize)}rem;
				line-height: ${properties.lineHeight};
				font-weight: ${properties.fontWeight};
				font-style: ${properties.fontStyle};
				--source-text-decoration-thickness: ${textDecorationThickness(properties.fontSize)};
			\`;
		`,
	)
	.join('')
	.replace(STRIP_TABS, '');

// Generate object literal representation of presets
const object = Object.entries(typographyPresets)
	.map(
		([preset, properties]) => `
			export const ${preset}Object = {
				fontFamily: '${fontArrayToString(properties.fontFamily)}',
				fontSize: '${pxStringToRem(properties.fontSize)}rem',
				lineHeight: ${properties.lineHeight},
				fontWeight: ${properties.fontWeight},
				fontStyle: '${properties.fontStyle}',
			} as const;
		`,
	)
	.join('')
	.replace(STRIP_TABS, '');

void (async () => {
	fs.writeFileSync(
		cssOutputPath,
		await format(banner + css, { filepath: cssOutputPath, ...prettierConfig }),
	);
	fs.writeFileSync(
		objectOutputPath,
		await format(banner + object, {
			filepath: objectOutputPath,
			...prettierConfig,
		}),
	);
	console.log(`✓ ${presetTotal} presets built`);
})();
