import type { CAPICrossword } from '../@types/CAPI';

export const cryptic: CAPICrossword = {
	id: 'crosswords/cryptic/29528',
	number: 29528,
	name: 'Cryptic crossword No 29,528',
	creator: {
		name: 'Brockwell',
		webUrl: 'https://www.theguardian.com/profile/brockwell',
	},
	date: 1730332800000,
	webPublicationDate: 1730332802000,
	entries: [
		{
			id: '7-across',
			number: 7,
			humanNumber: '7',
			clue: 'Optimistic, like male of 17ac? (7)',
			direction: 'across',
			length: 7,
			group: ['7-across'],
			position: {
				x: 0,
				y: 1,
			},
			separatorLocations: {},
			solution: 'BULLISH',
		},
		{
			id: '8-across',
			number: 8,
			humanNumber: '8',
			clue: 'Writer in retreat welcomed by fat cat (7)',
			direction: 'across',
			length: 7,
			group: ['8-across'],
			position: {
				x: 8,
				y: 1,
			},
			separatorLocations: {},
			solution: 'LEOPARD',
		},
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: 'Eagle not the last for Gary Player? (4)',
			direction: 'across',
			length: 4,
			group: ['9-across'],
			position: {
				x: 0,
				y: 3,
			},
			separatorLocations: {},
			solution: 'HARP',
		},
		{
			id: '10-across',
			number: 10,
			humanNumber: '10',
			clue: 'Heavy defeat at home by City, as per usual (9)',
			direction: 'across',
			length: 9,
			group: ['10-across'],
			position: {
				x: 5,
				y: 3,
			},
			separatorLocations: {},
			solution: 'ROUTINELY',
		},
		{
			id: '12-across',
			number: 12,
			humanNumber: '12',
			clue: 'Ridiculous record by 17ac (5)',
			direction: 'across',
			length: 5,
			group: ['12-across'],
			position: {
				x: 1,
				y: 5,
			},
			separatorLocations: {},
			solution: 'CRAZY',
		},
		{
			id: '13-across',
			number: 13,
			humanNumber: '13',
			clue: 'Life’s in a mess for 17ac (8)',
			direction: 'across',
			length: 8,
			group: ['13-across'],
			position: {
				x: 7,
				y: 5,
			},
			separatorLocations: {},
			solution: 'FINALISE',
		},
		{
			id: '15-across',
			number: 15,
			humanNumber: '15',
			clue: 'Bed broken by adult film (4)',
			direction: 'across',
			length: 4,
			group: ['15-across'],
			position: {
				x: 0,
				y: 7,
			},
			separatorLocations: {},
			solution: 'COAT',
		},
		{
			id: '16-across',
			number: 16,
			humanNumber: '16',
			clue: 'Peer tackling drip in toilet (5)',
			direction: 'across',
			length: 5,
			group: ['16-across'],
			position: {
				x: 5,
				y: 7,
			},
			separatorLocations: {},
			solution: 'PRIVY',
		},
		{
			id: '17-across',
			number: 17,
			humanNumber: '17',
			clue: 'Swimmer occasionally ill at ease doing backstroke? (4)',
			direction: 'across',
			length: 4,
			group: ['17-across'],
			position: {
				x: 11,
				y: 7,
			},
			separatorLocations: {},
			solution: 'SEAL',
		},
		{
			id: '18-across',
			number: 18,
			humanNumber: '18',
			clue: 'Unlimited plums to take on again (2-6)',
			direction: 'across',
			length: 8,
			group: ['18-across'],
			position: {
				x: 0,
				y: 9,
			},
			separatorLocations: {
				'-': [2],
			},
			solution: 'REENGAGE',
		},
		{
			id: '20-across',
			number: 20,
			humanNumber: '20',
			clue: 'Gang member bored by opening of Magic Flute (5)',
			direction: 'across',
			length: 5,
			group: ['20-across'],
			position: {
				x: 9,
				y: 9,
			},
			separatorLocations: {},
			solution: 'CRIMP',
		},
		{
			id: '21-across',
			number: 21,
			humanNumber: '21',
			clue: 'Cabaret dancing queen is 17ac (4-5)',
			direction: 'across',
			length: 9,
			group: ['21-across'],
			position: {
				x: 1,
				y: 11,
			},
			separatorLocations: {
				'-': [4],
			},
			solution: 'CRABEATER',
		},
		{
			id: '22-across',
			number: 22,
			humanNumber: '22',
			clue: 'Brother working within revolutionary unit (4)',
			direction: 'across',
			length: 4,
			group: ['22-across'],
			position: {
				x: 11,
				y: 11,
			},
			separatorLocations: {},
			solution: 'MONK',
		},
		{
			id: '24-across',
			number: 24,
			humanNumber: '24',
			clue: 'British artist coming back in time to entertain (7)',
			direction: 'across',
			length: 7,
			group: ['24-across'],
			position: {
				x: 0,
				y: 13,
			},
			separatorLocations: {},
			solution: 'HARBOUR',
		},
		{
			id: '25-across',
			number: 25,
			humanNumber: '25',
			clue: 'Female virtue cracked secret (7)',
			direction: 'across',
			length: 7,
			group: ['25-across'],
			position: {
				x: 8,
				y: 13,
			},
			separatorLocations: {},
			solution: 'FURTIVE',
		},
		{
			id: '1-down',
			number: 1,
			humanNumber: '1',
			clue: 'Young adult in passive stage (4)',
			direction: 'down',
			length: 4,
			group: ['1-down'],
			position: {
				x: 1,
				y: 0,
			},
			separatorLocations: {},
			solution: 'PUPA',
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2',
			clue: 'Footballer on the up – hard worker and big beast! (8)',
			direction: 'down',
			length: 8,
			group: ['2-down'],
			position: {
				x: 3,
				y: 0,
			},
			separatorLocations: {},
			solution: 'ELEPHANT',
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'Husband leaving smoking pot in a lost state (6)',
			direction: 'down',
			length: 6,
			group: ['3-down'],
			position: {
				x: 5,
				y: 0,
			},
			separatorLocations: {},
			solution: 'ASTRAY',
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: 'Communist country’s borders admitting drug tolerance (8)',
			direction: 'down',
			length: 8,
			group: ['4-down'],
			position: {
				x: 9,
				y: 0,
			},
			separatorLocations: {},
			solution: 'LENIENCY',
		},
		{
			id: '5-down',
			number: 5,
			humanNumber: '5',
			clue: '“Howzat” call from Lyon saving Australia (6)',
			direction: 'down',
			length: 6,
			group: ['5-down'],
			position: {
				x: 11,
				y: 0,
			},
			separatorLocations: {},
			solution: 'APPEAL',
		},
		{
			id: '6-down',
			number: 6,
			humanNumber: '6',
			clue: 'Old nag (4)',
			direction: 'down',
			length: 4,
			group: ['6-down'],
			position: {
				x: 13,
				y: 0,
			},
			separatorLocations: {},
			solution: 'GREY',
		},
		{
			id: '11-down',
			number: 11,
			humanNumber: '11',
			clue: 'Most partisan United fan whipped up anger on street (9)',
			direction: 'down',
			length: 9,
			group: ['11-down'],
			position: {
				x: 7,
				y: 3,
			},
			separatorLocations: {},
			solution: 'UNFAIREST',
		},
		{
			id: '12-down',
			number: 12,
			humanNumber: '12',
			clue: 'Charlie to get away from 17ac (5)',
			direction: 'down',
			length: 5,
			group: ['12-down'],
			position: {
				x: 1,
				y: 5,
			},
			separatorLocations: {},
			solution: 'CLOSE',
		},
		{
			id: '14-down',
			number: 14,
			humanNumber: '14',
			clue: 'Mark regularly using satnav maps (5)',
			direction: 'down',
			length: 5,
			group: ['14-down'],
			position: {
				x: 13,
				y: 5,
			},
			separatorLocations: {},
			solution: 'STAMP',
		},
		{
			id: '16-down',
			number: 16,
			humanNumber: '16',
			clue: 'Sleepy dictator’s gun loaded (8)',
			direction: 'down',
			length: 8,
			group: ['16-down'],
			position: {
				x: 5,
				y: 7,
			},
			separatorLocations: {},
			solution: 'PEACEFUL',
		},
		{
			id: '17-down',
			number: 17,
			humanNumber: '17',
			clue: 'Square couple holding joint for fellow traveller (8)',
			direction: 'down',
			length: 8,
			group: ['17-down'],
			position: {
				x: 11,
				y: 7,
			},
			separatorLocations: {},
			solution: 'SHIPMATE',
		},
		{
			id: '19-down',
			number: 19,
			humanNumber: '19',
			clue: 'Barney Rubble is 12dn (6)',
			direction: 'down',
			length: 6,
			group: ['19-down'],
			position: {
				x: 3,
				y: 9,
			},
			separatorLocations: {},
			solution: 'NEARBY',
		},
		{
			id: '20-down',
			number: 20,
			humanNumber: '20',
			clue: 'Show around a lost American (6)',
			direction: 'down',
			length: 6,
			group: ['20-down'],
			position: {
				x: 9,
				y: 9,
			},
			separatorLocations: {},
			solution: 'CIRCUS',
		},
		{
			id: '21-down',
			number: 21,
			humanNumber: '21',
			clue: 'Crack and heroin smuggled by 17ac (4)',
			direction: 'down',
			length: 4,
			group: ['21-down'],
			position: {
				x: 1,
				y: 11,
			},
			separatorLocations: {},
			solution: 'CHAP',
		},
		{
			id: '23-down',
			number: 23,
			humanNumber: '23',
			clue: 'Blue, like stilton supplied by Spooner (4)',
			direction: 'down',
			length: 4,
			group: ['23-down'],
			position: {
				x: 13,
				y: 11,
			},
			separatorLocations: {},
			solution: 'NAVY',
		},
	],
	solutionAvailable: true,
	dateSolutionAvailable: 1730332800000,
	dimensions: {
		cols: 15,
		rows: 15,
	},
	crosswordType: 'cryptic',
	pdf: 'https://crosswords-static.guim.co.uk/gdn.cryptic.20241031.pdf',
};
