import type { CrosswordData } from '../@types/crossword';

export const prize: CrosswordData = {
	id: 'crosswords/prize/29524',
	number: 29524,
	name: 'Prize crossword No 29,524',
	creator: {
		name: 'Brummie',
		webUrl: 'https://www.theguardian.com/profile/brummie',
	},
	date: 1729900800000,
	webPublicationDate: 1729897217000,
	entries: [
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: 'Rod’s rude attention-seeker (5)',
			direction: 'across',
			length: 5,
			group: ['9-across'],
			position: {
				x: 0,
				y: 1,
			},
			separatorLocations: {},
		},
		{
			id: '10-across',
			number: 10,
			humanNumber: '10',
			clue: 'Sally crosses stage, as a form of casting (9)',
			direction: 'across',
			length: 9,
			group: ['10-across'],
			position: {
				x: 6,
				y: 1,
			},
			separatorLocations: {},
		},
		{
			id: '11-across',
			number: 11,
			humanNumber: '11',
			clue: 'Heading action needed by the one in possession? (5,4)',
			direction: 'across',
			length: 9,
			group: ['11-across'],
			position: {
				x: 0,
				y: 3,
			},
			separatorLocations: {
				',': [5],
			},
		},
		{
			id: '12-across',
			number: 12,
			humanNumber: '12',
			clue: 'Recruit turned Lone Ranger’s head (5)',
			direction: 'across',
			length: 5,
			group: ['12-across'],
			position: {
				x: 10,
				y: 3,
			},
			separatorLocations: {},
		},
		{
			id: '13-across',
			number: 13,
			humanNumber: '13',
			clue: 'African republic imprisons a church prophet (7)',
			direction: 'across',
			length: 7,
			group: ['13-across'],
			position: {
				x: 0,
				y: 5,
			},
			separatorLocations: {},
		},
		{
			id: '15-across',
			number: 15,
			humanNumber: '15',
			clue: 'Guardian pursuing lost sheep arrives at old city (7)',
			direction: 'across',
			length: 7,
			group: ['15-across'],
			position: {
				x: 8,
				y: 5,
			},
			separatorLocations: {},
		},
		{
			id: '17-across',
			number: 17,
			humanNumber: '17',
			clue: 'US city’s on about ‘optical device’ (5)',
			direction: 'across',
			length: 5,
			group: ['17-across'],
			position: {
				x: 0,
				y: 7,
			},
			separatorLocations: {},
		},
		{
			id: '18-across',
			number: 18,
			humanNumber: '18',
			clue: 'Briefly against disposing of a machine separating fibre (3)',
			direction: 'across',
			length: 3,
			group: ['18-across'],
			position: {
				x: 6,
				y: 7,
			},
			separatorLocations: {},
		},
		{
			id: '20-across',
			number: 20,
			humanNumber: '20',
			clue: 'Oscar winner’s debut lied about? (5)',
			direction: 'across',
			length: 5,
			group: ['20-across'],
			position: {
				x: 10,
				y: 7,
			},
			separatorLocations: {},
		},
		{
			id: '22-across',
			number: 22,
			humanNumber: '22',
			clue: 'Right to leave a free-for-all sale (7)',
			direction: 'across',
			length: 7,
			group: ['22-across'],
			position: {
				x: 0,
				y: 9,
			},
			separatorLocations: {},
		},
		{
			id: '25-across',
			number: 25,
			humanNumber: '25',
			clue: 'Pressure one’s briefly put at centre of ancient monument (7)',
			direction: 'across',
			length: 7,
			group: ['25-across'],
			position: {
				x: 8,
				y: 9,
			},
			separatorLocations: {},
		},
		{
			id: '26-across',
			number: 26,
			humanNumber: '26',
			clue: 'Liverpudlian ejecting college drunkard (5)',
			direction: 'across',
			length: 5,
			group: ['26-across'],
			position: {
				x: 0,
				y: 11,
			},
			separatorLocations: {},
		},
		{
			id: '27-across',
			number: 27,
			humanNumber: '27',
			clue: 'Sparkler? Patience! (9)',
			direction: 'across',
			length: 9,
			group: ['27-across'],
			position: {
				x: 6,
				y: 11,
			},
			separatorLocations: {},
		},
		{
			id: '30-across',
			number: 30,
			humanNumber: '30',
			clue: 'Drama about oil spill trapping large protected mammal (9)',
			direction: 'across',
			length: 9,
			group: ['30-across'],
			position: {
				x: 0,
				y: 13,
			},
			separatorLocations: {},
		},
		{
			id: '31-across',
			number: 31,
			humanNumber: '31',
			clue: 'Beloved pasta sauce’s back (5)',
			direction: 'across',
			length: 5,
			group: ['31-across'],
			position: {
				x: 10,
				y: 13,
			},
			separatorLocations: {},
		},
		{
			id: '1-down',
			number: 1,
			humanNumber: '1',
			clue: 'Ends up as Chesil Beach, say (4)',
			direction: 'down',
			length: 4,
			group: ['1-down'],
			position: {
				x: 0,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2',
			clue: 'Burlesque? Let’s change game (8)',
			direction: 'down',
			length: 8,
			group: ['2-down'],
			position: {
				x: 2,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'Charge round roof entrance on the house (4)',
			direction: 'down',
			length: 4,
			group: ['3-down'],
			position: {
				x: 4,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: 'Conducting upbeat intro with female band (8)',
			direction: 'down',
			length: 8,
			group: ['4-down'],
			position: {
				x: 6,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '5-down',
			number: 5,
			humanNumber: '5',
			clue: 'Join lamb’s rump and hog’s back (6)',
			direction: 'down',
			length: 6,
			group: ['5-down'],
			position: {
				x: 8,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '6-down',
			number: 6,
			humanNumber: '6',
			clue: 'Ex-president one almost wishes would get thrashed in early Republican primaries (10)',
			direction: 'down',
			length: 10,
			group: ['6-down'],
			position: {
				x: 10,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '7-down',
			number: 7,
			humanNumber: '7',
			clue: 'Tries to take in top of tight suit (6)',
			direction: 'down',
			length: 6,
			group: ['7-down'],
			position: {
				x: 12,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '8-down',
			number: 8,
			humanNumber: '8',
			clue: 'Sounds like market in which to spend time (4)',
			direction: 'down',
			length: 4,
			group: ['8-down'],
			position: {
				x: 14,
				y: 0,
			},
			separatorLocations: {},
		},
		{
			id: '13-down',
			number: 13,
			humanNumber: '13',
			clue: 'Spirit associated with a Mediterranean island (5)',
			direction: 'down',
			length: 5,
			group: ['13-down'],
			position: {
				x: 0,
				y: 5,
			},
			separatorLocations: {},
		},
		{
			id: '14-down',
			number: 14,
			humanNumber: '14',
			clue: 'Dynamic recording has a number of errors to be fixed (10)',
			direction: 'down',
			length: 10,
			group: ['14-down'],
			position: {
				x: 4,
				y: 5,
			},
			separatorLocations: {},
		},
		{
			id: '16-down',
			number: 16,
			humanNumber: '16',
			clue: 'Sun made water race (5)',
			direction: 'down',
			length: 5,
			group: ['16-down'],
			position: {
				x: 14,
				y: 5,
			},
			separatorLocations: {},
		},
		{
			id: '19-down',
			number: 19,
			humanNumber: '19',
			clue: 'Kip has ball with Trotsky, military commander (8)',
			direction: 'down',
			length: 8,
			group: ['19-down'],
			position: {
				x: 8,
				y: 7,
			},
			separatorLocations: {},
		},
		{
			id: '21-down',
			number: 21,
			humanNumber: '21',
			clue: 'Doctor mingles with male unthinking followers (8)',
			direction: 'down',
			length: 8,
			group: ['21-down'],
			position: {
				x: 12,
				y: 7,
			},
			separatorLocations: {},
		},
		{
			id: '23-down',
			number: 23,
			humanNumber: '23',
			clue: 'Cold drink? Well, that’s pretty bad (6)',
			direction: 'down',
			length: 6,
			group: ['23-down'],
			position: {
				x: 2,
				y: 9,
			},
			separatorLocations: {},
		},
		{
			id: '24-down',
			number: 24,
			humanNumber: '24',
			clue: 'Finest leasehold houses to be in sheltered position (6)',
			direction: 'down',
			length: 6,
			group: ['24-down'],
			position: {
				x: 6,
				y: 9,
			},
			separatorLocations: {},
		},
		{
			id: '26-down',
			number: 26,
			humanNumber: '26',
			clue: 'I have an exact match for that photo (4)',
			direction: 'down',
			length: 4,
			group: ['26-down'],
			position: {
				x: 0,
				y: 11,
			},
			separatorLocations: {},
		},
		{
			id: '28-down',
			number: 28,
			humanNumber: '28',
			clue: 'Silly talk needs to be quiet (4)',
			direction: 'down',
			length: 4,
			group: ['28-down'],
			position: {
				x: 10,
				y: 11,
			},
			separatorLocations: {},
		},
		{
			id: '29-down',
			number: 29,
			humanNumber: '29',
			clue: 'Pound, the last to be deposited in time (4)',
			direction: 'down',
			length: 4,
			group: ['29-down'],
			position: {
				x: 14,
				y: 11,
			},
			separatorLocations: {},
		},
	],
	solutionAvailable: false,
	dateSolutionAvailable: 1730505600000,
	dimensions: {
		cols: 15,
		rows: 15,
	},
	crosswordType: 'prize',
	pdf: 'https://crosswords-static.guim.co.uk/gdn.cryptic.20241026.pdf',
};
