import type { CrosswordData } from '../@types/crossword';

export const quick: CrosswordData = {
	id: 'crosswords/quick/17001',
	number: 17001,
	name: 'Quick crossword No 17,001',
	date: 1730332800000,
	webPublicationDate: 1730332803000,
	entries: [
		{
			id: '5-across',
			number: 5,
			humanNumber: '5',
			clue: 'Bane (4,5)',
			direction: 'across',
			length: 9,
			group: ['5-across'],
			position: {
				x: 2,
				y: 1,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'BETENOIRE',
		},
		{
			id: '8-across',
			number: 8,
			humanNumber: '8',
			clue: 'Fish-hook’s business end (4)',
			direction: 'across',
			length: 4,
			group: ['8-across'],
			position: {
				x: 0,
				y: 3,
			},
			separatorLocations: {},
			solution: 'BARB',
		},
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: 'Line created by rising and falling water (8)',
			direction: 'across',
			length: 8,
			group: ['9-across'],
			position: {
				x: 5,
				y: 3,
			},
			separatorLocations: {},
			solution: 'TIDEMARK',
		},
		{
			id: '10-across',
			number: 10,
			humanNumber: '10',
			clue: 'Bold (6)',
			direction: 'across',
			length: 6,
			group: ['10-across'],
			position: {
				x: 0,
				y: 5,
			},
			separatorLocations: {},
			solution: 'CHEEKY',
		},
		{
			id: '11-across',
			number: 11,
			humanNumber: '11',
			clue: 'Contraption (6)',
			direction: 'across',
			length: 6,
			group: ['11-across'],
			position: {
				x: 7,
				y: 5,
			},
			separatorLocations: {},
			solution: 'GADGET',
		},
		{
			id: '13-across',
			number: 13,
			humanNumber: '13',
			clue: 'Go quickly (up?) (6)',
			direction: 'across',
			length: 6,
			group: ['13-across'],
			position: {
				x: 0,
				y: 7,
			},
			separatorLocations: {},
			solution: 'ROCKET',
		},
		{
			id: '15-across',
			number: 15,
			humanNumber: '15',
			clue: 'Gusto (6)',
			direction: 'across',
			length: 6,
			group: ['15-across'],
			position: {
				x: 7,
				y: 7,
			},
			separatorLocations: {},
			solution: 'VIGOUR',
		},
		{
			id: '16-across',
			number: 16,
			humanNumber: '16',
			clue: '1,000,000,000,000 (8)',
			direction: 'across',
			length: 8,
			group: ['16-across'],
			position: {
				x: 0,
				y: 9,
			},
			separatorLocations: {},
			solution: 'TRILLION',
		},
		{
			id: '18-across',
			number: 18,
			humanNumber: '18',
			clue: 'Swain (4)',
			direction: 'across',
			length: 4,
			group: ['18-across'],
			position: {
				x: 9,
				y: 9,
			},
			separatorLocations: {},
			solution: 'BEAU',
		},
		{
			id: '19-across',
			number: 19,
			humanNumber: '19',
			clue: 'Procession of vehicles carrying politicians, e.g. (9)',
			direction: 'across',
			length: 9,
			group: ['19-across'],
			position: {
				x: 2,
				y: 11,
			},
			separatorLocations: {},
			solution: 'MOTORCADE',
		},
		{
			id: '1-down',
			number: 1,
			humanNumber: '1',
			clue: 'Time for a quick cuppa (3,5)',
			direction: 'down',
			length: 8,
			group: ['1-down'],
			position: {
				x: 3,
				y: 0,
			},
			separatorLocations: {
				',': [3],
			},
			solution: 'TEABREAK',
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2',
			clue: 'Room for clergy’s robes (6)',
			direction: 'down',
			length: 6,
			group: ['2-down'],
			position: {
				x: 5,
				y: 0,
			},
			separatorLocations: {},
			solution: 'VESTRY',
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'Meaty snack sometimes served with mustard (3,3)',
			direction: 'down',
			length: 6,
			group: ['3-down'],
			position: {
				x: 7,
				y: 0,
			},
			separatorLocations: {
				',': [3],
			},
			solution: 'HOTDOG',
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: 'Fill (4)',
			direction: 'down',
			length: 4,
			group: ['4-down'],
			position: {
				x: 9,
				y: 0,
			},
			separatorLocations: {},
			solution: 'CRAM',
		},
		{
			id: '6-down',
			number: 6,
			humanNumber: '6',
			clue: 'Where speedo found (9)',
			direction: 'down',
			length: 9,
			group: ['6-down'],
			position: {
				x: 1,
				y: 2,
			},
			separatorLocations: {},
			solution: 'DASHBOARD',
		},
		{
			id: '7-down',
			number: 7,
			humanNumber: '7',
			clue: 'Fluctuating (9)',
			direction: 'down',
			length: 9,
			group: ['7-down'],
			position: {
				x: 11,
				y: 2,
			},
			separatorLocations: {},
			solution: 'IRREGULAR',
		},
		{
			id: '12-down',
			number: 12,
			humanNumber: '12',
			clue: 'Drudge (8)',
			direction: 'down',
			length: 8,
			group: ['12-down'],
			position: {
				x: 9,
				y: 5,
			},
			separatorLocations: {},
			solution: 'DOGSBODY',
		},
		{
			id: '14-down',
			number: 14,
			humanNumber: '14',
			clue: 'Camera holder (6)',
			direction: 'down',
			length: 6,
			group: ['14-down'],
			position: {
				x: 5,
				y: 7,
			},
			separatorLocations: {},
			solution: 'TRIPOD',
		},
		{
			id: '15-down',
			number: 15,
			humanNumber: '15',
			clue: 'Italian city with cultural festival La Biennale (6)',
			direction: 'down',
			length: 6,
			group: ['15-down'],
			position: {
				x: 7,
				y: 7,
			},
			separatorLocations: {},
			solution: 'VENICE',
		},
		{
			id: '17-down',
			number: 17,
			humanNumber: '17',
			clue: 'Big cat (4)',
			direction: 'down',
			length: 4,
			group: ['17-down'],
			position: {
				x: 3,
				y: 9,
			},
			separatorLocations: {},
			solution: 'LION',
		},
	],
	solutionAvailable: true,
	dateSolutionAvailable: 1730332800000,
	dimensions: {
		cols: 13,
		rows: 13,
	},
	crosswordType: 'quick',
	pdf: 'https://crosswords-static.guim.co.uk/gdn.quick.20241031.pdf',
};
