import type { CrosswordData } from '../@types/crossword';

export const quiptic: CrosswordData = {
	id: 'crosswords/quiptic/1301',
	number: 1301,
	name: 'Quiptic crossword No 1,301',
	creator: {
		name: 'Picaroon',
		webUrl: 'https://www.theguardian.com/profile/picaroon',
	},
	date: 1729987200000,
	webPublicationDate: 1729983645000,
	entries: [
		{
			id: '4-across',
			number: 4,
			humanNumber: '4',
			clue: 'American friend had to convert founder of a religion (6)',
			direction: 'across',
			length: 6,
			group: ['4-across'],
			position: {
				x: 0,
				y: 1,
			},
			separatorLocations: {},
			solution: 'BUDDHA',
		},
		{
			id: '6-across',
			number: 6,
			humanNumber: '6',
			clue: 'How steak may be cooked that’s good for you! (4,4)',
			direction: 'across',
			length: 8,
			group: ['6-across'],
			position: {
				x: 7,
				y: 1,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'WELLDONE',
		},
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: 'Ultimately endure conclusions of Royal Family (6)',
			direction: 'across',
			length: 6,
			group: ['9-across'],
			position: {
				x: 0,
				y: 3,
			},
			separatorLocations: {},
			solution: 'LASTLY',
		},
		{
			id: '10-across',
			number: 10,
			humanNumber: '10',
			clue: 'Faulty hearing – Mr Ali’s troubled with it (8)',
			direction: 'across',
			length: 8,
			group: ['10-across'],
			position: {
				x: 7,
				y: 3,
			},
			separatorLocations: {},
			solution: 'MISTRIAL',
		},
		{
			id: '11-across',
			number: 11,
			humanNumber: '11',
			clue: 'Liam and Noel playing with toy in a way that arouses feelings (11)',
			direction: 'across',
			length: 11,
			group: ['11-across'],
			position: {
				x: 0,
				y: 5,
			},
			separatorLocations: {},
			solution: 'EMOTIONALLY',
		},
		{
			id: '15-across',
			number: 15,
			humanNumber: '15',
			clue: 'In text that’s rewritten, entertaining chapter vanished (7)',
			direction: 'across',
			length: 7,
			group: ['15-across'],
			position: {
				x: 0,
				y: 7,
			},
			separatorLocations: {},
			solution: 'EXTINCT',
		},
		{
			id: '17-across',
			number: 17,
			humanNumber: '17',
			clue: 'Perhaps May in that place by South Africa’s capital (7)',
			direction: 'across',
			length: 7,
			group: ['17-across'],
			position: {
				x: 8,
				y: 7,
			},
			separatorLocations: {},
			solution: 'THERESA',
		},
		{
			id: '18-across',
			number: 18,
			humanNumber: '18',
			clue: 'Stage make-up isn’t put on musical lead in Phantom (6,5)',
			direction: 'across',
			length: 11,
			group: ['18-across'],
			position: {
				x: 4,
				y: 9,
			},
			separatorLocations: {
				',': [6],
			},
			solution: 'GREASEPAINT',
		},
		{
			id: '22-across',
			number: 22,
			humanNumber: '22',
			clue: 'MP has not drunk spirits (8)',
			direction: 'across',
			length: 8,
			group: ['22-across'],
			position: {
				x: 0,
				y: 11,
			},
			separatorLocations: {},
			solution: 'PHANTOMS',
		},
		{
			id: '23-across',
			number: 23,
			humanNumber: '23',
			clue: 'Laud unclothed couple’s childminder (2,4)',
			direction: 'across',
			length: 6,
			group: ['23-across'],
			position: {
				x: 9,
				y: 11,
			},
			separatorLocations: {
				',': [2],
			},
			solution: 'AUPAIR',
		},
		{
			id: '24-across',
			number: 24,
			humanNumber: '24',
			clue: 'Leo stole crackers, getting release from captivity (3,5)',
			direction: 'across',
			length: 8,
			group: ['24-across'],
			position: {
				x: 0,
				y: 13,
			},
			separatorLocations: {
				',': [3],
			},
			solution: 'LETLOOSE',
		},
		{
			id: '25-across',
			number: 25,
			humanNumber: '25',
			clue: 'Saw blade’s edges grasped (6)',
			direction: 'across',
			length: 6,
			group: ['25-across'],
			position: {
				x: 9,
				y: 13,
			},
			separatorLocations: {},
			solution: 'BEHELD',
		},
		{
			id: '1-down',
			number: 1,
			humanNumber: '1',
			clue: 'Condiment that’s hot in cold starter from Indian (6)',
			direction: 'down',
			length: 6,
			group: ['1-down'],
			position: {
				x: 4,
				y: 0,
			},
			separatorLocations: {},
			solution: 'CHILLI',
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2',
			clue: 'Member one criticises makes laws (10)',
			direction: 'down',
			length: 10,
			group: ['2-down'],
			position: {
				x: 8,
				y: 0,
			},
			separatorLocations: {},
			solution: 'LEGISLATES',
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'Problem for driver in boring old Phoenician city (4,4)',
			direction: 'down',
			length: 8,
			group: ['3-down'],
			position: {
				x: 10,
				y: 0,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'FLATTYRE',
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: 'Bishop always conceals untruth for person with faith (8)',
			direction: 'down',
			length: 8,
			group: ['4-down'],
			position: {
				x: 0,
				y: 1,
			},
			separatorLocations: {},
			solution: 'BELIEVER',
		},
		{
			id: '5-down',
			number: 5,
			humanNumber: '5',
			clue: 'Perverts or some antibourgeois Trots idling around (8)',
			direction: 'down',
			length: 8,
			group: ['5-down'],
			position: {
				x: 2,
				y: 1,
			},
			separatorLocations: {},
			solution: 'DISTORTS',
		},
		{
			id: '7-down',
			number: 7,
			humanNumber: '7',
			clue: 'Exclude from old American university (4)',
			direction: 'down',
			length: 4,
			group: ['7-down'],
			position: {
				x: 12,
				y: 1,
			},
			separatorLocations: {},
			solution: 'OMIT',
		},
		{
			id: '8-down',
			number: 8,
			humanNumber: '8',
			clue: 'Snake-like fish in small shelter, turning around (4)',
			direction: 'down',
			length: 4,
			group: ['8-down'],
			position: {
				x: 14,
				y: 1,
			},
			separatorLocations: {},
			solution: 'EELS',
		},
		{
			id: '12-down',
			number: 12,
			humanNumber: '12',
			clue: 'Contents of fine thermos that’s nearest the bottom (10)',
			direction: 'down',
			length: 10,
			group: ['12-down'],
			position: {
				x: 6,
				y: 5,
			},
			separatorLocations: {},
			solution: 'NETHERMOST',
		},
		{
			id: '13-down',
			number: 13,
			humanNumber: '13',
			clue: 'Ms Blanchett admitting bitterness about having no partner (8)',
			direction: 'down',
			length: 8,
			group: ['13-down'],
			position: {
				x: 12,
				y: 6,
			},
			separatorLocations: {},
			solution: 'CELIBATE',
		},
		{
			id: '14-down',
			number: 14,
			humanNumber: '14',
			clue: 'Beaten cricketer with England gutted (8)',
			direction: 'down',
			length: 8,
			group: ['14-down'],
			position: {
				x: 14,
				y: 6,
			},
			separatorLocations: {},
			solution: 'BATTERED',
		},
		{
			id: '16-down',
			number: 16,
			humanNumber: '16',
			clue: 'Denial, for example, when entering country (8)',
			direction: 'down',
			length: 8,
			group: ['16-down'],
			position: {
				x: 4,
				y: 7,
			},
			separatorLocations: {},
			solution: 'NEGATION',
		},
		{
			id: '19-down',
			number: 19,
			humanNumber: '19',
			clue: 'Someone who cuts dried fruit, right? (6)',
			direction: 'down',
			length: 6,
			group: ['19-down'],
			position: {
				x: 10,
				y: 9,
			},
			separatorLocations: {},
			solution: 'PRUNER',
		},
		{
			id: '20-down',
			number: 20,
			humanNumber: '20',
			clue: 'Precious stone in ring put on friend (4)',
			direction: 'down',
			length: 4,
			group: ['20-down'],
			position: {
				x: 0,
				y: 10,
			},
			separatorLocations: {},
			solution: 'OPAL',
		},
		{
			id: '21-down',
			number: 21,
			humanNumber: '21',
			clue: 'Don’t eat the kind of food served at McDonald’s (4)',
			direction: 'down',
			length: 4,
			group: ['21-down'],
			position: {
				x: 2,
				y: 10,
			},
			separatorLocations: {},
			solution: 'FAST',
		},
	],
	solutionAvailable: true,
	dateSolutionAvailable: 1729983600000,
	dimensions: {
		cols: 15,
		rows: 15,
	},
	crosswordType: 'quiptic',
};
