import type { CrosswordData } from '../@types/crossword';

export const special: CrosswordData = {
	id: 'crosswords/special/1',
	number: 1,
	name: 'Special crossword No 1',
	creator: {
		name: 'Sphinx',
		webUrl: 'https://www.theguardian.com/profile/sphinx',
	},
	date: 1729296000000,
	webPublicationDate: 1729292402000,
	entries: [
		{
			id: '1-across',
			number: 1,
			humanNumber: '1',
			clue: 'After substitution, go use ball on one Hungarian player (4,6)',
			direction: 'across',
			length: 10,
			group: ['1-across'],
			position: {
				x: 0,
				y: 0,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'BELALUGOSI',
		},
		{
			id: '6-across',
			number: 6,
			humanNumber: '6',
			clue: 'No oriental regulations about libel (4)',
			direction: 'across',
			length: 4,
			group: ['6-across'],
			position: {
				x: 11,
				y: 0,
			},
			separatorLocations: {},
			solution: 'SLUR',
		},
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: 'Colour plasmas for the aristocracy! (10)',
			direction: 'across',
			length: 10,
			group: ['9-across'],
			position: {
				x: 0,
				y: 2,
			},
			separatorLocations: {},
			solution: 'BLUEBLOODS',
		},
		{
			id: '10-across',
			number: 10,
			humanNumber: '10',
			clue: '<i>Catastrophe</i><span> is the return of humour</span> (4)',
			direction: 'across',
			length: 4,
			group: ['10-across'],
			position: {
				x: 11,
				y: 2,
			},
			separatorLocations: {},
			solution: 'DOOM',
		},
		{
			id: '12-across',
			number: 12,
			humanNumber: '12',
			clue: 'Unscrupulous doctor deployed tanner’s knife (12)',
			direction: 'across',
			length: 12,
			group: ['12-across'],
			position: {
				x: 3,
				y: 4,
			},
			separatorLocations: {},
			solution: 'FRANKENSTEIN',
		},
		{
			id: '15-across',
			number: 15,
			humanNumber: '15',
			clue: 'Exposes footloose trainee in Norfolk town (9)',
			direction: 'across',
			length: 9,
			group: ['15-across'],
			position: {
				x: 0,
				y: 6,
			},
			separatorLocations: {},
			solution: 'DISINTERS',
		},
		{
			id: '17-across',
			number: 17,
			humanNumber: '17',
			clue: 'Ratty’s ship follows crow non-stop (5)',
			direction: 'across',
			length: 5,
			group: ['17-across'],
			position: {
				x: 10,
				y: 6,
			},
			separatorLocations: {},
			solution: 'CROSS',
		},
		{
			id: '18-across',
			number: 18,
			humanNumber: '18',
			clue: 'Sponge rear of foot round about first sign of carbuncles (5)',
			direction: 'across',
			length: 5,
			group: ['18-across'],
			position: {
				x: 0,
				y: 8,
			},
			separatorLocations: {},
			solution: 'LEECH',
		},
		{
			id: '19-across',
			number: 19,
			humanNumber: '19',
			clue: 'Criticise actors before mid-point entrance (9)',
			direction: 'across',
			length: 9,
			group: ['19-across'],
			position: {
				x: 6,
				y: 8,
			},
			separatorLocations: {},
			solution: 'CASTIGATE',
		},
		{
			id: '20-across',
			number: 20,
			humanNumber: '20',
			clue: 'Drain life force from nauseating ex-criminal (12)',
			direction: 'across',
			length: 12,
			group: ['20-across'],
			position: {
				x: 0,
				y: 10,
			},
			separatorLocations: {},
			solution: 'EXSANGUINATE',
		},
		{
			id: '24-across',
			number: 24,
			humanNumber: '24',
			clue: 'Mountain dweller to be found in 9 (4)',
			direction: 'across',
			length: 4,
			group: ['24-across'],
			position: {
				x: 0,
				y: 12,
			},
			separatorLocations: {},
			solution: 'IBEX',
		},
		{
			id: '25-across',
			number: 25,
			humanNumber: '25',
			clue: 'Four competing in political party before sharing the spoils (8,2)',
			direction: 'across',
			length: 10,
			group: ['25-across'],
			position: {
				x: 5,
				y: 12,
			},
			separatorLocations: {
				',': [8],
			},
			solution: 'DIVVYINGUP',
		},
		{
			id: '26-across',
			number: 26,
			humanNumber: '26',
			clue: 'Eats bananas – gorge! (4)',
			direction: 'across',
			length: 4,
			group: ['26-across'],
			position: {
				x: 0,
				y: 14,
			},
			separatorLocations: {},
			solution: 'SATE',
		},
		{
			id: '27-across',
			number: 27,
			humanNumber: '27',
			clue: '‘Early closing’ relative pronounces, ‘makes more room’ (10)',
			direction: 'across',
			length: 10,
			group: ['27-across'],
			position: {
				x: 5,
				y: 14,
			},
			separatorLocations: {},
			solution: 'UNCLUTTERS',
		},
		{
			id: '1-down',
			number: 1,
			humanNumber: '1',
			clue: 'Wee one has thumb tip in mouth (4)',
			direction: 'down',
			length: 4,
			group: ['1-down'],
			position: {
				x: 0,
				y: 0,
			},
			separatorLocations: {},
			solution: 'BABY',
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2',
			clue: 'Powerful backing-duo opening for Lulu (4)',
			direction: 'down',
			length: 4,
			group: ['2-down'],
			position: {
				x: 2,
				y: 0,
			},
			separatorLocations: {},
			solution: 'LOUD',
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'Twisting ends of tidal flora, in the briny, all at sea (12)',
			direction: 'down',
			length: 12,
			group: ['3-down'],
			position: {
				x: 4,
				y: 0,
			},
			separatorLocations: {},
			solution: 'LABYRINTHINE',
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: '<span>Matriarch imbibes fourth of </span><i>Famous Grouse</i> (5)',
			direction: 'down',
			length: 5,
			group: ['4-down'],
			position: {
				x: 6,
				y: 0,
			},
			separatorLocations: {},
			solution: 'GROAN',
		},
		{
			id: '5-down',
			number: 5,
			humanNumber: '5',
			clue: 'The German recalled small city on the Ruhr reversing sorrows (9)',
			direction: 'down',
			length: 9,
			group: ['5-down'],
			position: {
				x: 8,
				y: 0,
			},
			separatorLocations: {},
			solution: 'SADNESSES',
		},
		{
			id: '7-down',
			number: 7,
			humanNumber: '7',
			clue: 'She’s easy, ladies, to attach to old chap! (5,5)',
			direction: 'down',
			length: 10,
			group: ['7-down'],
			position: {
				x: 12,
				y: 0,
			},
			separatorLocations: {
				',': [5],
			},
			solution: 'LOOSEWOMAN',
		},
		{
			id: '8-down',
			number: 8,
			humanNumber: '8',
			clue: 'Reviewed vehicles with lead chassis in plant (10)',
			direction: 'down',
			length: 10,
			group: ['8-down'],
			position: {
				x: 14,
				y: 0,
			},
			separatorLocations: {},
			solution: 'REMINISCED',
		},
		{
			id: '11-down',
			number: 11,
			humanNumber: '11',
			clue: 'Does doctor pry at his tics? (12)',
			direction: 'down',
			length: 12,
			group: ['11-down'],
			position: {
				x: 10,
				y: 3,
			},
			separatorLocations: {},
			solution: 'PSYCHIATRIST',
		},
		{
			id: '13-down',
			number: 13,
			humanNumber: '13',
			clue: 'Men and women gather round lake for infidelities (10)',
			direction: 'down',
			length: 10,
			group: ['13-down'],
			position: {
				x: 0,
				y: 5,
			},
			separatorLocations: {},
			solution: 'ADULTERIES',
		},
		{
			id: '14-down',
			number: 14,
			humanNumber: '14',
			clue: 'Fools Saturday workers, on time for appraisal (10)',
			direction: 'down',
			length: 10,
			group: ['14-down'],
			position: {
				x: 2,
				y: 5,
			},
			separatorLocations: {},
			solution: 'ASSESSMENT',
		},
		{
			id: '16-down',
			number: 16,
			humanNumber: '16',
			clue: 'One is devastated about pointless clues in team elimination (9)',
			direction: 'down',
			length: 9,
			group: ['16-down'],
			position: {
				x: 6,
				y: 6,
			},
			separatorLocations: {},
			solution: 'EXCLUSION',
		},
		{
			id: '21-down',
			number: 21,
			humanNumber: '21',
			clue: '<span>New </span><i>Strangelove</i><span> story?</span> (5)',
			direction: 'down',
			length: 5,
			group: ['21-down'],
			position: {
				x: 8,
				y: 10,
			},
			separatorLocations: {},
			solution: 'NOVEL',
		},
		{
			id: '22-down',
			number: 22,
			humanNumber: '22',
			clue: 'Every other conger eel is a monster (4)',
			direction: 'down',
			length: 4,
			group: ['22-down'],
			position: {
				x: 12,
				y: 11,
			},
			separatorLocations: {},
			solution: 'OGRE',
		},
		{
			id: '23-down',
			number: 23,
			humanNumber: '23',
			clue: 'Musical work sounds like catcalling! (4)',
			direction: 'down',
			length: 4,
			group: ['23-down'],
			position: {
				x: 14,
				y: 11,
			},
			separatorLocations: {},
			solution: 'OPUS',
		},
	],
	solutionAvailable: true,
	dateSolutionAvailable: 1729292400000,
	dimensions: {
		cols: 15,
		rows: 15,
	},
	crosswordType: 'special',
	instructions:
		'This is the puzzle seen onscreen in the BBC’s 2020 production of Dracula, compiled by Steve Pemberton.',
};
