import type { CAPICrossword } from '../@types/CAPI';

export const weekend: CAPICrossword = {
	id: 'crosswords/weekend/720',
	number: 720,
	name: 'Weekend crossword No 720',
	creator: {
		name: 'Sy',
		webUrl: 'https://www.theguardian.com/profile/sy',
	},
	date: 1729900800000,
	webPublicationDate: 1729897217000,
	entries: [
		{
			id: '7-across',
			number: 7,
			humanNumber: '7',
			clue: 'Tree cultivated especially in China and Japan for its yellow-orange fruit (6)',
			direction: 'across',
			length: 6,
			group: ['7-across'],
			position: {
				x: 0,
				y: 1,
			},
			separatorLocations: {},
			solution: 'LOQUAT',
		},
		{
			id: '8-across',
			number: 8,
			humanNumber: '8',
			clue: 'The Lebanese capital (6)',
			direction: 'across',
			length: 6,
			group: ['8-across'],
			position: {
				x: 7,
				y: 1,
			},
			separatorLocations: {},
			solution: 'BEIRUT',
		},
		{
			id: '9-across',
			number: 9,
			humanNumber: '9',
			clue: 'Yiddish-derived word for the kind of audacity shown by 2/3? (8)',
			direction: 'across',
			length: 8,
			group: ['9-across'],
			position: {
				x: 0,
				y: 3,
			},
			separatorLocations: {},
			solution: 'CHUTZPAH',
		},
		{
			id: '10-across',
			number: 10,
			humanNumber: '10',
			clue: 'The employer of, amongst others, Harry Bosch and Kate Lockley? (1,1,1,1)',
			direction: 'across',
			length: 4,
			group: ['10-across'],
			position: {
				x: 9,
				y: 3,
			},
			separatorLocations: {
				',': [1, 2, 3],
			},
			solution: 'LAPD',
		},
		{
			id: '11-across',
			number: 11,
			humanNumber: '11',
			clue: 'The __; Constable painting used by 2/3 activists in a protest action (3,4)',
			direction: 'across',
			length: 7,
			group: ['11-across'],
			position: {
				x: 0,
				y: 5,
			},
			separatorLocations: {
				',': [3],
			},
			solution: 'HAYWAIN',
		},
		{
			id: '13-across',
			number: 13,
			humanNumber: '13',
			clue: 'Astrological sign represented by the scales of justice (5)',
			direction: 'across',
			length: 5,
			group: ['13-across'],
			position: {
				x: 8,
				y: 5,
			},
			separatorLocations: {},
			solution: 'LIBRA',
		},
		{
			id: '15-across',
			number: 15,
			humanNumber: '15',
			clue: 'Ethnic group from the Niger delta (5)',
			direction: 'across',
			length: 5,
			group: ['15-across'],
			position: {
				x: 0,
				y: 7,
			},
			separatorLocations: {},
			solution: 'OGONI',
		},
		{
			id: '17-across',
			number: 17,
			humanNumber: '17',
			clue: 'City on the Tigris (7)',
			direction: 'across',
			length: 7,
			group: ['17-across'],
			position: {
				x: 6,
				y: 7,
			},
			separatorLocations: {},
			solution: 'BAGHDAD',
		},
		{
			id: '20-across',
			number: 20,
			humanNumber: '20, 6',
			clue: 'The __, Leonardo painting used by 2/3 activists in a protest action (4,6)',
			direction: 'across',
			length: 4,
			group: ['20-across', '6-down'],
			position: {
				x: 0,
				y: 9,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'LAST',
		},
		{
			id: '21-across',
			number: 21,
			humanNumber: '21',
			clue: 'A colourful parrot (8)',
			direction: 'across',
			length: 8,
			group: ['21-across'],
			position: {
				x: 5,
				y: 9,
			},
			separatorLocations: {},
			solution: 'LORIKEET',
		},
		{
			id: '23-across',
			number: 23,
			humanNumber: '23',
			clue: 'Polymath known for his 1959 lecture, The Two Cultures (1,1,4)',
			direction: 'across',
			length: 6,
			group: ['23-across'],
			position: {
				x: 0,
				y: 11,
			},
			separatorLocations: {
				',': [1, 2],
			},
			solution: 'CPSNOW',
		},
		{
			id: '24-across',
			number: 24,
			humanNumber: '24',
			clue: 'A town in Nottinghamshire but a city in New Jersey? (6)',
			direction: 'across',
			length: 6,
			group: ['24-across'],
			position: {
				x: 7,
				y: 11,
			},
			separatorLocations: {},
			solution: 'NEWARK',
		},
		{
			id: '1-down',
			number: 1,
			humanNumber: '1',
			clue: 'The sixth book of the Old Testament (6)',
			direction: 'down',
			length: 6,
			group: ['1-down'],
			position: {
				x: 1,
				y: 0,
			},
			separatorLocations: {},
			solution: 'JOSHUA',
		},
		{
			id: '2-down',
			number: 2,
			humanNumber: '2, 3',
			clue: 'Campaign group seeking to end fossil fuel extraction by 2030 (4,4,3)',
			direction: 'down',
			length: 4,
			group: ['2-down', '3-down'],
			position: {
				x: 3,
				y: 0,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'JUST',
		},
		{
			id: '3-down',
			number: 3,
			humanNumber: '3',
			clue: 'See 2',
			direction: 'down',
			length: 7,
			group: ['2-down', '3-down'],
			position: {
				x: 5,
				y: 0,
			},
			separatorLocations: {
				',': [4],
			},
			solution: 'STOPOIL',
		},
		{
			id: '4-down',
			number: 4,
			humanNumber: '4',
			clue: 'The Berlin subway system (1-4)',
			direction: 'down',
			length: 5,
			group: ['4-down'],
			position: {
				x: 7,
				y: 0,
			},
			separatorLocations: {
				'-': [1],
			},
			solution: 'UBAHN',
		},
		{
			id: '5-down',
			number: 5,
			humanNumber: '5, 18, 14',
			clue: 'Vermeer painting used by 2/3 activists in a protest action (4,4,1,5,7)',
			direction: 'down',
			length: 8,
			group: ['5-down', '18-down', '14-down'],
			position: {
				x: 9,
				y: 0,
			},
			separatorLocations: {
				',': [4, 8],
			},
			solution: 'GIRLWITH',
		},
		{
			id: '6-down',
			number: 6,
			humanNumber: '6',
			clue: 'See 20 Across',
			direction: 'down',
			length: 6,
			group: ['20-across', '6-down'],
			position: {
				x: 11,
				y: 0,
			},
			separatorLocations: {
				',': [],
			},
			solution: 'SUPPER',
		},
		{
			id: '12-down',
			number: 12,
			humanNumber: '12',
			clue: 'Ray __, actor whose films include Sexy Beast and Black Widow (8)',
			direction: 'down',
			length: 8,
			group: ['12-down'],
			position: {
				x: 3,
				y: 5,
			},
			separatorLocations: {},
			solution: 'WINSTONE',
		},
		{
			id: '14-down',
			number: 14,
			humanNumber: '14',
			clue: 'See 5',
			direction: 'down',
			length: 7,
			group: ['5-down', '18-down', '14-down'],
			position: {
				x: 7,
				y: 6,
			},
			separatorLocations: {
				',': [],
			},
			solution: 'EARRING',
		},
		{
			id: '16-down',
			number: 16,
			humanNumber: '16',
			clue: 'Pomace brandy from Italy (6)',
			direction: 'down',
			length: 6,
			group: ['16-down'],
			position: {
				x: 1,
				y: 7,
			},
			separatorLocations: {},
			solution: 'GRAPPA',
		},
		{
			id: '18-down',
			number: 18,
			humanNumber: '18',
			clue: 'See 5',
			direction: 'down',
			length: 6,
			group: ['5-down', '18-down', '14-down'],
			position: {
				x: 11,
				y: 7,
			},
			separatorLocations: {
				',': [1, 6],
			},
			solution: 'APEARL',
		},
		{
			id: '19-down',
			number: 19,
			humanNumber: '19',
			clue: 'The profession of Krusty, Bozo and Joseph Grimaldi? (5)',
			direction: 'down',
			length: 5,
			group: ['19-down'],
			position: {
				x: 5,
				y: 8,
			},
			separatorLocations: {},
			solution: 'CLOWN',
		},
		{
			id: '22-down',
			number: 22,
			humanNumber: '22',
			clue: 'Fruit – or person – from New Zealand (4)',
			direction: 'down',
			length: 4,
			group: ['22-down'],
			position: {
				x: 9,
				y: 9,
			},
			separatorLocations: {},
			solution: 'KIWI',
		},
	],
	solutionAvailable: true,
	dateSolutionAvailable: 1729897200000,
	dimensions: {
		cols: 13,
		rows: 13,
	},
	crosswordType: 'weekend',
	pdf: 'https://crosswords-static.guim.co.uk/gdn.weekend.20241026.pdf',
};
