#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# make sure we're using the correct version of node
. ./tools/scripts/check-node-version

# keep docs up to date
node tools/scripts/maintain-readme/index.mjs
git add README.md

corepack pnpm lint-staged
