#!/usr/bin/env bash

tmp=.temp-import

mkdir -p $tmp

curl -L -O --create-dirs --output-dir $tmp https://github.com/guardian/libs/archive/main.tar.gz

tar -xvf $tmp/main.tar.gz --directory libs/@guardian/libs  --strip-components 1 \
	libs-main/src \
	libs-main/scripts \
	libs-main/static \
	libs-main/README.md \
	libs-main/package.json

rm -rf "$tmp"
