# To save £££, we only run the Chromatic tests once the `run_chromatic` label is
# applied. This workflow reminds people to add the label because it isn't always
# obvious.

name: Chromatic Label Helper

on:
  pull_request:
    types: [opened]

jobs:
  write_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const comment = [
              "> [!TIP]",
              "> Once this PR is ready to go, add the `run_chromatic` label to run the Chromatic tests.",
              ">",
              "> _This saves us a lot of money by not running the tests before we need them._",
            ].join('\n');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
