name: 'Update Colour Tokens'

on:
  push:
    branches: [oa/design-tokens-figma]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # enables use to use the cache in actions/setup-node
      - uses: pnpm/action-setup@v2.4.0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: setup git credentials
        run: |
          git config user.name "GH Action Token Updater"
          git config user.email "actions@users.noreply.github.com"

      - name: Create or update branch
        run: |
          git fetch origin automated-update-tokens
          git checkout -b automated-update-tokens || git checkout automated-update-tokens
          git reset --hard origin/automated-update-tokens
          git pull --rebase origin automated-update-tokens

      - name: Update tokens
        run: pnpm nx run @csnx/design-tokens:make-tokens

      - name: Add changes update branch
        run: |
          git add .
          git commit -m "Update color tokens" -a
          git push origin automated-update-tokens

      - name: Create Pull Request
        run: |
          gh pr create -B main -H automated-update-tokens --title '[Automated] Update Color Tokens' --body 'This is an automated PR to update color tokens'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
