name: Sourcepoint Integration Tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Every day at 9am

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-env

      - run: make @guardian/libs:sourcepoint-integration-tes

      - run: |
          curl -X POST "${{ secrets.SOURCEPOINT_INTEGRATION_TEST_NOTIFICATION }}" \
          --header "Content-Type: application/json" \
          -d '{"text": "Sourcepoint Integration Tests failed! Has the Sourcepoint vendor list changed?"}'
        if: ${{ failure() }}
