name: source package usage tracker
on:
  schedule:
    # Every work day of the week at 08:08
    - cron: '8 8 * * MON-FRI'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/denoland/setup-deno#latest-stable-for-a-major
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Source tracker
        run: |
          deno run \
            --allow-read \
            --allow-net \
            --allow-sys=uid \
            --allow-env=TMPDIR,GITHUB_TOKEN \
            scripts/deno/source-tracker/mod.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
