# testing out using workflow_run to trigger a workflow from another workflow.
# this will be triggered by test-a.yml

name: Test B
on:
  workflow_run:
    workflows: [Test A]
    types:
      - completed

# && github.event.workflow_run.event == 'pull_request'
# && contains(github.event.workflow_run.pull_requests[0].labels.*.name, 'run_chromatic')
# || (
#   github.event_name == 'pull_request_target'
#   && github.event.action == 'labeled'
#   && contains(github.event.pull_request.labels.*.name, 'run_chromatic')
# )

jobs:
  say-things-b:
    if: |
      (
        github.event_name == 'workflow_run'
          && github.event.workflow_run.conclusion == 'success'
      )

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - message: thing 1
          - message: thing 2

    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.message }}
