# testing out using workflow_run to trigger a workflow from another workflow.
# this will trigger test-b.yml

name: Test A
on:
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  say-things-a:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - message: thing 1
          - message: thing 2

    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.message }}
